
-- Add runes to items
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('RAISER_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'conquering_rune_t1', '<green>Rune of Conquering (Tier I)', 1, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('RAISER_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'conquering_rune_t2', '<blue>Rune of Conquering (Tier II)', 2, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('RAISER_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'conquering_rune_t3', '<yellow>Rune of Conquering (Tier III)', 3, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WARD_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'reinforcing_rune_t1', '<green>Rune of Reinforcing (Tier I)', 1, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WARD_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'reinforcing_rune_t2', '<blue>Rune of Reinforcing (Tier II)', 2, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WARD_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'reinforcing_rune_t3', '<yellow>Rune of Reinforcing (Tier III)', 3, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('EYE_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'power_rune_t1', '<green>Rune of Power (Tier I)', 1, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('EYE_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'power_rune_t2', '<blue>Rune of Power (Tier II)', 2, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('EYE_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'power_rune_t3', '<yellow>Rune of Power (Tier III)', 3, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'insight_rune_t1', '<green>Rune of Insight (Tier I)', 1, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'insight_rune_t2', '<blue>Rune of Insight (Tier II)', 2, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'insight_rune_t3', '<yellow>Rune of Insight (Tier III)', 3, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('RIB_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'haste_rune_t4', '<orange>Rune of Haste (Tier IV)', 4, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WILD_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'unbreaking_rune_t1', '<green>Rune of Unbreaking (Tier I)', 1, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WILD_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'unbreaking_rune_t2', '<blue>Rune of Unbreaking (Tier II)', 2, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WILD_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'unbreaking_rune_t3', '<yellow>Rune of Unbreaking (Tier III)', 3, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('WILD_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'unbreaking_rune_t4', '<orange>Rune of Unbreaking (Tier IV)', 4, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'alacrity_rune_t4', '<orange>Rune of Alacrity (Tier IV)', 4, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'frost_rune_t3', '<yellow>Rune of Frost (Tier III)', 3, 0, 0);
INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE', 'champions', 'frost_rune_t4', '<orange>Rune of Frost (Tier IV)', 4, 0, 0);