/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables.records;


import me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaughtByClient;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetBiggestFishCaughtByClientRecord extends TableRecordImpl<GetBiggestFishCaughtByClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_biggest_fish_caught_by_client.id</code>.
     */
    public GetBiggestFishCaughtByClientRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_biggest_fish_caught_by_client.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.get_biggest_fish_caught_by_client.client_uuid</code>.
     */
    public GetBiggestFishCaughtByClientRecord setClientUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_biggest_fish_caught_by_client.client_uuid</code>.
     */
    public String getClientUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.get_biggest_fish_caught_by_client.type</code>.
     */
    public GetBiggestFishCaughtByClientRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.get_biggest_fish_caught_by_client.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.get_biggest_fish_caught_by_client.weight</code>.
     */
    public GetBiggestFishCaughtByClientRecord setWeight(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.get_biggest_fish_caught_by_client.weight</code>.
     */
    public Integer getWeight() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetBiggestFishCaughtByClientRecord
     */
    public GetBiggestFishCaughtByClientRecord() {
        super(GetBiggestFishCaughtByClient.GET_BIGGEST_FISH_CAUGHT_BY_CLIENT);
    }

    /**
     * Create a detached, initialised GetBiggestFishCaughtByClientRecord
     */
    public GetBiggestFishCaughtByClientRecord(Integer id, String clientUuid, String type, Integer weight) {
        super(GetBiggestFishCaughtByClient.GET_BIGGEST_FISH_CAUGHT_BY_CLIENT);

        setId(id);
        setClientUuid(clientUuid);
        setType(type);
        setWeight(weight);
        resetChangedOnNotNull();
    }
}
