/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables.records;


import me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingWeight;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetClientFishingWeightRecord extends TableRecordImpl<GetClientFishingWeightRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_client_fishing_weight.total_weight</code>.
     */
    public GetClientFishingWeightRecord setTotalWeight(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_client_fishing_weight.total_weight</code>.
     */
    public Long getTotalWeight() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetClientFishingWeightRecord
     */
    public GetClientFishingWeightRecord() {
        super(GetClientFishingWeight.GET_CLIENT_FISHING_WEIGHT);
    }

    /**
     * Create a detached, initialised GetClientFishingWeightRecord
     */
    public GetClientFishingWeightRecord(Long totalWeight) {
        super(GetClientFishingWeight.GET_CLIENT_FISHING_WEIGHT);

        setTotalWeight(totalWeight);
        resetChangedOnNotNull();
    }
}
