/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables.records;


import me.mykindos.betterpvp.progression.database.jooq.tables.GetTopMiningByOre;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopMiningByOreRecord extends TableRecordImpl<GetTopMiningByOreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_top_mining_by_ore.client_uuid</code>.
     */
    public GetTopMiningByOreRecord setClientUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_top_mining_by_ore.client_uuid</code>.
     */
    public String getClientUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.get_top_mining_by_ore.total_amount_mined</code>.
     */
    public GetTopMiningByOreRecord setTotalAmountMined(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_top_mining_by_ore.total_amount_mined</code>.
     */
    public Integer getTotalAmountMined() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetTopMiningByOreRecord
     */
    public GetTopMiningByOreRecord() {
        super(GetTopMiningByOre.GET_TOP_MINING_BY_ORE);
    }

    /**
     * Create a detached, initialised GetTopMiningByOreRecord
     */
    public GetTopMiningByOreRecord(String clientUuid, Integer totalAmountMined) {
        super(GetTopMiningByOre.GET_TOP_MINING_BY_ORE);

        setClientUuid(clientUuid);
        setTotalAmountMined(totalAmountMined);
        resetChangedOnNotNull();
    }
}
