/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables.records;


import me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByCount;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopFishingByCountRecord extends TableRecordImpl<GetTopFishingByCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_top_fishing_by_count.client_uuid</code>.
     */
    public GetTopFishingByCountRecord setClientUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_top_fishing_by_count.client_uuid</code>.
     */
    public String getClientUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.get_top_fishing_by_count.fish_count</code>.
     */
    public GetTopFishingByCountRecord setFishCount(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_top_fishing_by_count.fish_count</code>.
     */
    public Long getFishCount() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetTopFishingByCountRecord
     */
    public GetTopFishingByCountRecord() {
        super(GetTopFishingByCount.GET_TOP_FISHING_BY_COUNT);
    }

    /**
     * Create a detached, initialised GetTopFishingByCountRecord
     */
    public GetTopFishingByCountRecord(String clientUuid, Long fishCount) {
        super(GetTopFishingByCount.GET_TOP_FISHING_BY_COUNT);

        setClientUuid(clientUuid);
        setFishCount(fishCount);
        resetChangedOnNotNull();
    }
}
