/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables.records;


import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionProperties;

import org.jooq.Record4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgressionPropertiesRecord extends UpdatableRecordImpl<ProgressionPropertiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.progression_properties.client</code>.
     */
    public ProgressionPropertiesRecord setClient(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_properties.client</code>.
     */
    public Long getClient() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.progression_properties.season</code>.
     */
    public ProgressionPropertiesRecord setSeason(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_properties.season</code>.
     */
    public Integer getSeason() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.progression_properties.profession</code>.
     */
    public ProgressionPropertiesRecord setProfession(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_properties.profession</code>.
     */
    public String getProfession() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.progression_properties.property</code>.
     */
    public ProgressionPropertiesRecord setProperty(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_properties.property</code>.
     */
    public String getProperty() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.progression_properties.value</code>.
     */
    public ProgressionPropertiesRecord setValue(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_properties.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<Long, Integer, String, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgressionPropertiesRecord
     */
    public ProgressionPropertiesRecord() {
        super(ProgressionProperties.PROGRESSION_PROPERTIES);
    }

    /**
     * Create a detached, initialised ProgressionPropertiesRecord
     */
    public ProgressionPropertiesRecord(Long client, Integer season, String profession, String property, String value) {
        super(ProgressionProperties.PROGRESSION_PROPERTIES);

        setClient(client);
        setSeason(season);
        setProfession(profession);
        setProperty(property);
        setValue(value);
        resetChangedOnNotNull();
    }
}
