/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables.records;


import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionWoodcutting;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgressionWoodcuttingRecord extends UpdatableRecordImpl<ProgressionWoodcuttingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.progression_woodcutting.id</code>.
     */
    public ProgressionWoodcuttingRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_woodcutting.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.progression_woodcutting.client</code>.
     */
    public ProgressionWoodcuttingRecord setClient(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_woodcutting.client</code>.
     */
    public Long getClient() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.progression_woodcutting.season</code>.
     */
    public ProgressionWoodcuttingRecord setSeason(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_woodcutting.season</code>.
     */
    public Integer getSeason() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.progression_woodcutting.material</code>.
     */
    public ProgressionWoodcuttingRecord setMaterial(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_woodcutting.material</code>.
     */
    public String getMaterial() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.progression_woodcutting.location</code>.
     */
    public ProgressionWoodcuttingRecord setLocation(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_woodcutting.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.progression_woodcutting.amount</code>.
     */
    public ProgressionWoodcuttingRecord setAmount(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_woodcutting.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.progression_woodcutting.timestamp</code>.
     */
    public ProgressionWoodcuttingRecord setTimestamp(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.progression_woodcutting.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgressionWoodcuttingRecord
     */
    public ProgressionWoodcuttingRecord() {
        super(ProgressionWoodcutting.PROGRESSION_WOODCUTTING);
    }

    /**
     * Create a detached, initialised ProgressionWoodcuttingRecord
     */
    public ProgressionWoodcuttingRecord(Integer id, Long client, Integer season, String material, String location, Integer amount, Long timestamp) {
        super(ProgressionWoodcutting.PROGRESSION_WOODCUTTING);

        setId(id);
        setClient(client);
        setSeason(season);
        setMaterial(material);
        setLocation(location);
        setAmount(amount);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }
}
