/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.shops.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.shops.database.jooq.Keys;
import me.mykindos.betterpvp.shops.database.jooq.Public;
import me.mykindos.betterpvp.shops.database.jooq.tables.Shopitems.ShopitemsPath;
import me.mykindos.betterpvp.shops.database.jooq.tables.records.ShopitemsFlagsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShopitemsFlags extends TableImpl<ShopitemsFlagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shopitems_flags</code>
     */
    public static final ShopitemsFlags SHOPITEMS_FLAGS = new ShopitemsFlags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShopitemsFlagsRecord> getRecordType() {
        return ShopitemsFlagsRecord.class;
    }

    /**
     * The column <code>public.shopitems_flags.id</code>.
     */
    public final TableField<ShopitemsFlagsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.shopitems_flags.shop_item_id</code>.
     */
    public final TableField<ShopitemsFlagsRecord, Integer> SHOP_ITEM_ID = createField(DSL.name("shop_item_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.shopitems_flags.persistent_key</code>.
     */
    public final TableField<ShopitemsFlagsRecord, String> PERSISTENT_KEY = createField(DSL.name("persistent_key"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.shopitems_flags.persistent_value</code>.
     */
    public final TableField<ShopitemsFlagsRecord, String> PERSISTENT_VALUE = createField(DSL.name("persistent_value"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private ShopitemsFlags(Name alias, Table<ShopitemsFlagsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShopitemsFlags(Name alias, Table<ShopitemsFlagsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.shopitems_flags</code> table reference
     */
    public ShopitemsFlags(String alias) {
        this(DSL.name(alias), SHOPITEMS_FLAGS);
    }

    /**
     * Create an aliased <code>public.shopitems_flags</code> table reference
     */
    public ShopitemsFlags(Name alias) {
        this(alias, SHOPITEMS_FLAGS);
    }

    /**
     * Create a <code>public.shopitems_flags</code> table reference
     */
    public ShopitemsFlags() {
        this(DSL.name("shopitems_flags"), null);
    }

    public <O extends Record> ShopitemsFlags(Table<O> path, ForeignKey<O, ShopitemsFlagsRecord> childPath, InverseForeignKey<O, ShopitemsFlagsRecord> parentPath) {
        super(path, childPath, parentPath, SHOPITEMS_FLAGS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShopitemsFlagsPath extends ShopitemsFlags implements Path<ShopitemsFlagsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShopitemsFlagsPath(Table<O> path, ForeignKey<O, ShopitemsFlagsRecord> childPath, InverseForeignKey<O, ShopitemsFlagsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShopitemsFlagsPath(Name alias, Table<ShopitemsFlagsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShopitemsFlagsPath as(String alias) {
            return new ShopitemsFlagsPath(DSL.name(alias), this);
        }

        @Override
        public ShopitemsFlagsPath as(Name alias) {
            return new ShopitemsFlagsPath(alias, this);
        }

        @Override
        public ShopitemsFlagsPath as(Table<?> alias) {
            return new ShopitemsFlagsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ShopitemsFlagsRecord, Integer> getIdentity() {
        return (Identity<ShopitemsFlagsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShopitemsFlagsRecord> getPrimaryKey() {
        return Keys.SHOPITEMS_FLAGS_PKEY;
    }

    @Override
    public List<ForeignKey<ShopitemsFlagsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHOPITEMS_FLAGS__SHOPITEMS_FLAGS_SHOP_ITEM_ID_FKEY);
    }

    private transient ShopitemsPath _shopitems;

    /**
     * Get the implicit join path to the <code>public.shopitems</code> table.
     */
    public ShopitemsPath shopitems() {
        if (_shopitems == null)
            _shopitems = new ShopitemsPath(this, Keys.SHOPITEMS_FLAGS__SHOPITEMS_FLAGS_SHOP_ITEM_ID_FKEY, null);

        return _shopitems;
    }

    @Override
    public ShopitemsFlags as(String alias) {
        return new ShopitemsFlags(DSL.name(alias), this);
    }

    @Override
    public ShopitemsFlags as(Name alias) {
        return new ShopitemsFlags(alias, this);
    }

    @Override
    public ShopitemsFlags as(Table<?> alias) {
        return new ShopitemsFlags(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopitemsFlags rename(String name) {
        return new ShopitemsFlags(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopitemsFlags rename(Name name) {
        return new ShopitemsFlags(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopitemsFlags rename(Table<?> name) {
        return new ShopitemsFlags(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopitemsFlags where(Condition condition) {
        return new ShopitemsFlags(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopitemsFlags where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopitemsFlags where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopitemsFlags where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopitemsFlags where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopitemsFlags where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopitemsFlags where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopitemsFlags where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopitemsFlags whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopitemsFlags whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
