/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.shops.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.shops.database.jooq.Keys;
import me.mykindos.betterpvp.shops.database.jooq.Public;
import me.mykindos.betterpvp.shops.database.jooq.tables.ShopitemsDynamicPricing.ShopitemsDynamicPricingPath;
import me.mykindos.betterpvp.shops.database.jooq.tables.ShopitemsFlags.ShopitemsFlagsPath;
import me.mykindos.betterpvp.shops.database.jooq.tables.records.ShopitemsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Shopitems extends TableImpl<ShopitemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shopitems</code>
     */
    public static final Shopitems SHOPITEMS = new Shopitems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShopitemsRecord> getRecordType() {
        return ShopitemsRecord.class;
    }

    /**
     * The column <code>public.shopitems.id</code>.
     */
    public final TableField<ShopitemsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.shopitems.shopkeeper</code>.
     */
    public final TableField<ShopitemsRecord, String> SHOPKEEPER = createField(DSL.name("shopkeeper"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.shopitems.material</code>.
     */
    public final TableField<ShopitemsRecord, String> MATERIAL = createField(DSL.name("material"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.shopitems.item_name</code>.
     */
    public final TableField<ShopitemsRecord, String> ITEM_NAME = createField(DSL.name("item_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.shopitems.model_data</code>.
     */
    public final TableField<ShopitemsRecord, Integer> MODEL_DATA = createField(DSL.name("model_data"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.shopitems.menu_slot</code>.
     */
    public final TableField<ShopitemsRecord, Integer> MENU_SLOT = createField(DSL.name("menu_slot"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.shopitems.menu_page</code>.
     */
    public final TableField<ShopitemsRecord, Integer> MENU_PAGE = createField(DSL.name("menu_page"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.shopitems.amount</code>.
     */
    public final TableField<ShopitemsRecord, Integer> AMOUNT = createField(DSL.name("amount"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.shopitems.buy_price</code>.
     */
    public final TableField<ShopitemsRecord, Integer> BUY_PRICE = createField(DSL.name("buy_price"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.shopitems.sell_price</code>.
     */
    public final TableField<ShopitemsRecord, Integer> SELL_PRICE = createField(DSL.name("sell_price"), SQLDataType.INTEGER.nullable(false), this, "");

    private Shopitems(Name alias, Table<ShopitemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Shopitems(Name alias, Table<ShopitemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.shopitems</code> table reference
     */
    public Shopitems(String alias) {
        this(DSL.name(alias), SHOPITEMS);
    }

    /**
     * Create an aliased <code>public.shopitems</code> table reference
     */
    public Shopitems(Name alias) {
        this(alias, SHOPITEMS);
    }

    /**
     * Create a <code>public.shopitems</code> table reference
     */
    public Shopitems() {
        this(DSL.name("shopitems"), null);
    }

    public <O extends Record> Shopitems(Table<O> path, ForeignKey<O, ShopitemsRecord> childPath, InverseForeignKey<O, ShopitemsRecord> parentPath) {
        super(path, childPath, parentPath, SHOPITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShopitemsPath extends Shopitems implements Path<ShopitemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShopitemsPath(Table<O> path, ForeignKey<O, ShopitemsRecord> childPath, InverseForeignKey<O, ShopitemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShopitemsPath(Name alias, Table<ShopitemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShopitemsPath as(String alias) {
            return new ShopitemsPath(DSL.name(alias), this);
        }

        @Override
        public ShopitemsPath as(Name alias) {
            return new ShopitemsPath(alias, this);
        }

        @Override
        public ShopitemsPath as(Table<?> alias) {
            return new ShopitemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ShopitemsRecord, Integer> getIdentity() {
        return (Identity<ShopitemsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShopitemsRecord> getPrimaryKey() {
        return Keys.SHOPITEMS_PKEY;
    }

    @Override
    public List<UniqueKey<ShopitemsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SHOPITEMS_SHOPKEEPER_MATERIAL_ITEMNAME_UK);
    }

    private transient ShopitemsDynamicPricingPath _shopitemsDynamicPricing;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shopitems_dynamic_pricing</code> table
     */
    public ShopitemsDynamicPricingPath shopitemsDynamicPricing() {
        if (_shopitemsDynamicPricing == null)
            _shopitemsDynamicPricing = new ShopitemsDynamicPricingPath(this, null, Keys.SHOPITEMS_DYNAMIC_PRICING__SHOPITEMS_DYNAMIC_PRICING_SHOP_ITEM_ID_FKEY.getInverseKey());

        return _shopitemsDynamicPricing;
    }

    private transient ShopitemsFlagsPath _shopitemsFlags;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shopitems_flags</code> table
     */
    public ShopitemsFlagsPath shopitemsFlags() {
        if (_shopitemsFlags == null)
            _shopitemsFlags = new ShopitemsFlagsPath(this, null, Keys.SHOPITEMS_FLAGS__SHOPITEMS_FLAGS_SHOP_ITEM_ID_FKEY.getInverseKey());

        return _shopitemsFlags;
    }

    @Override
    public Shopitems as(String alias) {
        return new Shopitems(DSL.name(alias), this);
    }

    @Override
    public Shopitems as(Name alias) {
        return new Shopitems(alias, this);
    }

    @Override
    public Shopitems as(Table<?> alias) {
        return new Shopitems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Shopitems rename(String name) {
        return new Shopitems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shopitems rename(Name name) {
        return new Shopitems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shopitems rename(Table<?> name) {
        return new Shopitems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shopitems where(Condition condition) {
        return new Shopitems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shopitems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shopitems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shopitems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shopitems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shopitems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shopitems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shopitems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shopitems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shopitems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
