author: Rey
main: me.mykindos.betterpvp.hub.Hub
bootstrapper: me.mykindos.betterpvp.hub.HubBootstrap
name: Hub
load: POSTWORLD
version: '1.0'
api-version: '1.21'
dependencies:
  server:
    Core:
      load: BEFORE
      required: true
      join-classpath: true
    Mapper:
      load: BEFORE
      required: true
      join-classpath: true
    Champions:
      load: BEFORE
      required: false
      join-classpath: true