CREATE TABLE IF NOT EXISTS filtered_words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(36) NULL
);

ALTER TABLE filtered_words ADD INDEX (word);