core:
  info:
    server: Clans-1
    season: Season 1
  database:
    supabase:
      url: "https://wenrbemzbvclukhgmbgz.supabase.co"
      anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlbnJiZW16YnZjbHVraGdtYmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNzA2MjEsImV4cCI6MjA3NDc0NjYyMX0.Pup-qcJLl7MNPy7DbW3SOyNoYAODc7XB5AvP5Yo8n4M"
    global:
      databaseName: betterpvp
      username: user
      password: BetterPvP123!
      ip: 127.0.0.1:5002
      maxPoolSize: 10
  tips:
    timeBetweenTips: 150.0
  exceptions:
    discord-webhook: ''
  pepper: ''
  resourcepack:
    enabled: true
pvp:
  enableOldPvP: true
  hitboxExpansion: 0.0
  hitboxCooldown: 0.0
  mythic-damage-indicators:
    duration: 1.5
    enabled: true
    scale: 1.1
  mythic-health-bars:
    enabled: true
  showKillerHealth: true
gamer:
  default:
    coins: 5000
    fragments: 0
    pvpprotection: 3600.0
hunger:
  enabled: false
discord:
  chatWebhook: ''
  invite: https://discord.gg/Q4XvxH7
resourcepack:
  enabled: false
  force: false
  sha: 972f72a7b2c8cca7ce2ad8087ddf0a256b146700
  url: https://betterpvp.net/latestpack.zip
  filepath: pack.zip
  selfhost: false
weather:
  enabled: false
items:
  hideAttributes: true
  hideEnchants: true
  drop-protection:
    required-drops: 5
    expiry-seconds: 2.0
  treeFeller:
    cooldown: 20.0
    maxBlocks: 130
command:
  promote:
    enabled: true
    requiredRank: ADMIN
  list:
    enabled: true
    requiredRank: ADMIN
  teleport:
    enabled: true
    requiredRank: ADMIN
  teleportposition:
    enabled: true
    requiredRank: ADMIN
  client:
    enabled: true
    requiredRank: ADMIN
    admin:
      enabled: true
      requiredRank: ADMIN
    search:
      enabled: true
      requiredRank: ADMIN
    promote:
      enabled: true
      requiredRank: ADMIN
    demote:
      enabled: true
      requiredRank: ADMIN
    count:
      enabled: true
      requiredRank: ADMIN
    setmediachannel:
      enabled: true
      requiredRank: ADMIN
  admin:
    enabled: true
    requiredRank: PLAYER
  teleportworld:
    enabled: true
    requiredRank: ADMIN
  kick:
    enabled: true
    requiredRank: ADMIN
  search:
    enabled: true
    requiredRank: ADMIN
    online:
      enabled: true
      requiredRank: ADMIN
    player:
      enabled: true
      requiredRank: ADMIN
    item:
      enabled: true
      requiredRank: ADMIN
  teleporthere:
    enabled: true
    requiredRank: ADMIN
  test:
    enabled: true
    requiredRank: ADMIN
  gamemode:
    enabled: true
    requiredRank: ADMIN
    creative:
      enabled: true
      requiredRank: ADMIN
    survival:
      enabled: true
      requiredRank: ADMIN
    adventure:
      enabled: true
      requiredRank: ADMIN
    spectator:
      enabled: true
      requiredRank: ADMIN
      test:
        enabled: true
        requiredRank: ADMIN
  setspawn:
    enabled: true
    requiredRank: ADMIN
  core:
    enabled: true
    requiredRank: ADMIN
    reload:
      enabled: true
      requiredRank: ADMIN
  settings:
    enabled: true
    requiredRank: PLAYER
  heal:
    enabled: true
    requiredRank: ADMIN
  balance:
    enabled: true
    requiredRank: PLAYER
    pay:
      enabled: true
      requiredRank: PLAYER
    give:
      enabled: true
      requiredRank: ADMIN
    get:
      enabled: true
      requiredRank: PLAYER
    set:
      enabled: true
      requiredRank: ADMIN
  iteminfo:
    enabled: true
    requiredRank: ADMIN
  spawn:
    enabled: true
    requiredRank: ADMIN
  kill:
    enabled: true
    requiredRank: PLAYER
  leaderboard:
    enabled: true
    requiredRank: PLAYER
  staffchat:
    enabled: true
    requiredRank: TRIAL_MOD
  display:
    enabled: true
    requiredRank: ADMIN
    select:
      enabled: true
      requiredRank: ADMIN
    deselect:
      enabled: true
      requiredRank: ADMIN
    summon:
      enabled: true
      requiredRank: ADMIN
      rotate:
        enabled: true
        requiredRank: ADMIN
    remove:
      enabled: true
      requiredRank: ADMIN
    transform:
      enabled: true
      requiredRank: ADMIN
      rotate:
        enabled: true
        requiredRank: ADMIN
      scale:
        enabled: true
        requiredRank: ADMIN
      Translate:
        enabled: true
        requiredRank: ADMIN
      translate:
        enabled: true
        requiredRank: ADMIN
    interpolation:
      enabled: true
      requiredRank: ADMIN
  messageadmin:
    enabled: true
    requiredRank: HELPER
  replyadmin:
    enabled: true
    requiredRank: HELPER
  broadcast:
    enabled: true
    requiredRank: MODERATOR
  invsee:
    enabled: true
    requiredRank: ADMIN
  hat:
    enabled: true
    requiredRank: PLAYER
  customeffect:
    enabled: true
    requiredRank: ADMIN
    give:
      enabled: true
      requiredRank: ADMIN
    clear:
      enabled: true
      requiredRank: ADMIN
  customgive:
    enabled: true
    requiredRank: ADMIN
  reply:
    enabled: true
    requiredRank: PLAYER
  message:
    enabled: true
    requiredRank: PLAYER
  tip:
    enabled: true
    requiredRank: PLAYER
  setviewdistance:
    enabled: true
    requiredRank: ADMIN
  log:
    enabled: true
    requiredRank: ADMIN
    legend:
      enabled: true
      requiredRank: ADMIN
  world:
    enabled: true
    requiredRank: ADMIN
  punish:
    enabled: true
    requiredRank: TRIAL_MOD
    add:
      enabled: true
      requiredRank: TRIAL_MOD
    remove:
      enabled: true
      requiredRank: TRIAL_MOD
    history:
      enabled: true
      requiredRank: TRIAL_MOD
  loadpack:
    enabled: true
    requiredRank: ADMIN
  unfreeze:
    enabled: true
    requiredRank: MODERATOR
  freeze:
    enabled: true
    requiredRank: MODERATOR
  daily:
    enabled: true
    requiredRank: ADMIN
  showitem:
    enabled: true
    requiredRank: PLAYER
  showeffects:
    enabled: true
    requiredRank: PLAYER
  setprotection:
    enabled: true
    requiredRank: MODERATOR
  protection:
    enabled: true
    requiredRank: PLAYER
  silencechat:
    enabled: true
    requiredRank: MODERATOR
  unloadpack:
    enabled: true
    requiredRank: ADMIN
  logout:
    enabled: true
    requiredRank: PLAYER
  playtime:
    enabled: true
    requiredRank: PLAYER
  ignore:
    enabled: true
    requiredRank: PLAYER
  vanish:
    enabled: true
    requiredRank: ADMIN
  punishmenthistory:
    enabled: true
    requiredRank: PLAYER
  legacypunish:
    enabled: true
    requiredRank: ADMIN
    add:
      enabled: true
      requiredRank: ADMIN
    custom:
      enabled: true
      requiredRank: ADMIN
    history:
      enabled: true
      requiredRank: ADMIN
    remove:
      enabled: true
      requiredRank: ADMIN
  rules:
    enabled: true
    requiredRank: PLAYER
  clear:
    enabled: true
    requiredRank: ADMIN
  npc:
    enabled: true
    requiredRank: ADMIN
    list:
      enabled: true
      requiredRank: ADMIN
    spawn:
      enabled: true
      requiredRank: ADMIN
    remove:
      enabled: true
      requiredRank: ADMIN
  logpurge:
    enabled: true
    requiredRank: ADMIN
  offlinemessages:
    enabled: true
    requiredRank: PLAYER
  adminofflinemessages:
    enabled: true
    requiredRank: ADMIN
  worldlogger:
    enabled: true
    requiredRank: MODERATOR
    inspect:
      enabled: true
      requiredRank: MODERATOR
    page:
      enabled: true
      requiredRank: MODERATOR
    rollback:
      enabled: true
      requiredRank: ADMIN
    restore:
      enabled: true
      requiredRank: ADMIN
    restorechunk:
      enabled: true
      requiredRank: ADMIN
  channel:
    enabled: true
    requiredRank: ADMIN
  centerself:
    enabled: true
    requiredRank: ADMIN
  droptable:
    enabled: true
    requiredRank: PLAYER
  rewardstest:
    enabled: true
    requiredRank: ADMIN
  rewards:
    enabled: true
    requiredRank: PLAYER
  chatfilter:
    enabled: true
    requiredRank: MODERATOR
    add:
      enabled: true
      requiredRank: ADMIN
    reload:
      enabled: true
      requiredRank: ADMIN
    remove:
      enabled: true
      requiredRank: ADMIN
    list:
      enabled: true
      requiredRank: MODERATOR
  recipe:
    enabled: true
    requiredRank: PLAYER
  items:
    enabled: true
    requiredRank: PLAYER
  give:
    enabled: true
    requiredRank: ADMIN
  mockitem:
    enabled: true
    requiredRank: ADMIN
  loot:
    enabled: true
    requiredRank: PLAYER
  attune:
    enabled: true
    requiredRank: ADMIN
  reforge:
    enabled: true
    requiredRank: ADMIN
  achievements:
    enabled: true
    requiredRank: PLAYER
  profile:
    enabled: true
    requiredRank: PLAYER
  statsmenu:
    enabled: true
    requiredRank: PLAYER
  heatmap:
    enabled: true
    requiredRank: ADMIN
    here:
      enabled: true
      requiredRank: ADMIN
    top:
      enabled: true
      requiredRank: ADMIN
  shadowfilter:
    enabled: true
    requiredRank: ADMIN
    list:
      enabled: true
      requiredRank: ADMIN
    reload:
      enabled: true
      requiredRank: ADMIN
    remove:
      enabled: true
      requiredRank: ADMIN
    add:
      enabled: true
      requiredRank: ADMIN
  profilestats:
    enabled: true
    requiredRank: ADMIN
  refreshitemcache:
    enabled: true
    requiredRank: ADMIN
  discord:
    enabled: true
    requiredRank: PLAYER
  ping:
    enabled: true
    requiredRank: PLAYER
  sendtip:
    enabled: true
    requiredRank: ADMIN
tab:
  title: Welcome to BetterPvP!
  website: https://betterpvp.net
  server: Clans-1
  shop: /store
energy:
  nerf-energy-regen: false
  consumption-regen-delay: 0.5
  max-energy: 150.0
  energy-per-tick: 10.0
  energy-per-tick-nerfed: 4.0
  update-rate: 50
  energy-per-second: 15.0
server:
  unlimitedPlayers: true
  maxPlayers: 999
combatlog:
  valuable-items:
    - TNT
    - MUSIC_DISC_PIGSTEP
    - MUSIC_DISC_WAIT
    - MUSIC_DISC_13
  enabled: true
update-event:
  allow-rollover: false
daily:
  coinsAmount: 5000
spawns:
  RedShops: world, -448.5, 69.0, -472.5, 0.90197754, 3.4725707
  YellowShops: world, -447.5, 69.0, 473.5, -179.39539, -0.47505057
  BlueShops: world, 447.5, 68.0, -473.5, 0.16472624, -0.023868788
  GreenShops: world, 448.5, 68.0, 473.5, -179.7284, -0.31821498
tips:
  speedtip:
    enabled: true
    categoryWeight: 1
    weight: 1
  bleedtip:
    enabled: true
    categoryWeight: 1
    weight: 1
  strengthtip:
    enabled: true
    categoryWeight: 1
    weight: 1
  poisontip:
    enabled: true
    categoryWeight: 1
    weight: 1
  slownesstip:
    enabled: true
    categoryWeight: 1
    weight: 1
  tipstip:
    enabled: true
    categoryWeight: 1
    weight: 2
  craftingtip:
    enabled: true
    categoryWeight: 1
    weight: 1
protection:
  drop-pickup-time: 10.0
  reserve-time: 10.0
clans:
  coins:
    dropCoinsOnDeath: true
    percentCoinsDroppedOnDeath: 0.1
activity:
  threshold:
    active: 10.0
    hotspot: 25.0
    quiet: 5.0
  weight:
    combat: 1.0
    kill: 5.0
    presence: 1.0
  decay:
    dead-cell: 0.01
    factor: 0.85
  min-damage-threshold: 5.0
stats:
  enabled: true
achievements:
  enabled: true
ping:
  onlyStaffCanSeeOthers: true
repair:
  baseFraction: 0.33
  lifetimeMultiplier: 3
  reinforcementsPerPurityOrder: 3
  requiredSwings: 3
salvage:
  maxYield: 3
  minYield: 1
  purityBonus:
    high: 2
    low: 0
    mid: 1
  tierUpgradeChance: 0.2
