lunar:
  database:
    prefix: lunar_
command:
  lunar:
    enabled: true
    requiredRank: ADMIN
    reload:
      enabled: true
      requiredRank: ADMIN
# Web Config settings
# If enabled, the plugin will load from local files first,
# then override any values found in the web configuration.
# The web configuration supports directories for each plugin, e.g.:
# core/resourcepacks.yml, champions/skills/skills.yml, clans/config.yml
webconfig:
  enabled: false
  url: https://betterpvp.net/configs