/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables.records;


import me.mykindos.betterpvp.clans.database.jooq.tables.ClansFieldsOres;

import org.jooq.Record5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClansFieldsOresRecord extends UpdatableRecordImpl<ClansFieldsOresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clans_fields_ores.realm</code>.
     */
    public ClansFieldsOresRecord setRealm(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_fields_ores.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.clans_fields_ores.world</code>.
     */
    public ClansFieldsOresRecord setWorld(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_fields_ores.world</code>.
     */
    public String getWorld() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.clans_fields_ores.x</code>.
     */
    public ClansFieldsOresRecord setX(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_fields_ores.x</code>.
     */
    public Integer getX() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.clans_fields_ores.y</code>.
     */
    public ClansFieldsOresRecord setY(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_fields_ores.y</code>.
     */
    public Integer getY() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.clans_fields_ores.z</code>.
     */
    public ClansFieldsOresRecord setZ(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_fields_ores.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.clans_fields_ores.type</code>.
     */
    public ClansFieldsOresRecord setType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_fields_ores.type</code>.
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.clans_fields_ores.data</code>.
     */
    public ClansFieldsOresRecord setData(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_fields_ores.data</code>.
     */
    public String getData() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record5<Integer, String, Integer, Integer, Integer> key() {
        return (Record5) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClansFieldsOresRecord
     */
    public ClansFieldsOresRecord() {
        super(ClansFieldsOres.CLANS_FIELDS_ORES);
    }

    /**
     * Create a detached, initialised ClansFieldsOresRecord
     */
    public ClansFieldsOresRecord(Integer realm, String world, Integer x, Integer y, Integer z, String type, String data) {
        super(ClansFieldsOres.CLANS_FIELDS_ORES);

        setRealm(realm);
        setWorld(world);
        setX(x);
        setY(y);
        setZ(z);
        setType(type);
        setData(data);
        resetChangedOnNotNull();
    }
}
