/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables.records;


import me.mykindos.betterpvp.clans.database.jooq.tables.Clans;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClansRecord extends UpdatableRecordImpl<ClansRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clans.id</code>.
     */
    public ClansRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clans.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.clans.realm</code>.
     */
    public ClansRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clans.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.clans.name</code>.
     */
    public ClansRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clans.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clans.home</code>.
     */
    public ClansRecord setHome(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clans.home</code>.
     */
    public String getHome() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clans.admin</code>.
     */
    public ClansRecord setAdmin(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.clans.admin</code>.
     */
    public Integer getAdmin() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.clans.safe</code>.
     */
    public ClansRecord setSafe(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.clans.safe</code>.
     */
    public Integer getSafe() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClansRecord
     */
    public ClansRecord() {
        super(Clans.CLANS);
    }

    /**
     * Create a detached, initialised ClansRecord
     */
    public ClansRecord(Long id, Integer realm, String name, String home, Integer admin, Integer safe) {
        super(Clans.CLANS);

        setId(id);
        setRealm(realm);
        setName(name);
        setHome(home);
        setAdmin(admin);
        setSafe(safe);
        resetChangedOnNotNull();
    }
}
