/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables.records;


import me.mykindos.betterpvp.clans.database.jooq.tables.ClanTerritory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanTerritoryRecord extends UpdatableRecordImpl<ClanTerritoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clan_territory.id</code>.
     */
    public ClanTerritoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clan_territory.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.clan_territory.clan</code>.
     */
    public ClanTerritoryRecord setClan(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clan_territory.clan</code>.
     */
    public Long getClan() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.clan_territory.chunk</code>.
     */
    public ClanTerritoryRecord setChunk(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clan_territory.chunk</code>.
     */
    public String getChunk() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClanTerritoryRecord
     */
    public ClanTerritoryRecord() {
        super(ClanTerritory.CLAN_TERRITORY);
    }

    /**
     * Create a detached, initialised ClanTerritoryRecord
     */
    public ClanTerritoryRecord(Integer id, Long clan, String chunk) {
        super(ClanTerritory.CLAN_TERRITORY);

        setId(id);
        setClan(clan);
        setChunk(chunk);
        resetChangedOnNotNull();
    }
}
