/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables.records;


import me.mykindos.betterpvp.clans.database.jooq.tables.ClanMetadata;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanMetadataRecord extends UpdatableRecordImpl<ClanMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clan_metadata.clan</code>.
     */
    public ClanMetadataRecord setClan(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clan_metadata.clan</code>.
     */
    public Long getClan() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.clan_metadata.banner</code>.
     */
    public ClanMetadataRecord setBanner(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clan_metadata.banner</code>.
     */
    public String getBanner() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.clan_metadata.mailbox</code>.
     */
    public ClanMetadataRecord setMailbox(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clan_metadata.mailbox</code>.
     */
    public String getMailbox() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clan_metadata.vault</code>.
     */
    public ClanMetadataRecord setVault(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clan_metadata.vault</code>.
     */
    public String getVault() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClanMetadataRecord
     */
    public ClanMetadataRecord() {
        super(ClanMetadata.CLAN_METADATA);
    }

    /**
     * Create a detached, initialised ClanMetadataRecord
     */
    public ClanMetadataRecord(Long clan, String banner, String mailbox, String vault) {
        super(ClanMetadata.CLAN_METADATA);

        setClan(clan);
        setBanner(banner);
        setMailbox(mailbox);
        setVault(vault);
        resetChangedOnNotNull();
    }
}
