/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables.records;


import me.mykindos.betterpvp.clans.database.jooq.tables.ClansDominanceScale;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClansDominanceScaleRecord extends UpdatableRecordImpl<ClansDominanceScaleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clans_dominance_scale.clan_size</code>.
     */
    public ClansDominanceScaleRecord setClanSize(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_dominance_scale.clan_size</code>.
     */
    public Integer getClanSize() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.clans_dominance_scale.dominance</code>.
     */
    public ClansDominanceScaleRecord setDominance(Double value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clans_dominance_scale.dominance</code>.
     */
    public Double getDominance() {
        return (Double) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClansDominanceScaleRecord
     */
    public ClansDominanceScaleRecord() {
        super(ClansDominanceScale.CLANS_DOMINANCE_SCALE);
    }

    /**
     * Create a detached, initialised ClansDominanceScaleRecord
     */
    public ClansDominanceScaleRecord(Integer clanSize, Double dominance) {
        super(ClansDominanceScale.CLANS_DOMINANCE_SCALE);

        setClanSize(clanSize);
        setDominance(dominance);
        resetChangedOnNotNull();
    }
}
