/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables.records;


import me.mykindos.betterpvp.clans.database.jooq.tables.GetClanKillLogs;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetClanKillLogsRecord extends TableRecordImpl<GetClanKillLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_clan_kill_logs.killer</code>.
     */
    public GetClanKillLogsRecord setKiller(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.killer</code>.
     */
    public Long getKiller() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.get_clan_kill_logs.killer_name</code>.
     */
    public GetClanKillLogsRecord setKillerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.killer_name</code>.
     */
    public String getKillerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.get_clan_kill_logs.killer_clan</code>.
     */
    public GetClanKillLogsRecord setKillerClan(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.killer_clan</code>.
     */
    public Long getKillerClan() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.get_clan_kill_logs.victim</code>.
     */
    public GetClanKillLogsRecord setVictim(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.victim</code>.
     */
    public Long getVictim() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.get_clan_kill_logs.victim_name</code>.
     */
    public GetClanKillLogsRecord setVictimName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.victim_name</code>.
     */
    public String getVictimName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.get_clan_kill_logs.victim_clan</code>.
     */
    public GetClanKillLogsRecord setVictimClan(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.victim_clan</code>.
     */
    public Long getVictimClan() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.get_clan_kill_logs.dominance</code>.
     */
    public GetClanKillLogsRecord setDominance(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.dominance</code>.
     */
    public Double getDominance() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.get_clan_kill_logs.time_val</code>.
     */
    public GetClanKillLogsRecord setTimeVal(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.get_clan_kill_logs.time_val</code>.
     */
    public Long getTimeVal() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetClanKillLogsRecord
     */
    public GetClanKillLogsRecord() {
        super(GetClanKillLogs.GET_CLAN_KILL_LOGS);
    }

    /**
     * Create a detached, initialised GetClanKillLogsRecord
     */
    public GetClanKillLogsRecord(Long killer, String killerName, Long killerClan, Long victim, String victimName, Long victimClan, Double dominance, Long timeVal) {
        super(GetClanKillLogs.GET_CLAN_KILL_LOGS);

        setKiller(killer);
        setKillerName(killerName);
        setKillerClan(killerClan);
        setVictim(victim);
        setVictimName(victimName);
        setVictimClan(victimClan);
        setDominance(dominance);
        setTimeVal(timeVal);
        resetChangedOnNotNull();
    }
}
