author: Moonsworth LLC Development Team, Mykindos
main: me.mykindos.betterpvp.lunar.LunarClientAPI
name: Lunar
load: STARTUP
version: '1.0'
api-version: '1.20'
depend: [Core]
website: https://www.lunarclient.com/