/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetBiggestFishCaughtByClientRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetBiggestFishCaughtByClient extends TableImpl<GetBiggestFishCaughtByClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.get_biggest_fish_caught_by_client</code>
     */
    public static final GetBiggestFishCaughtByClient GET_BIGGEST_FISH_CAUGHT_BY_CLIENT = new GetBiggestFishCaughtByClient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetBiggestFishCaughtByClientRecord> getRecordType() {
        return GetBiggestFishCaughtByClientRecord.class;
    }

    /**
     * The column <code>public.get_biggest_fish_caught_by_client.id</code>.
     */
    public final TableField<GetBiggestFishCaughtByClientRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.get_biggest_fish_caught_by_client.client_uuid</code>.
     */
    public final TableField<GetBiggestFishCaughtByClientRecord, String> CLIENT_UUID = createField(DSL.name("client_uuid"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_biggest_fish_caught_by_client.type</code>.
     */
    public final TableField<GetBiggestFishCaughtByClientRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_biggest_fish_caught_by_client.weight</code>.
     */
    public final TableField<GetBiggestFishCaughtByClientRecord, Integer> WEIGHT = createField(DSL.name("weight"), SQLDataType.INTEGER, this, "");

    private GetBiggestFishCaughtByClient(Name alias, Table<GetBiggestFishCaughtByClientRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.BIGINT),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.DOUBLE),
            DSL.val(null, SQLDataType.INTEGER)
        });
    }

    private GetBiggestFishCaughtByClient(Name alias, Table<GetBiggestFishCaughtByClientRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetBiggestFishCaughtByClient(Name alias, Table<GetBiggestFishCaughtByClientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_biggest_fish_caught_by_client</code>
     * table reference
     */
    public GetBiggestFishCaughtByClient(String alias) {
        this(DSL.name(alias), GET_BIGGEST_FISH_CAUGHT_BY_CLIENT);
    }

    /**
     * Create an aliased <code>public.get_biggest_fish_caught_by_client</code>
     * table reference
     */
    public GetBiggestFishCaughtByClient(Name alias) {
        this(alias, GET_BIGGEST_FISH_CAUGHT_BY_CLIENT);
    }

    /**
     * Create a <code>public.get_biggest_fish_caught_by_client</code> table
     * reference
     */
    public GetBiggestFishCaughtByClient() {
        this(DSL.name("get_biggest_fish_caught_by_client"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetBiggestFishCaughtByClient as(String alias) {
        return new GetBiggestFishCaughtByClient(DSL.name(alias), this, parameters);
    }

    @Override
    public GetBiggestFishCaughtByClient as(Name alias) {
        return new GetBiggestFishCaughtByClient(alias, this, parameters);
    }

    @Override
    public GetBiggestFishCaughtByClient as(Table<?> alias) {
        return new GetBiggestFishCaughtByClient(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetBiggestFishCaughtByClient rename(String name) {
        return new GetBiggestFishCaughtByClient(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetBiggestFishCaughtByClient rename(Name name) {
        return new GetBiggestFishCaughtByClient(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetBiggestFishCaughtByClient rename(Table<?> name) {
        return new GetBiggestFishCaughtByClient(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetBiggestFishCaughtByClient call(
          Long pClientId
        , Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        GetBiggestFishCaughtByClient result = new GetBiggestFishCaughtByClient(DSL.name("get_biggest_fish_caught_by_client"), null, new Field[] {
            DSL.val(pClientId, SQLDataType.BIGINT),
            DSL.val(seasonParam, SQLDataType.INTEGER),
            DSL.val(days, SQLDataType.DOUBLE),
            DSL.val(maxResults, SQLDataType.INTEGER)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetBiggestFishCaughtByClient call(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<Double> days
        , Field<Integer> maxResults
    ) {
        GetBiggestFishCaughtByClient result = new GetBiggestFishCaughtByClient(DSL.name("get_biggest_fish_caught_by_client"), null, new Field[] {
            pClientId,
            seasonParam,
            days,
            maxResults
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
