/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetBiggestFishCaughtRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetBiggestFishCaught extends TableImpl<GetBiggestFishCaughtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_biggest_fish_caught</code>
     */
    public static final GetBiggestFishCaught GET_BIGGEST_FISH_CAUGHT = new GetBiggestFishCaught();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetBiggestFishCaughtRecord> getRecordType() {
        return GetBiggestFishCaughtRecord.class;
    }

    /**
     * The column <code>public.get_biggest_fish_caught.id</code>.
     */
    public final TableField<GetBiggestFishCaughtRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_biggest_fish_caught.client_uuid</code>.
     */
    public final TableField<GetBiggestFishCaughtRecord, String> CLIENT_UUID = createField(DSL.name("client_uuid"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_biggest_fish_caught.type</code>.
     */
    public final TableField<GetBiggestFishCaughtRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_biggest_fish_caught.weight</code>.
     */
    public final TableField<GetBiggestFishCaughtRecord, Integer> WEIGHT = createField(DSL.name("weight"), SQLDataType.INTEGER, this, "");

    private GetBiggestFishCaught(Name alias, Table<GetBiggestFishCaughtRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.DOUBLE),
            DSL.val(null, SQLDataType.INTEGER)
        });
    }

    private GetBiggestFishCaught(Name alias, Table<GetBiggestFishCaughtRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetBiggestFishCaught(Name alias, Table<GetBiggestFishCaughtRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_biggest_fish_caught</code> table
     * reference
     */
    public GetBiggestFishCaught(String alias) {
        this(DSL.name(alias), GET_BIGGEST_FISH_CAUGHT);
    }

    /**
     * Create an aliased <code>public.get_biggest_fish_caught</code> table
     * reference
     */
    public GetBiggestFishCaught(Name alias) {
        this(alias, GET_BIGGEST_FISH_CAUGHT);
    }

    /**
     * Create a <code>public.get_biggest_fish_caught</code> table reference
     */
    public GetBiggestFishCaught() {
        this(DSL.name("get_biggest_fish_caught"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetBiggestFishCaught as(String alias) {
        return new GetBiggestFishCaught(DSL.name(alias), this, parameters);
    }

    @Override
    public GetBiggestFishCaught as(Name alias) {
        return new GetBiggestFishCaught(alias, this, parameters);
    }

    @Override
    public GetBiggestFishCaught as(Table<?> alias) {
        return new GetBiggestFishCaught(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetBiggestFishCaught rename(String name) {
        return new GetBiggestFishCaught(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetBiggestFishCaught rename(Name name) {
        return new GetBiggestFishCaught(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetBiggestFishCaught rename(Table<?> name) {
        return new GetBiggestFishCaught(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetBiggestFishCaught call(
          Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        GetBiggestFishCaught result = new GetBiggestFishCaught(DSL.name("get_biggest_fish_caught"), null, new Field[] {
            DSL.val(seasonParam, SQLDataType.INTEGER),
            DSL.val(days, SQLDataType.DOUBLE),
            DSL.val(maxResults, SQLDataType.INTEGER)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetBiggestFishCaught call(
          Field<Integer> seasonParam
        , Field<Double> days
        , Field<Integer> maxResults
    ) {
        GetBiggestFishCaught result = new GetBiggestFishCaught(DSL.name("get_biggest_fish_caught"), null, new Field[] {
            seasonParam,
            days,
            maxResults
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
