/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetClientFishingCountRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetClientFishingCount extends TableImpl<GetClientFishingCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_client_fishing_count</code>
     */
    public static final GetClientFishingCount GET_CLIENT_FISHING_COUNT = new GetClientFishingCount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetClientFishingCountRecord> getRecordType() {
        return GetClientFishingCountRecord.class;
    }

    /**
     * The column <code>public.get_client_fishing_count.fish_count</code>.
     */
    public final TableField<GetClientFishingCountRecord, Long> FISH_COUNT = createField(DSL.name("fish_count"), SQLDataType.BIGINT, this, "");

    private GetClientFishingCount(Name alias, Table<GetClientFishingCountRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.BIGINT),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.DOUBLE)
        });
    }

    private GetClientFishingCount(Name alias, Table<GetClientFishingCountRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetClientFishingCount(Name alias, Table<GetClientFishingCountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_client_fishing_count</code> table
     * reference
     */
    public GetClientFishingCount(String alias) {
        this(DSL.name(alias), GET_CLIENT_FISHING_COUNT);
    }

    /**
     * Create an aliased <code>public.get_client_fishing_count</code> table
     * reference
     */
    public GetClientFishingCount(Name alias) {
        this(alias, GET_CLIENT_FISHING_COUNT);
    }

    /**
     * Create a <code>public.get_client_fishing_count</code> table reference
     */
    public GetClientFishingCount() {
        this(DSL.name("get_client_fishing_count"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetClientFishingCount as(String alias) {
        return new GetClientFishingCount(DSL.name(alias), this, parameters);
    }

    @Override
    public GetClientFishingCount as(Name alias) {
        return new GetClientFishingCount(alias, this, parameters);
    }

    @Override
    public GetClientFishingCount as(Table<?> alias) {
        return new GetClientFishingCount(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientFishingCount rename(String name) {
        return new GetClientFishingCount(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientFishingCount rename(Name name) {
        return new GetClientFishingCount(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientFishingCount rename(Table<?> name) {
        return new GetClientFishingCount(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetClientFishingCount call(
          Long pClientId
        , Integer seasonParam
        , Double days
    ) {
        GetClientFishingCount result = new GetClientFishingCount(DSL.name("get_client_fishing_count"), null, new Field[] {
            DSL.val(pClientId, SQLDataType.BIGINT),
            DSL.val(seasonParam, SQLDataType.INTEGER),
            DSL.val(days, SQLDataType.DOUBLE)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetClientFishingCount call(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<Double> days
    ) {
        GetClientFishingCount result = new GetClientFishingCount(DSL.name("get_client_fishing_count"), null, new Field[] {
            pClientId,
            seasonParam,
            days
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
