/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetClientOresMinedRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetClientOresMined extends TableImpl<GetClientOresMinedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_client_ores_mined</code>
     */
    public static final GetClientOresMined GET_CLIENT_ORES_MINED = new GetClientOresMined();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetClientOresMinedRecord> getRecordType() {
        return GetClientOresMinedRecord.class;
    }

    /**
     * The column <code>public.get_client_ores_mined.total_amount_mined</code>.
     */
    public final TableField<GetClientOresMinedRecord, Integer> TOTAL_AMOUNT_MINED = createField(DSL.name("total_amount_mined"), SQLDataType.INTEGER, this, "");

    private GetClientOresMined(Name alias, Table<GetClientOresMinedRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.BIGINT),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.CLOB.array())
        });
    }

    private GetClientOresMined(Name alias, Table<GetClientOresMinedRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetClientOresMined(Name alias, Table<GetClientOresMinedRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_client_ores_mined</code> table
     * reference
     */
    public GetClientOresMined(String alias) {
        this(DSL.name(alias), GET_CLIENT_ORES_MINED);
    }

    /**
     * Create an aliased <code>public.get_client_ores_mined</code> table
     * reference
     */
    public GetClientOresMined(Name alias) {
        this(alias, GET_CLIENT_ORES_MINED);
    }

    /**
     * Create a <code>public.get_client_ores_mined</code> table reference
     */
    public GetClientOresMined() {
        this(DSL.name("get_client_ores_mined"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetClientOresMined as(String alias) {
        return new GetClientOresMined(DSL.name(alias), this, parameters);
    }

    @Override
    public GetClientOresMined as(Name alias) {
        return new GetClientOresMined(alias, this, parameters);
    }

    @Override
    public GetClientOresMined as(Table<?> alias) {
        return new GetClientOresMined(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientOresMined rename(String name) {
        return new GetClientOresMined(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientOresMined rename(Name name) {
        return new GetClientOresMined(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientOresMined rename(Table<?> name) {
        return new GetClientOresMined(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetClientOresMined call(
          Long pClientId
        , Integer seasonParam
        , String[] blocks
    ) {
        GetClientOresMined result = new GetClientOresMined(DSL.name("get_client_ores_mined"), null, new Field[] {
            DSL.val(pClientId, SQLDataType.BIGINT),
            DSL.val(seasonParam, SQLDataType.INTEGER),
            DSL.val(blocks, SQLDataType.CLOB.array())
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetClientOresMined call(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<String[]> blocks
    ) {
        GetClientOresMined result = new GetClientOresMined(DSL.name("get_client_ores_mined"), null, new Field[] {
            pClientId,
            seasonParam,
            blocks
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
