/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetClientFishingWeightRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetClientFishingWeight extends TableImpl<GetClientFishingWeightRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_client_fishing_weight</code>
     */
    public static final GetClientFishingWeight GET_CLIENT_FISHING_WEIGHT = new GetClientFishingWeight();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetClientFishingWeightRecord> getRecordType() {
        return GetClientFishingWeightRecord.class;
    }

    /**
     * The column <code>public.get_client_fishing_weight.total_weight</code>.
     */
    public final TableField<GetClientFishingWeightRecord, Long> TOTAL_WEIGHT = createField(DSL.name("total_weight"), SQLDataType.BIGINT, this, "");

    private GetClientFishingWeight(Name alias, Table<GetClientFishingWeightRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.BIGINT),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.DOUBLE)
        });
    }

    private GetClientFishingWeight(Name alias, Table<GetClientFishingWeightRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetClientFishingWeight(Name alias, Table<GetClientFishingWeightRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_client_fishing_weight</code> table
     * reference
     */
    public GetClientFishingWeight(String alias) {
        this(DSL.name(alias), GET_CLIENT_FISHING_WEIGHT);
    }

    /**
     * Create an aliased <code>public.get_client_fishing_weight</code> table
     * reference
     */
    public GetClientFishingWeight(Name alias) {
        this(alias, GET_CLIENT_FISHING_WEIGHT);
    }

    /**
     * Create a <code>public.get_client_fishing_weight</code> table reference
     */
    public GetClientFishingWeight() {
        this(DSL.name("get_client_fishing_weight"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetClientFishingWeight as(String alias) {
        return new GetClientFishingWeight(DSL.name(alias), this, parameters);
    }

    @Override
    public GetClientFishingWeight as(Name alias) {
        return new GetClientFishingWeight(alias, this, parameters);
    }

    @Override
    public GetClientFishingWeight as(Table<?> alias) {
        return new GetClientFishingWeight(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientFishingWeight rename(String name) {
        return new GetClientFishingWeight(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientFishingWeight rename(Name name) {
        return new GetClientFishingWeight(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientFishingWeight rename(Table<?> name) {
        return new GetClientFishingWeight(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetClientFishingWeight call(
          Long pClientId
        , Integer seasonParam
        , Double days
    ) {
        GetClientFishingWeight result = new GetClientFishingWeight(DSL.name("get_client_fishing_weight"), null, new Field[] {
            DSL.val(pClientId, SQLDataType.BIGINT),
            DSL.val(seasonParam, SQLDataType.INTEGER),
            DSL.val(days, SQLDataType.DOUBLE)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetClientFishingWeight call(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<Double> days
    ) {
        GetClientFishingWeight result = new GetClientFishingWeight(DSL.name("get_client_fishing_weight"), null, new Field[] {
            pClientId,
            seasonParam,
            days
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
