/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetTopFishingByCountRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopFishingByCount extends TableImpl<GetTopFishingByCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_top_fishing_by_count</code>
     */
    public static final GetTopFishingByCount GET_TOP_FISHING_BY_COUNT = new GetTopFishingByCount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetTopFishingByCountRecord> getRecordType() {
        return GetTopFishingByCountRecord.class;
    }

    /**
     * The column <code>public.get_top_fishing_by_count.client_uuid</code>.
     */
    public final TableField<GetTopFishingByCountRecord, String> CLIENT_UUID = createField(DSL.name("client_uuid"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_top_fishing_by_count.fish_count</code>.
     */
    public final TableField<GetTopFishingByCountRecord, Long> FISH_COUNT = createField(DSL.name("fish_count"), SQLDataType.BIGINT, this, "");

    private GetTopFishingByCount(Name alias, Table<GetTopFishingByCountRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.DOUBLE),
            DSL.val(null, SQLDataType.INTEGER)
        });
    }

    private GetTopFishingByCount(Name alias, Table<GetTopFishingByCountRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetTopFishingByCount(Name alias, Table<GetTopFishingByCountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_top_fishing_by_count</code> table
     * reference
     */
    public GetTopFishingByCount(String alias) {
        this(DSL.name(alias), GET_TOP_FISHING_BY_COUNT);
    }

    /**
     * Create an aliased <code>public.get_top_fishing_by_count</code> table
     * reference
     */
    public GetTopFishingByCount(Name alias) {
        this(alias, GET_TOP_FISHING_BY_COUNT);
    }

    /**
     * Create a <code>public.get_top_fishing_by_count</code> table reference
     */
    public GetTopFishingByCount() {
        this(DSL.name("get_top_fishing_by_count"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetTopFishingByCount as(String alias) {
        return new GetTopFishingByCount(DSL.name(alias), this, parameters);
    }

    @Override
    public GetTopFishingByCount as(Name alias) {
        return new GetTopFishingByCount(alias, this, parameters);
    }

    @Override
    public GetTopFishingByCount as(Table<?> alias) {
        return new GetTopFishingByCount(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopFishingByCount rename(String name) {
        return new GetTopFishingByCount(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopFishingByCount rename(Name name) {
        return new GetTopFishingByCount(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopFishingByCount rename(Table<?> name) {
        return new GetTopFishingByCount(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetTopFishingByCount call(
          Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        GetTopFishingByCount result = new GetTopFishingByCount(DSL.name("get_top_fishing_by_count"), null, new Field[] {
            DSL.val(seasonParam, SQLDataType.INTEGER),
            DSL.val(days, SQLDataType.DOUBLE),
            DSL.val(maxResults, SQLDataType.INTEGER)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetTopFishingByCount call(
          Field<Integer> seasonParam
        , Field<Double> days
        , Field<Integer> maxResults
    ) {
        GetTopFishingByCount result = new GetTopFishingByCount(DSL.name("get_top_fishing_by_count"), null, new Field[] {
            seasonParam,
            days,
            maxResults
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
