/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import java.util.Collection;

import me.mykindos.betterpvp.progression.database.jooq.Keys;
import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.ProgressionPropertiesRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgressionProperties extends TableImpl<ProgressionPropertiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.progression_properties</code>
     */
    public static final ProgressionProperties PROGRESSION_PROPERTIES = new ProgressionProperties();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProgressionPropertiesRecord> getRecordType() {
        return ProgressionPropertiesRecord.class;
    }

    /**
     * The column <code>public.progression_properties.client</code>.
     */
    public final TableField<ProgressionPropertiesRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.progression_properties.season</code>.
     */
    public final TableField<ProgressionPropertiesRecord, Integer> SEASON = createField(DSL.name("season"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.progression_properties.profession</code>.
     */
    public final TableField<ProgressionPropertiesRecord, String> PROFESSION = createField(DSL.name("profession"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.progression_properties.property</code>.
     */
    public final TableField<ProgressionPropertiesRecord, String> PROPERTY = createField(DSL.name("property"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.progression_properties.value</code>.
     */
    public final TableField<ProgressionPropertiesRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private ProgressionProperties(Name alias, Table<ProgressionPropertiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProgressionProperties(Name alias, Table<ProgressionPropertiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.progression_properties</code> table
     * reference
     */
    public ProgressionProperties(String alias) {
        this(DSL.name(alias), PROGRESSION_PROPERTIES);
    }

    /**
     * Create an aliased <code>public.progression_properties</code> table
     * reference
     */
    public ProgressionProperties(Name alias) {
        this(alias, PROGRESSION_PROPERTIES);
    }

    /**
     * Create a <code>public.progression_properties</code> table reference
     */
    public ProgressionProperties() {
        this(DSL.name("progression_properties"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ProgressionPropertiesRecord> getPrimaryKey() {
        return Keys.PROGRESSION_PROPERTIES_PKEY;
    }

    @Override
    public ProgressionProperties as(String alias) {
        return new ProgressionProperties(DSL.name(alias), this);
    }

    @Override
    public ProgressionProperties as(Name alias) {
        return new ProgressionProperties(alias, this);
    }

    @Override
    public ProgressionProperties as(Table<?> alias) {
        return new ProgressionProperties(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionProperties rename(String name) {
        return new ProgressionProperties(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionProperties rename(Name name) {
        return new ProgressionProperties(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionProperties rename(Table<?> name) {
        return new ProgressionProperties(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionProperties where(Condition condition) {
        return new ProgressionProperties(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionProperties where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionProperties where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionProperties where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionProperties where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionProperties where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionProperties where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionProperties where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionProperties whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionProperties whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
