/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.progression.database.jooq.Indexes;
import me.mykindos.betterpvp.progression.database.jooq.Keys;
import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.ProgressionMiningRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgressionMining extends TableImpl<ProgressionMiningRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.progression_mining</code>
     */
    public static final ProgressionMining PROGRESSION_MINING = new ProgressionMining();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProgressionMiningRecord> getRecordType() {
        return ProgressionMiningRecord.class;
    }

    /**
     * The column <code>public.progression_mining.client</code>.
     */
    public final TableField<ProgressionMiningRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.progression_mining.season</code>.
     */
    public final TableField<ProgressionMiningRecord, Integer> SEASON = createField(DSL.name("season"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.progression_mining.material</code>.
     */
    public final TableField<ProgressionMiningRecord, String> MATERIAL = createField(DSL.name("material"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.progression_mining.amount_mined</code>.
     */
    public final TableField<ProgressionMiningRecord, Integer> AMOUNT_MINED = createField(DSL.name("amount_mined"), SQLDataType.INTEGER.nullable(false), this, "");

    private ProgressionMining(Name alias, Table<ProgressionMiningRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProgressionMining(Name alias, Table<ProgressionMiningRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.progression_mining</code> table reference
     */
    public ProgressionMining(String alias) {
        this(DSL.name(alias), PROGRESSION_MINING);
    }

    /**
     * Create an aliased <code>public.progression_mining</code> table reference
     */
    public ProgressionMining(Name alias) {
        this(alias, PROGRESSION_MINING);
    }

    /**
     * Create a <code>public.progression_mining</code> table reference
     */
    public ProgressionMining() {
        this(DSL.name("progression_mining"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PROGRESSION_MINING_CLIENT_SEASON_MATERIAL, Indexes.IDX_PROGRESSION_MINING_SEASON_MATERIAL);
    }

    @Override
    public UniqueKey<ProgressionMiningRecord> getPrimaryKey() {
        return Keys.PROGRESSION_MINING_PKEY;
    }

    @Override
    public ProgressionMining as(String alias) {
        return new ProgressionMining(DSL.name(alias), this);
    }

    @Override
    public ProgressionMining as(Name alias) {
        return new ProgressionMining(alias, this);
    }

    @Override
    public ProgressionMining as(Table<?> alias) {
        return new ProgressionMining(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionMining rename(String name) {
        return new ProgressionMining(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionMining rename(Name name) {
        return new ProgressionMining(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionMining rename(Table<?> name) {
        return new ProgressionMining(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionMining where(Condition condition) {
        return new ProgressionMining(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionMining where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionMining where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionMining where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionMining where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionMining where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionMining where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionMining where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionMining whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionMining whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
