/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.progression.database.jooq.Indexes;
import me.mykindos.betterpvp.progression.database.jooq.Keys;
import me.mykindos.betterpvp.progression.database.jooq.Public;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.ProgressionWoodcuttingRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgressionWoodcutting extends TableImpl<ProgressionWoodcuttingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.progression_woodcutting</code>
     */
    public static final ProgressionWoodcutting PROGRESSION_WOODCUTTING = new ProgressionWoodcutting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProgressionWoodcuttingRecord> getRecordType() {
        return ProgressionWoodcuttingRecord.class;
    }

    /**
     * The column <code>public.progression_woodcutting.id</code>.
     */
    public final TableField<ProgressionWoodcuttingRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.progression_woodcutting.client</code>.
     */
    public final TableField<ProgressionWoodcuttingRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.progression_woodcutting.season</code>.
     */
    public final TableField<ProgressionWoodcuttingRecord, Integer> SEASON = createField(DSL.name("season"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.progression_woodcutting.material</code>.
     */
    public final TableField<ProgressionWoodcuttingRecord, String> MATERIAL = createField(DSL.name("material"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.progression_woodcutting.location</code>.
     */
    public final TableField<ProgressionWoodcuttingRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.VARCHAR(285).nullable(false), this, "");

    /**
     * The column <code>public.progression_woodcutting.amount</code>.
     */
    public final TableField<ProgressionWoodcuttingRecord, Integer> AMOUNT = createField(DSL.name("amount"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.progression_woodcutting.timestamp</code>.
     */
    public final TableField<ProgressionWoodcuttingRecord, Long> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("((EXTRACT(epoch FROM now()) * (1000)::numeric))::bigint"), SQLDataType.BIGINT)), this, "");

    private ProgressionWoodcutting(Name alias, Table<ProgressionWoodcuttingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProgressionWoodcutting(Name alias, Table<ProgressionWoodcuttingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.progression_woodcutting</code> table
     * reference
     */
    public ProgressionWoodcutting(String alias) {
        this(DSL.name(alias), PROGRESSION_WOODCUTTING);
    }

    /**
     * Create an aliased <code>public.progression_woodcutting</code> table
     * reference
     */
    public ProgressionWoodcutting(Name alias) {
        this(alias, PROGRESSION_WOODCUTTING);
    }

    /**
     * Create a <code>public.progression_woodcutting</code> table reference
     */
    public ProgressionWoodcutting() {
        this(DSL.name("progression_woodcutting"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PROGRESSION_WOODCUTTING_CLIENT_SEASON_TIMESTAMP, Indexes.IDX_PROGRESSION_WOODCUTTING_TIMESTAMP);
    }

    @Override
    public Identity<ProgressionWoodcuttingRecord, Integer> getIdentity() {
        return (Identity<ProgressionWoodcuttingRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProgressionWoodcuttingRecord> getPrimaryKey() {
        return Keys.PROGRESSION_WOODCUTTING_PKEY;
    }

    @Override
    public ProgressionWoodcutting as(String alias) {
        return new ProgressionWoodcutting(DSL.name(alias), this);
    }

    @Override
    public ProgressionWoodcutting as(Name alias) {
        return new ProgressionWoodcutting(alias, this);
    }

    @Override
    public ProgressionWoodcutting as(Table<?> alias) {
        return new ProgressionWoodcutting(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionWoodcutting rename(String name) {
        return new ProgressionWoodcutting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionWoodcutting rename(Name name) {
        return new ProgressionWoodcutting(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgressionWoodcutting rename(Table<?> name) {
        return new ProgressionWoodcutting(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionWoodcutting where(Condition condition) {
        return new ProgressionWoodcutting(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionWoodcutting where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionWoodcutting where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionWoodcutting where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionWoodcutting where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionWoodcutting where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionWoodcutting where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgressionWoodcutting where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionWoodcutting whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgressionWoodcutting whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
