/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.AchievementCompletionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AchievementCompletions extends TableImpl<AchievementCompletionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.achievement_completions</code>
     */
    public static final AchievementCompletions ACHIEVEMENT_COMPLETIONS = new AchievementCompletions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AchievementCompletionsRecord> getRecordType() {
        return AchievementCompletionsRecord.class;
    }

    /**
     * The column <code>public.achievement_completions.id</code>.
     */
    public final TableField<AchievementCompletionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.achievement_completions.client</code>.
     */
    public final TableField<AchievementCompletionsRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.achievement_completions.period</code>.
     */
    public final TableField<AchievementCompletionsRecord, String> PERIOD = createField(DSL.name("period"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.achievement_completions.namespace</code>.
     */
    public final TableField<AchievementCompletionsRecord, String> NAMESPACE = createField(DSL.name("namespace"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.achievement_completions.keyname</code>.
     */
    public final TableField<AchievementCompletionsRecord, String> KEYNAME = createField(DSL.name("keyname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.achievement_completions.timestamp</code>.
     */
    public final TableField<AchievementCompletionsRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private AchievementCompletions(Name alias, Table<AchievementCompletionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AchievementCompletions(Name alias, Table<AchievementCompletionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.achievement_completions</code> table
     * reference
     */
    public AchievementCompletions(String alias) {
        this(DSL.name(alias), ACHIEVEMENT_COMPLETIONS);
    }

    /**
     * Create an aliased <code>public.achievement_completions</code> table
     * reference
     */
    public AchievementCompletions(Name alias) {
        this(alias, ACHIEVEMENT_COMPLETIONS);
    }

    /**
     * Create a <code>public.achievement_completions</code> table reference
     */
    public AchievementCompletions() {
        this(DSL.name("achievement_completions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ACHIEVEMENT_COMPLETIONS, Indexes.IDX_ACHIEVEMENT_COMPLETIONS_TOTAL);
    }

    @Override
    public UniqueKey<AchievementCompletionsRecord> getPrimaryKey() {
        return Keys.ACHIEVEMENT_COMPLETIONS_PKEY;
    }

    @Override
    public AchievementCompletions as(String alias) {
        return new AchievementCompletions(DSL.name(alias), this);
    }

    @Override
    public AchievementCompletions as(Name alias) {
        return new AchievementCompletions(alias, this);
    }

    @Override
    public AchievementCompletions as(Table<?> alias) {
        return new AchievementCompletions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AchievementCompletions rename(String name) {
        return new AchievementCompletions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AchievementCompletions rename(Name name) {
        return new AchievementCompletions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AchievementCompletions rename(Table<?> name) {
        return new AchievementCompletions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AchievementCompletions where(Condition condition) {
        return new AchievementCompletions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AchievementCompletions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AchievementCompletions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AchievementCompletions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AchievementCompletions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AchievementCompletions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AchievementCompletions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AchievementCompletions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AchievementCompletions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AchievementCompletions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
