/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.ClientNameHistory.ClientNameHistoryPath;
import me.mykindos.betterpvp.core.database.jooq.tables.ClientProperties.ClientPropertiesPath;
import me.mykindos.betterpvp.core.database.jooq.tables.ClientRewards.ClientRewardsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.ClientStats.ClientStatsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.CombatStats.CombatStatsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.FilteredWords.FilteredWordsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.GameData.GameDataPath;
import me.mykindos.betterpvp.core.database.jooq.tables.GameTeams.GameTeamsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.GamerProperties.GamerPropertiesPath;
import me.mykindos.betterpvp.core.database.jooq.tables.Ignores.IgnoresPath;
import me.mykindos.betterpvp.core.database.jooq.tables.KillContributions.KillContributionsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.Kills.KillsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.OfflineMessages.OfflineMessagesPath;
import me.mykindos.betterpvp.core.database.jooq.tables.Punishments.PunishmentsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ClientsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Clients extends TableImpl<ClientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clients</code>
     */
    public static final Clients CLIENTS = new Clients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientsRecord> getRecordType() {
        return ClientsRecord.class;
    }

    /**
     * The column <code>public.clients.id</code>.
     */
    public final TableField<ClientsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.clients.uuid</code>.
     */
    public final TableField<ClientsRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.clients.name</code>.
     */
    public final TableField<ClientsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.clients.rank</code>.
     */
    public final TableField<ClientsRecord, String> RANK = createField(DSL.name("rank"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.field(DSL.raw("'PLAYER'::character varying"), SQLDataType.VARCHAR)), this, "");

    private Clients(Name alias, Table<ClientsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Clients(Name alias, Table<ClientsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clients</code> table reference
     */
    public Clients(String alias) {
        this(DSL.name(alias), CLIENTS);
    }

    /**
     * Create an aliased <code>public.clients</code> table reference
     */
    public Clients(Name alias) {
        this(alias, CLIENTS);
    }

    /**
     * Create a <code>public.clients</code> table reference
     */
    public Clients() {
        this(DSL.name("clients"), null);
    }

    public <O extends Record> Clients(Table<O> path, ForeignKey<O, ClientsRecord> childPath, InverseForeignKey<O, ClientsRecord> parentPath) {
        super(path, childPath, parentPath, CLIENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientsPath extends Clients implements Path<ClientsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientsPath(Table<O> path, ForeignKey<O, ClientsRecord> childPath, InverseForeignKey<O, ClientsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientsPath(Name alias, Table<ClientsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientsPath as(String alias) {
            return new ClientsPath(DSL.name(alias), this);
        }

        @Override
        public ClientsPath as(Name alias) {
            return new ClientsPath(alias, this);
        }

        @Override
        public ClientsPath as(Table<?> alias) {
            return new ClientsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CLIENTS_NAME_INDEX);
    }

    @Override
    public UniqueKey<ClientsRecord> getPrimaryKey() {
        return Keys.CLIENTS_PKEY;
    }

    @Override
    public List<UniqueKey<ClientsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CLIENTS_UUID_KEY);
    }

    private transient ClientNameHistoryPath _clientNameHistory;

    /**
     * Get the implicit to-many join path to the
     * <code>public.client_name_history</code> table
     */
    public ClientNameHistoryPath clientNameHistory() {
        if (_clientNameHistory == null)
            _clientNameHistory = new ClientNameHistoryPath(this, null, Keys.CLIENT_NAME_HISTORY__CLIENT_NAME_HISTORY_CLIENT_FKEY.getInverseKey());

        return _clientNameHistory;
    }

    private transient ClientPropertiesPath _clientProperties;

    /**
     * Get the implicit to-many join path to the
     * <code>public.client_properties</code> table
     */
    public ClientPropertiesPath clientProperties() {
        if (_clientProperties == null)
            _clientProperties = new ClientPropertiesPath(this, null, Keys.CLIENT_PROPERTIES__CLIENT_PROPERTIES_CLIENT_FKEY.getInverseKey());

        return _clientProperties;
    }

    private transient ClientRewardsPath _clientRewards;

    /**
     * Get the implicit to-many join path to the
     * <code>public.client_rewards</code> table
     */
    public ClientRewardsPath clientRewards() {
        if (_clientRewards == null)
            _clientRewards = new ClientRewardsPath(this, null, Keys.CLIENT_REWARDS__CLIENT_REWARDS_CLIENT_FKEY.getInverseKey());

        return _clientRewards;
    }

    private transient ClientStatsPath _clientStats;

    /**
     * Get the implicit to-many join path to the
     * <code>public.client_stats</code> table
     */
    public ClientStatsPath clientStats() {
        if (_clientStats == null)
            _clientStats = new ClientStatsPath(this, null, Keys.CLIENT_STATS__CLIENT_STATS_CLIENT_FKEY.getInverseKey());

        return _clientStats;
    }

    private transient CombatStatsPath _combatStats;

    /**
     * Get the implicit to-many join path to the
     * <code>public.combat_stats</code> table
     */
    public CombatStatsPath combatStats() {
        if (_combatStats == null)
            _combatStats = new CombatStatsPath(this, null, Keys.COMBAT_STATS__COMBAT_STATS_CLIENT_FKEY.getInverseKey());

        return _combatStats;
    }

    private transient FilteredWordsPath _filteredWords;

    /**
     * Get the implicit to-many join path to the
     * <code>public.filtered_words</code> table
     */
    public FilteredWordsPath filteredWords() {
        if (_filteredWords == null)
            _filteredWords = new FilteredWordsPath(this, null, Keys.FILTERED_WORDS__FILTERED_WORDS_CREATED_BY_FKEY.getInverseKey());

        return _filteredWords;
    }

    private transient GameTeamsPath _gameTeams;

    /**
     * Get the implicit to-many join path to the <code>public.game_teams</code>
     * table
     */
    public GameTeamsPath gameTeams() {
        if (_gameTeams == null)
            _gameTeams = new GameTeamsPath(this, null, Keys.GAME_TEAMS__GAME_TEAMS_CLIENT_FKEY.getInverseKey());

        return _gameTeams;
    }

    private transient GamerPropertiesPath _gamerProperties;

    /**
     * Get the implicit to-many join path to the
     * <code>public.gamer_properties</code> table
     */
    public GamerPropertiesPath gamerProperties() {
        if (_gamerProperties == null)
            _gamerProperties = new GamerPropertiesPath(this, null, Keys.GAMER_PROPERTIES__GAMER_PROPERTIES_CLIENT_FKEY.getInverseKey());

        return _gamerProperties;
    }

    private transient IgnoresPath _ignoresClientFkey;

    /**
     * Get the implicit to-many join path to the <code>public.ignores</code>
     * table, via the <code>ignores_client_fkey</code> key
     */
    public IgnoresPath ignoresClientFkey() {
        if (_ignoresClientFkey == null)
            _ignoresClientFkey = new IgnoresPath(this, null, Keys.IGNORES__IGNORES_CLIENT_FKEY.getInverseKey());

        return _ignoresClientFkey;
    }

    private transient IgnoresPath _ignoresIgnoredFkey;

    /**
     * Get the implicit to-many join path to the <code>public.ignores</code>
     * table, via the <code>ignores_ignored_fkey</code> key
     */
    public IgnoresPath ignoresIgnoredFkey() {
        if (_ignoresIgnoredFkey == null)
            _ignoresIgnoredFkey = new IgnoresPath(this, null, Keys.IGNORES__IGNORES_IGNORED_FKEY.getInverseKey());

        return _ignoresIgnoredFkey;
    }

    private transient KillContributionsPath _killContributions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.kill_contributions</code> table
     */
    public KillContributionsPath killContributions() {
        if (_killContributions == null)
            _killContributions = new KillContributionsPath(this, null, Keys.KILL_CONTRIBUTIONS__KILL_CONTRIBUTIONS_CONTRIBUTOR_FKEY.getInverseKey());

        return _killContributions;
    }

    private transient OfflineMessagesPath _offlineMessages;

    /**
     * Get the implicit to-many join path to the
     * <code>public.offline_messages</code> table
     */
    public OfflineMessagesPath offlineMessages() {
        if (_offlineMessages == null)
            _offlineMessages = new OfflineMessagesPath(this, null, Keys.OFFLINE_MESSAGES__OFFLINE_MESSAGES_CLIENT_FKEY.getInverseKey());

        return _offlineMessages;
    }

    private transient PunishmentsPath _punishments;

    /**
     * Get the implicit to-many join path to the <code>public.punishments</code>
     * table
     */
    public PunishmentsPath punishments() {
        if (_punishments == null)
            _punishments = new PunishmentsPath(this, null, Keys.PUNISHMENTS__PUNISHMENTS_CLIENT_FKEY.getInverseKey());

        return _punishments;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.game_data</code> table
     */
    public GameDataPath gameData() {
        return gameTeams().gameData();
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.kills</code>
     * table
     */
    public KillsPath kills() {
        return killContributions().kills();
    }

    @Override
    public Clients as(String alias) {
        return new Clients(DSL.name(alias), this);
    }

    @Override
    public Clients as(Name alias) {
        return new Clients(alias, this);
    }

    @Override
    public Clients as(Table<?> alias) {
        return new Clients(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Clients rename(String name) {
        return new Clients(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clients rename(Name name) {
        return new Clients(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clients rename(Table<?> name) {
        return new Clients(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Condition condition) {
        return new Clients(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
