/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ClientRewardsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRewards extends TableImpl<ClientRewardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client_rewards</code>
     */
    public static final ClientRewards CLIENT_REWARDS = new ClientRewards();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientRewardsRecord> getRecordType() {
        return ClientRewardsRecord.class;
    }

    /**
     * The column <code>public.client_rewards.client</code>.
     */
    public final TableField<ClientRewardsRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.client_rewards.season</code>.
     */
    public final TableField<ClientRewardsRecord, Integer> SEASON = createField(DSL.name("season"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.client_rewards.rewards</code>.
     */
    public final TableField<ClientRewardsRecord, String> REWARDS = createField(DSL.name("rewards"), SQLDataType.CLOB.nullable(false), this, "");

    private ClientRewards(Name alias, Table<ClientRewardsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClientRewards(Name alias, Table<ClientRewardsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client_rewards</code> table reference
     */
    public ClientRewards(String alias) {
        this(DSL.name(alias), CLIENT_REWARDS);
    }

    /**
     * Create an aliased <code>public.client_rewards</code> table reference
     */
    public ClientRewards(Name alias) {
        this(alias, CLIENT_REWARDS);
    }

    /**
     * Create a <code>public.client_rewards</code> table reference
     */
    public ClientRewards() {
        this(DSL.name("client_rewards"), null);
    }

    public <O extends Record> ClientRewards(Table<O> path, ForeignKey<O, ClientRewardsRecord> childPath, InverseForeignKey<O, ClientRewardsRecord> parentPath) {
        super(path, childPath, parentPath, CLIENT_REWARDS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientRewardsPath extends ClientRewards implements Path<ClientRewardsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientRewardsPath(Table<O> path, ForeignKey<O, ClientRewardsRecord> childPath, InverseForeignKey<O, ClientRewardsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientRewardsPath(Name alias, Table<ClientRewardsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientRewardsPath as(String alias) {
            return new ClientRewardsPath(DSL.name(alias), this);
        }

        @Override
        public ClientRewardsPath as(Name alias) {
            return new ClientRewardsPath(alias, this);
        }

        @Override
        public ClientRewardsPath as(Table<?> alias) {
            return new ClientRewardsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ClientRewardsRecord> getPrimaryKey() {
        return Keys.CLIENT_REWARDS_PKEY;
    }

    @Override
    public List<ForeignKey<ClientRewardsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENT_REWARDS__CLIENT_REWARDS_CLIENT_FKEY);
    }

    private transient ClientsPath _clients;

    /**
     * Get the implicit join path to the <code>public.clients</code> table.
     */
    public ClientsPath clients() {
        if (_clients == null)
            _clients = new ClientsPath(this, Keys.CLIENT_REWARDS__CLIENT_REWARDS_CLIENT_FKEY, null);

        return _clients;
    }

    @Override
    public ClientRewards as(String alias) {
        return new ClientRewards(DSL.name(alias), this);
    }

    @Override
    public ClientRewards as(Name alias) {
        return new ClientRewards(alias, this);
    }

    @Override
    public ClientRewards as(Table<?> alias) {
        return new ClientRewards(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRewards rename(String name) {
        return new ClientRewards(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRewards rename(Name name) {
        return new ClientRewards(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRewards rename(Table<?> name) {
        return new ClientRewards(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Condition condition) {
        return new ClientRewards(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRewards where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRewards whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
