/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ClientStatsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientStats extends TableImpl<ClientStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client_stats</code>
     */
    public static final ClientStats CLIENT_STATS = new ClientStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientStatsRecord> getRecordType() {
        return ClientStatsRecord.class;
    }

    /**
     * The column <code>public.client_stats.client</code>.
     */
    public final TableField<ClientStatsRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.client_stats.period</code>.
     */
    public final TableField<ClientStatsRecord, String> PERIOD = createField(DSL.name("period"), SQLDataType.VARCHAR(127).nullable(false), this, "");

    /**
     * The column <code>public.client_stats.stattype</code>.
     */
    public final TableField<ClientStatsRecord, String> STATTYPE = createField(DSL.name("stattype"), SQLDataType.VARCHAR(127).nullable(false), this, "");

    /**
     * The column <code>public.client_stats.statdata</code>.
     */
    public final TableField<ClientStatsRecord, JSONB> STATDATA = createField(DSL.name("statdata"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.client_stats.stat</code>.
     */
    public final TableField<ClientStatsRecord, Long> STAT = createField(DSL.name("stat"), SQLDataType.BIGINT.nullable(false), this, "");

    private ClientStats(Name alias, Table<ClientStatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClientStats(Name alias, Table<ClientStatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client_stats</code> table reference
     */
    public ClientStats(String alias) {
        this(DSL.name(alias), CLIENT_STATS);
    }

    /**
     * Create an aliased <code>public.client_stats</code> table reference
     */
    public ClientStats(Name alias) {
        this(alias, CLIENT_STATS);
    }

    /**
     * Create a <code>public.client_stats</code> table reference
     */
    public ClientStats() {
        this(DSL.name("client_stats"), null);
    }

    public <O extends Record> ClientStats(Table<O> path, ForeignKey<O, ClientStatsRecord> childPath, InverseForeignKey<O, ClientStatsRecord> parentPath) {
        super(path, childPath, parentPath, CLIENT_STATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientStatsPath extends ClientStats implements Path<ClientStatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientStatsPath(Table<O> path, ForeignKey<O, ClientStatsRecord> childPath, InverseForeignKey<O, ClientStatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientStatsPath(Name alias, Table<ClientStatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientStatsPath as(String alias) {
            return new ClientStatsPath(DSL.name(alias), this);
        }

        @Override
        public ClientStatsPath as(Name alias) {
            return new ClientStatsPath(alias, this);
        }

        @Override
        public ClientStatsPath as(Table<?> alias) {
            return new ClientStatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_STAT_CLIENT);
    }

    @Override
    public UniqueKey<ClientStatsRecord> getPrimaryKey() {
        return Keys.PK_CLIENT;
    }

    @Override
    public List<ForeignKey<ClientStatsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENT_STATS__CLIENT_STATS_CLIENT_FKEY, Keys.CLIENT_STATS__FK_CLIENT);
    }

    private transient ClientsPath _clientStatsClientFkey;

    /**
     * Get the implicit join path to the <code>public.clients</code> table, via
     * the <code>client_stats_client_fkey</code> key.
     */
    public ClientsPath clientStatsClientFkey() {
        if (_clientStatsClientFkey == null)
            _clientStatsClientFkey = new ClientsPath(this, Keys.CLIENT_STATS__CLIENT_STATS_CLIENT_FKEY, null);

        return _clientStatsClientFkey;
    }

    private transient ClientsPath _fkClient;

    /**
     * Get the implicit join path to the <code>public.clients</code> table, via
     * the <code>fk_client</code> key.
     */
    public ClientsPath fkClient() {
        if (_fkClient == null)
            _fkClient = new ClientsPath(this, Keys.CLIENT_STATS__FK_CLIENT, null);

        return _fkClient;
    }

    @Override
    public ClientStats as(String alias) {
        return new ClientStats(DSL.name(alias), this);
    }

    @Override
    public ClientStats as(Name alias) {
        return new ClientStats(alias, this);
    }

    @Override
    public ClientStats as(Table<?> alias) {
        return new ClientStats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientStats rename(String name) {
        return new ClientStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientStats rename(Name name) {
        return new ClientStats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientStats rename(Table<?> name) {
        return new ClientStats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientStats where(Condition condition) {
        return new ClientStats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientStats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientStats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientStats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientStats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientStats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientStats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientStats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientStats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientStats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
