/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.FilteredWordsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilteredWords extends TableImpl<FilteredWordsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.filtered_words</code>
     */
    public static final FilteredWords FILTERED_WORDS = new FilteredWords();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FilteredWordsRecord> getRecordType() {
        return FilteredWordsRecord.class;
    }

    /**
     * The column <code>public.filtered_words.id</code>.
     */
    public final TableField<FilteredWordsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.filtered_words.word</code>.
     */
    public final TableField<FilteredWordsRecord, String> WORD = createField(DSL.name("word"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.filtered_words.created_at</code>.
     */
    public final TableField<FilteredWordsRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.filtered_words.created_by</code>.
     */
    public final TableField<FilteredWordsRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    private FilteredWords(Name alias, Table<FilteredWordsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FilteredWords(Name alias, Table<FilteredWordsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.filtered_words</code> table reference
     */
    public FilteredWords(String alias) {
        this(DSL.name(alias), FILTERED_WORDS);
    }

    /**
     * Create an aliased <code>public.filtered_words</code> table reference
     */
    public FilteredWords(Name alias) {
        this(alias, FILTERED_WORDS);
    }

    /**
     * Create a <code>public.filtered_words</code> table reference
     */
    public FilteredWords() {
        this(DSL.name("filtered_words"), null);
    }

    public <O extends Record> FilteredWords(Table<O> path, ForeignKey<O, FilteredWordsRecord> childPath, InverseForeignKey<O, FilteredWordsRecord> parentPath) {
        super(path, childPath, parentPath, FILTERED_WORDS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FilteredWordsPath extends FilteredWords implements Path<FilteredWordsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FilteredWordsPath(Table<O> path, ForeignKey<O, FilteredWordsRecord> childPath, InverseForeignKey<O, FilteredWordsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FilteredWordsPath(Name alias, Table<FilteredWordsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FilteredWordsPath as(String alias) {
            return new FilteredWordsPath(DSL.name(alias), this);
        }

        @Override
        public FilteredWordsPath as(Name alias) {
            return new FilteredWordsPath(alias, this);
        }

        @Override
        public FilteredWordsPath as(Table<?> alias) {
            return new FilteredWordsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FilteredWordsRecord, Integer> getIdentity() {
        return (Identity<FilteredWordsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FilteredWordsRecord> getPrimaryKey() {
        return Keys.FILTERED_WORDS_PKEY;
    }

    @Override
    public List<UniqueKey<FilteredWordsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FILTERED_WORDS_WORD_KEY);
    }

    @Override
    public List<ForeignKey<FilteredWordsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FILTERED_WORDS__FILTERED_WORDS_CREATED_BY_FKEY);
    }

    private transient ClientsPath _clients;

    /**
     * Get the implicit join path to the <code>public.clients</code> table.
     */
    public ClientsPath clients() {
        if (_clients == null)
            _clients = new ClientsPath(this, Keys.FILTERED_WORDS__FILTERED_WORDS_CREATED_BY_FKEY, null);

        return _clients;
    }

    @Override
    public FilteredWords as(String alias) {
        return new FilteredWords(DSL.name(alias), this);
    }

    @Override
    public FilteredWords as(Name alias) {
        return new FilteredWords(alias, this);
    }

    @Override
    public FilteredWords as(Table<?> alias) {
        return new FilteredWords(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FilteredWords rename(String name) {
        return new FilteredWords(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FilteredWords rename(Name name) {
        return new FilteredWords(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FilteredWords rename(Table<?> name) {
        return new FilteredWords(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilteredWords where(Condition condition) {
        return new FilteredWords(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilteredWords where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilteredWords where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilteredWords where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilteredWords where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilteredWords where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilteredWords where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FilteredWords where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilteredWords whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FilteredWords whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
