/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.GameTeams.GameTeamsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GameDataRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameData extends TableImpl<GameDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game_data</code>
     */
    public static final GameData GAME_DATA = new GameData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameDataRecord> getRecordType() {
        return GameDataRecord.class;
    }

    /**
     * The column <code>public.game_data.id</code>.
     */
    public final TableField<GameDataRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.game_data.game</code>.
     */
    public final TableField<GameDataRecord, String> GAME = createField(DSL.name("game"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.game_data.map</code>.
     */
    public final TableField<GameDataRecord, String> MAP = createField(DSL.name("map"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private GameData(Name alias, Table<GameDataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GameData(Name alias, Table<GameDataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game_data</code> table reference
     */
    public GameData(String alias) {
        this(DSL.name(alias), GAME_DATA);
    }

    /**
     * Create an aliased <code>public.game_data</code> table reference
     */
    public GameData(Name alias) {
        this(alias, GAME_DATA);
    }

    /**
     * Create a <code>public.game_data</code> table reference
     */
    public GameData() {
        this(DSL.name("game_data"), null);
    }

    public <O extends Record> GameData(Table<O> path, ForeignKey<O, GameDataRecord> childPath, InverseForeignKey<O, GameDataRecord> parentPath) {
        super(path, childPath, parentPath, GAME_DATA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GameDataPath extends GameData implements Path<GameDataRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GameDataPath(Table<O> path, ForeignKey<O, GameDataRecord> childPath, InverseForeignKey<O, GameDataRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GameDataPath(Name alias, Table<GameDataRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GameDataPath as(String alias) {
            return new GameDataPath(DSL.name(alias), this);
        }

        @Override
        public GameDataPath as(Name alias) {
            return new GameDataPath(alias, this);
        }

        @Override
        public GameDataPath as(Table<?> alias) {
            return new GameDataPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GameDataRecord> getPrimaryKey() {
        return Keys.GAME_DATA_PKEY;
    }

    private transient GameTeamsPath _gameTeams;

    /**
     * Get the implicit to-many join path to the <code>public.game_teams</code>
     * table
     */
    public GameTeamsPath gameTeams() {
        if (_gameTeams == null)
            _gameTeams = new GameTeamsPath(this, null, Keys.GAME_TEAMS__GAME_TEAMS_ID_FKEY.getInverseKey());

        return _gameTeams;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.clients</code> table
     */
    public ClientsPath clients() {
        return gameTeams().clients();
    }

    @Override
    public GameData as(String alias) {
        return new GameData(DSL.name(alias), this);
    }

    @Override
    public GameData as(Name alias) {
        return new GameData(alias, this);
    }

    @Override
    public GameData as(Table<?> alias) {
        return new GameData(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameData rename(String name) {
        return new GameData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameData rename(Name name) {
        return new GameData(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameData rename(Table<?> name) {
        return new GameData(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameData where(Condition condition) {
        return new GameData(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameData where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameData where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameData where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameData where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameData where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameData where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameData where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameData whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameData whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
