/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GamerPropertiesRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GamerProperties extends TableImpl<GamerPropertiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.gamer_properties</code>
     */
    public static final GamerProperties GAMER_PROPERTIES = new GamerProperties();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GamerPropertiesRecord> getRecordType() {
        return GamerPropertiesRecord.class;
    }

    /**
     * The column <code>public.gamer_properties.client</code>.
     */
    public final TableField<GamerPropertiesRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.gamer_properties.realm</code>.
     */
    public final TableField<GamerPropertiesRecord, Integer> REALM = createField(DSL.name("realm"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.gamer_properties.property</code>.
     */
    public final TableField<GamerPropertiesRecord, String> PROPERTY = createField(DSL.name("property"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.gamer_properties.value</code>.
     */
    public final TableField<GamerPropertiesRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255), this, "");

    private GamerProperties(Name alias, Table<GamerPropertiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GamerProperties(Name alias, Table<GamerPropertiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.gamer_properties</code> table reference
     */
    public GamerProperties(String alias) {
        this(DSL.name(alias), GAMER_PROPERTIES);
    }

    /**
     * Create an aliased <code>public.gamer_properties</code> table reference
     */
    public GamerProperties(Name alias) {
        this(alias, GAMER_PROPERTIES);
    }

    /**
     * Create a <code>public.gamer_properties</code> table reference
     */
    public GamerProperties() {
        this(DSL.name("gamer_properties"), null);
    }

    public <O extends Record> GamerProperties(Table<O> path, ForeignKey<O, GamerPropertiesRecord> childPath, InverseForeignKey<O, GamerPropertiesRecord> parentPath) {
        super(path, childPath, parentPath, GAMER_PROPERTIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GamerPropertiesPath extends GamerProperties implements Path<GamerPropertiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GamerPropertiesPath(Table<O> path, ForeignKey<O, GamerPropertiesRecord> childPath, InverseForeignKey<O, GamerPropertiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GamerPropertiesPath(Name alias, Table<GamerPropertiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GamerPropertiesPath as(String alias) {
            return new GamerPropertiesPath(DSL.name(alias), this);
        }

        @Override
        public GamerPropertiesPath as(Name alias) {
            return new GamerPropertiesPath(alias, this);
        }

        @Override
        public GamerPropertiesPath as(Table<?> alias) {
            return new GamerPropertiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GamerPropertiesRecord> getPrimaryKey() {
        return Keys.GAMER_PROPERTIES_PKEY;
    }

    @Override
    public List<ForeignKey<GamerPropertiesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GAMER_PROPERTIES__GAMER_PROPERTIES_CLIENT_FKEY);
    }

    private transient ClientsPath _clients;

    /**
     * Get the implicit join path to the <code>public.clients</code> table.
     */
    public ClientsPath clients() {
        if (_clients == null)
            _clients = new ClientsPath(this, Keys.GAMER_PROPERTIES__GAMER_PROPERTIES_CLIENT_FKEY, null);

        return _clients;
    }

    @Override
    public GamerProperties as(String alias) {
        return new GamerProperties(DSL.name(alias), this);
    }

    @Override
    public GamerProperties as(Name alias) {
        return new GamerProperties(alias, this);
    }

    @Override
    public GamerProperties as(Table<?> alias) {
        return new GamerProperties(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GamerProperties rename(String name) {
        return new GamerProperties(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GamerProperties rename(Name name) {
        return new GamerProperties(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GamerProperties rename(Table<?> name) {
        return new GamerProperties(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GamerProperties where(Condition condition) {
        return new GamerProperties(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GamerProperties where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GamerProperties where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GamerProperties where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GamerProperties where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GamerProperties where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GamerProperties where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GamerProperties where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GamerProperties whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GamerProperties whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
