/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetCombatDataRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetCombatData extends TableImpl<GetCombatDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_combat_data</code>
     */
    public static final GetCombatData GET_COMBAT_DATA = new GetCombatData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetCombatDataRecord> getRecordType() {
        return GetCombatDataRecord.class;
    }

    /**
     * The column <code>public.get_combat_data.kills</code>.
     */
    public final TableField<GetCombatDataRecord, Integer> KILLS = createField(DSL.name("kills"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_combat_data.deaths</code>.
     */
    public final TableField<GetCombatDataRecord, Integer> DEATHS = createField(DSL.name("deaths"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_combat_data.assists</code>.
     */
    public final TableField<GetCombatDataRecord, Integer> ASSISTS = createField(DSL.name("assists"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_combat_data.rating</code>.
     */
    public final TableField<GetCombatDataRecord, Integer> RATING = createField(DSL.name("rating"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_combat_data.killstreak</code>.
     */
    public final TableField<GetCombatDataRecord, Integer> KILLSTREAK = createField(DSL.name("killstreak"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_combat_data.highest_killstreak</code>.
     */
    public final TableField<GetCombatDataRecord, Integer> HIGHEST_KILLSTREAK = createField(DSL.name("highest_killstreak"), SQLDataType.INTEGER, this, "");

    private GetCombatData(Name alias, Table<GetCombatDataRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.VARCHAR),
            DSL.val(null, SQLDataType.INTEGER)
        });
    }

    private GetCombatData(Name alias, Table<GetCombatDataRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetCombatData(Name alias, Table<GetCombatDataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_combat_data</code> table reference
     */
    public GetCombatData(String alias) {
        this(DSL.name(alias), GET_COMBAT_DATA);
    }

    /**
     * Create an aliased <code>public.get_combat_data</code> table reference
     */
    public GetCombatData(Name alias) {
        this(alias, GET_COMBAT_DATA);
    }

    /**
     * Create a <code>public.get_combat_data</code> table reference
     */
    public GetCombatData() {
        this(DSL.name("get_combat_data"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetCombatData as(String alias) {
        return new GetCombatData(DSL.name(alias), this, parameters);
    }

    @Override
    public GetCombatData as(Name alias) {
        return new GetCombatData(alias, this, parameters);
    }

    @Override
    public GetCombatData as(Table<?> alias) {
        return new GetCombatData(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetCombatData rename(String name) {
        return new GetCombatData(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetCombatData rename(Name name) {
        return new GetCombatData(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetCombatData rename(Table<?> name) {
        return new GetCombatData(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetCombatData call(
          String clientUuid
        , Integer realmParam
    ) {
        GetCombatData result = new GetCombatData(DSL.name("get_combat_data"), null, new Field[] {
            DSL.val(clientUuid, SQLDataType.VARCHAR),
            DSL.val(realmParam, SQLDataType.INTEGER)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetCombatData call(
          Field<String> clientUuid
        , Field<Integer> realmParam
    ) {
        GetCombatData result = new GetCombatData(DSL.name("get_combat_data"), null, new Field[] {
            clientUuid,
            realmParam
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
