/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetClientAchievementRanksRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetClientAchievementRanks extends TableImpl<GetClientAchievementRanksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.get_client_achievement_ranks</code>
     */
    public static final GetClientAchievementRanks GET_CLIENT_ACHIEVEMENT_RANKS = new GetClientAchievementRanks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetClientAchievementRanksRecord> getRecordType() {
        return GetClientAchievementRanksRecord.class;
    }

    /**
     * The column <code>public.get_client_achievement_ranks.namespace</code>.
     */
    public final TableField<GetClientAchievementRanksRecord, String> NAMESPACE = createField(DSL.name("namespace"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_client_achievement_ranks.keyname</code>.
     */
    public final TableField<GetClientAchievementRanksRecord, String> KEYNAME = createField(DSL.name("keyname"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_client_achievement_ranks.rank</code>.
     */
    public final TableField<GetClientAchievementRanksRecord, Long> RANK = createField(DSL.name("rank"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.get_client_achievement_ranks.season</code>.
     */
    public final TableField<GetClientAchievementRanksRecord, Integer> SEASON = createField(DSL.name("season"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_client_achievement_ranks.realm</code>.
     */
    public final TableField<GetClientAchievementRanksRecord, Integer> REALM = createField(DSL.name("realm"), SQLDataType.INTEGER, this, "");

    private GetClientAchievementRanks(Name alias, Table<GetClientAchievementRanksRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.BIGINT)
        });
    }

    private GetClientAchievementRanks(Name alias, Table<GetClientAchievementRanksRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetClientAchievementRanks(Name alias, Table<GetClientAchievementRanksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_client_achievement_ranks</code> table
     * reference
     */
    public GetClientAchievementRanks(String alias) {
        this(DSL.name(alias), GET_CLIENT_ACHIEVEMENT_RANKS);
    }

    /**
     * Create an aliased <code>public.get_client_achievement_ranks</code> table
     * reference
     */
    public GetClientAchievementRanks(Name alias) {
        this(alias, GET_CLIENT_ACHIEVEMENT_RANKS);
    }

    /**
     * Create a <code>public.get_client_achievement_ranks</code> table reference
     */
    public GetClientAchievementRanks() {
        this(DSL.name("get_client_achievement_ranks"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetClientAchievementRanks as(String alias) {
        return new GetClientAchievementRanks(DSL.name(alias), this, parameters);
    }

    @Override
    public GetClientAchievementRanks as(Name alias) {
        return new GetClientAchievementRanks(alias, this, parameters);
    }

    @Override
    public GetClientAchievementRanks as(Table<?> alias) {
        return new GetClientAchievementRanks(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientAchievementRanks rename(String name) {
        return new GetClientAchievementRanks(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientAchievementRanks rename(Name name) {
        return new GetClientAchievementRanks(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetClientAchievementRanks rename(Table<?> name) {
        return new GetClientAchievementRanks(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetClientAchievementRanks call(
          Long clientParam
    ) {
        GetClientAchievementRanks result = new GetClientAchievementRanks(DSL.name("get_client_achievement_ranks"), null, new Field[] {
            DSL.val(clientParam, SQLDataType.BIGINT)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetClientAchievementRanks call(
          Field<Long> clientParam
    ) {
        GetClientAchievementRanks result = new GetClientAchievementRanks(DSL.name("get_client_achievement_ranks"), null, new Field[] {
            clientParam
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
