/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetOfflineMessagesByTimeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetOfflineMessagesByTime extends TableImpl<GetOfflineMessagesByTimeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.get_offline_messages_by_time</code>
     */
    public static final GetOfflineMessagesByTime GET_OFFLINE_MESSAGES_BY_TIME = new GetOfflineMessagesByTime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetOfflineMessagesByTimeRecord> getRecordType() {
        return GetOfflineMessagesByTimeRecord.class;
    }

    /**
     * The column <code>public.get_offline_messages_by_time.client_uuid</code>.
     */
    public final TableField<GetOfflineMessagesByTimeRecord, String> CLIENT_UUID = createField(DSL.name("client_uuid"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_offline_messages_by_time.time_sent</code>.
     */
    public final TableField<GetOfflineMessagesByTimeRecord, Long> TIME_SENT = createField(DSL.name("time_sent"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.get_offline_messages_by_time.action</code>.
     */
    public final TableField<GetOfflineMessagesByTimeRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_offline_messages_by_time.message</code>.
     */
    public final TableField<GetOfflineMessagesByTimeRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB, this, "");

    private GetOfflineMessagesByTime(Name alias, Table<GetOfflineMessagesByTimeRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.BIGINT),
            DSL.val(null, SQLDataType.BIGINT)
        });
    }

    private GetOfflineMessagesByTime(Name alias, Table<GetOfflineMessagesByTimeRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetOfflineMessagesByTime(Name alias, Table<GetOfflineMessagesByTimeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_offline_messages_by_time</code> table
     * reference
     */
    public GetOfflineMessagesByTime(String alias) {
        this(DSL.name(alias), GET_OFFLINE_MESSAGES_BY_TIME);
    }

    /**
     * Create an aliased <code>public.get_offline_messages_by_time</code> table
     * reference
     */
    public GetOfflineMessagesByTime(Name alias) {
        this(alias, GET_OFFLINE_MESSAGES_BY_TIME);
    }

    /**
     * Create a <code>public.get_offline_messages_by_time</code> table reference
     */
    public GetOfflineMessagesByTime() {
        this(DSL.name("get_offline_messages_by_time"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetOfflineMessagesByTime as(String alias) {
        return new GetOfflineMessagesByTime(DSL.name(alias), this, parameters);
    }

    @Override
    public GetOfflineMessagesByTime as(Name alias) {
        return new GetOfflineMessagesByTime(alias, this, parameters);
    }

    @Override
    public GetOfflineMessagesByTime as(Table<?> alias) {
        return new GetOfflineMessagesByTime(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetOfflineMessagesByTime rename(String name) {
        return new GetOfflineMessagesByTime(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetOfflineMessagesByTime rename(Name name) {
        return new GetOfflineMessagesByTime(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetOfflineMessagesByTime rename(Table<?> name) {
        return new GetOfflineMessagesByTime(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetOfflineMessagesByTime call(
          Long clientParam
        , Long timeParam
    ) {
        GetOfflineMessagesByTime result = new GetOfflineMessagesByTime(DSL.name("get_offline_messages_by_time"), null, new Field[] {
            DSL.val(clientParam, SQLDataType.BIGINT),
            DSL.val(timeParam, SQLDataType.BIGINT)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetOfflineMessagesByTime call(
          Field<Long> clientParam
        , Field<Long> timeParam
    ) {
        GetOfflineMessagesByTime result = new GetOfflineMessagesByTime(DSL.name("get_offline_messages_by_time"), null, new Field[] {
            clientParam,
            timeParam
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
