/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTotalAchievementCompletionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTotalAchievementCompletions extends TableImpl<GetTotalAchievementCompletionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.get_total_achievement_completions</code>
     */
    public static final GetTotalAchievementCompletions GET_TOTAL_ACHIEVEMENT_COMPLETIONS = new GetTotalAchievementCompletions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetTotalAchievementCompletionsRecord> getRecordType() {
        return GetTotalAchievementCompletionsRecord.class;
    }

    /**
     * The column
     * <code>public.get_total_achievement_completions.namespace</code>.
     */
    public final TableField<GetTotalAchievementCompletionsRecord, String> NAMESPACE = createField(DSL.name("namespace"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_total_achievement_completions.keyname</code>.
     */
    public final TableField<GetTotalAchievementCompletionsRecord, String> KEYNAME = createField(DSL.name("keyname"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_total_achievement_completions.total</code>.
     */
    public final TableField<GetTotalAchievementCompletionsRecord, Long> TOTAL = createField(DSL.name("total"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.get_total_achievement_completions.season</code>.
     */
    public final TableField<GetTotalAchievementCompletionsRecord, Integer> SEASON = createField(DSL.name("season"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_total_achievement_completions.realm</code>.
     */
    public final TableField<GetTotalAchievementCompletionsRecord, Integer> REALM = createField(DSL.name("realm"), SQLDataType.INTEGER, this, "");

    private GetTotalAchievementCompletions(Name alias, Table<GetTotalAchievementCompletionsRecord> aliased) {
        this(alias, aliased, new Field[] {
        });
    }

    private GetTotalAchievementCompletions(Name alias, Table<GetTotalAchievementCompletionsRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetTotalAchievementCompletions(Name alias, Table<GetTotalAchievementCompletionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_total_achievement_completions</code>
     * table reference
     */
    public GetTotalAchievementCompletions(String alias) {
        this(DSL.name(alias), GET_TOTAL_ACHIEVEMENT_COMPLETIONS);
    }

    /**
     * Create an aliased <code>public.get_total_achievement_completions</code>
     * table reference
     */
    public GetTotalAchievementCompletions(Name alias) {
        this(alias, GET_TOTAL_ACHIEVEMENT_COMPLETIONS);
    }

    /**
     * Create a <code>public.get_total_achievement_completions</code> table
     * reference
     */
    public GetTotalAchievementCompletions() {
        this(DSL.name("get_total_achievement_completions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetTotalAchievementCompletions as(String alias) {
        return new GetTotalAchievementCompletions(DSL.name(alias), this, parameters);
    }

    @Override
    public GetTotalAchievementCompletions as(Name alias) {
        return new GetTotalAchievementCompletions(alias, this, parameters);
    }

    @Override
    public GetTotalAchievementCompletions as(Table<?> alias) {
        return new GetTotalAchievementCompletions(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTotalAchievementCompletions rename(String name) {
        return new GetTotalAchievementCompletions(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTotalAchievementCompletions rename(Name name) {
        return new GetTotalAchievementCompletions(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTotalAchievementCompletions rename(Table<?> name) {
        return new GetTotalAchievementCompletions(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetTotalAchievementCompletions call() {
        GetTotalAchievementCompletions result = new GetTotalAchievementCompletions(DSL.name("get_total_achievement_completions"), null, new Field[] {});

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
