/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import java.math.BigDecimal;

import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopKdrRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopKdr extends TableImpl<GetTopKdrRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_top_kdr</code>
     */
    public static final GetTopKdr GET_TOP_KDR = new GetTopKdr();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetTopKdrRecord> getRecordType() {
        return GetTopKdrRecord.class;
    }

    /**
     * The column <code>public.get_top_kdr.client</code>.
     */
    public final TableField<GetTopKdrRecord, String> CLIENT = createField(DSL.name("client"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_top_kdr.kdr</code>.
     */
    public final TableField<GetTopKdrRecord, BigDecimal> KDR = createField(DSL.name("kdr"), SQLDataType.NUMERIC, this, "");

    private GetTopKdr(Name alias, Table<GetTopKdrRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.INTEGER)
        });
    }

    private GetTopKdr(Name alias, Table<GetTopKdrRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetTopKdr(Name alias, Table<GetTopKdrRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_top_kdr</code> table reference
     */
    public GetTopKdr(String alias) {
        this(DSL.name(alias), GET_TOP_KDR);
    }

    /**
     * Create an aliased <code>public.get_top_kdr</code> table reference
     */
    public GetTopKdr(Name alias) {
        this(alias, GET_TOP_KDR);
    }

    /**
     * Create a <code>public.get_top_kdr</code> table reference
     */
    public GetTopKdr() {
        this(DSL.name("get_top_kdr"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetTopKdr as(String alias) {
        return new GetTopKdr(DSL.name(alias), this, parameters);
    }

    @Override
    public GetTopKdr as(Name alias) {
        return new GetTopKdr(alias, this, parameters);
    }

    @Override
    public GetTopKdr as(Table<?> alias) {
        return new GetTopKdr(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopKdr rename(String name) {
        return new GetTopKdr(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopKdr rename(Name name) {
        return new GetTopKdr(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopKdr rename(Table<?> name) {
        return new GetTopKdr(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetTopKdr call(
          Integer realmParam
        , Integer top
    ) {
        GetTopKdr result = new GetTopKdr(DSL.name("get_top_kdr"), null, new Field[] {
            DSL.val(realmParam, SQLDataType.INTEGER),
            DSL.val(top, SQLDataType.INTEGER)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetTopKdr call(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        GetTopKdr result = new GetTopKdr(DSL.name("get_top_kdr"), null, new Field[] {
            realmParam,
            top
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
