/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopHighestKillstreakRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopHighestKillstreak extends TableImpl<GetTopHighestKillstreakRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_top_highest_killstreak</code>
     */
    public static final GetTopHighestKillstreak GET_TOP_HIGHEST_KILLSTREAK = new GetTopHighestKillstreak();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetTopHighestKillstreakRecord> getRecordType() {
        return GetTopHighestKillstreakRecord.class;
    }

    /**
     * The column <code>public.get_top_highest_killstreak.client</code>.
     */
    public final TableField<GetTopHighestKillstreakRecord, String> CLIENT = createField(DSL.name("client"), SQLDataType.VARCHAR, this, "");

    /**
     * The column
     * <code>public.get_top_highest_killstreak.highest_killstreak</code>.
     */
    public final TableField<GetTopHighestKillstreakRecord, Integer> HIGHEST_KILLSTREAK = createField(DSL.name("highest_killstreak"), SQLDataType.INTEGER, this, "");

    private GetTopHighestKillstreak(Name alias, Table<GetTopHighestKillstreakRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.INTEGER)
        });
    }

    private GetTopHighestKillstreak(Name alias, Table<GetTopHighestKillstreakRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetTopHighestKillstreak(Name alias, Table<GetTopHighestKillstreakRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_top_highest_killstreak</code> table
     * reference
     */
    public GetTopHighestKillstreak(String alias) {
        this(DSL.name(alias), GET_TOP_HIGHEST_KILLSTREAK);
    }

    /**
     * Create an aliased <code>public.get_top_highest_killstreak</code> table
     * reference
     */
    public GetTopHighestKillstreak(Name alias) {
        this(alias, GET_TOP_HIGHEST_KILLSTREAK);
    }

    /**
     * Create a <code>public.get_top_highest_killstreak</code> table reference
     */
    public GetTopHighestKillstreak() {
        this(DSL.name("get_top_highest_killstreak"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetTopHighestKillstreak as(String alias) {
        return new GetTopHighestKillstreak(DSL.name(alias), this, parameters);
    }

    @Override
    public GetTopHighestKillstreak as(Name alias) {
        return new GetTopHighestKillstreak(alias, this, parameters);
    }

    @Override
    public GetTopHighestKillstreak as(Table<?> alias) {
        return new GetTopHighestKillstreak(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopHighestKillstreak rename(String name) {
        return new GetTopHighestKillstreak(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopHighestKillstreak rename(Name name) {
        return new GetTopHighestKillstreak(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopHighestKillstreak rename(Table<?> name) {
        return new GetTopHighestKillstreak(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetTopHighestKillstreak call(
          Integer realmParam
        , Integer top
    ) {
        GetTopHighestKillstreak result = new GetTopHighestKillstreak(DSL.name("get_top_highest_killstreak"), null, new Field[] {
            DSL.val(realmParam, SQLDataType.INTEGER),
            DSL.val(top, SQLDataType.INTEGER)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetTopHighestKillstreak call(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        GetTopHighestKillstreak result = new GetTopHighestKillstreak(DSL.name("get_top_highest_killstreak"), null, new Field[] {
            realmParam,
            top
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
