/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetWorldLogsForBlockRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetWorldLogsForBlock extends TableImpl<GetWorldLogsForBlockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_world_logs_for_block</code>
     */
    public static final GetWorldLogsForBlock GET_WORLD_LOGS_FOR_BLOCK = new GetWorldLogsForBlock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetWorldLogsForBlockRecord> getRecordType() {
        return GetWorldLogsForBlockRecord.class;
    }

    /**
     * The column <code>public.get_world_logs_for_block.id</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.world</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, String> WORLD = createField(DSL.name("world"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.block_x</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, Integer> BLOCK_X = createField(DSL.name("block_x"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.block_y</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, Integer> BLOCK_Y = createField(DSL.name("block_y"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.block_z</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, Integer> BLOCK_Z = createField(DSL.name("block_z"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.action</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.material</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, String> MATERIAL = createField(DSL.name("material"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.block_data</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, String> BLOCK_DATA = createField(DSL.name("block_data"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.itemstack</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, byte[]> ITEMSTACK = createField(DSL.name("itemstack"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.time_val</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, Long> TIME_VAL = createField(DSL.name("time_val"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.metadata</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, JSON> METADATA = createField(DSL.name("metadata"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.get_world_logs_for_block.total</code>.
     */
    public final TableField<GetWorldLogsForBlockRecord, Long> TOTAL = createField(DSL.name("total"), SQLDataType.BIGINT, this, "");

    private GetWorldLogsForBlock(Name alias, Table<GetWorldLogsForBlockRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.VARCHAR),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.INTEGER)
        });
    }

    private GetWorldLogsForBlock(Name alias, Table<GetWorldLogsForBlockRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetWorldLogsForBlock(Name alias, Table<GetWorldLogsForBlockRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_world_logs_for_block</code> table
     * reference
     */
    public GetWorldLogsForBlock(String alias) {
        this(DSL.name(alias), GET_WORLD_LOGS_FOR_BLOCK);
    }

    /**
     * Create an aliased <code>public.get_world_logs_for_block</code> table
     * reference
     */
    public GetWorldLogsForBlock(Name alias) {
        this(alias, GET_WORLD_LOGS_FOR_BLOCK);
    }

    /**
     * Create a <code>public.get_world_logs_for_block</code> table reference
     */
    public GetWorldLogsForBlock() {
        this(DSL.name("get_world_logs_for_block"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetWorldLogsForBlock as(String alias) {
        return new GetWorldLogsForBlock(DSL.name(alias), this, parameters);
    }

    @Override
    public GetWorldLogsForBlock as(Name alias) {
        return new GetWorldLogsForBlock(alias, this, parameters);
    }

    @Override
    public GetWorldLogsForBlock as(Table<?> alias) {
        return new GetWorldLogsForBlock(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetWorldLogsForBlock rename(String name) {
        return new GetWorldLogsForBlock(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetWorldLogsForBlock rename(Name name) {
        return new GetWorldLogsForBlock(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetWorldLogsForBlock rename(Table<?> name) {
        return new GetWorldLogsForBlock(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetWorldLogsForBlock call(
          Integer realmParam
        , String worldParam
        , Integer blockXParam
        , Integer blockYParam
        , Integer blockZParam
        , Integer pageOffset
        , Integer pageLimit
    ) {
        GetWorldLogsForBlock result = new GetWorldLogsForBlock(DSL.name("get_world_logs_for_block"), null, new Field[] {
            DSL.val(realmParam, SQLDataType.INTEGER),
            DSL.val(worldParam, SQLDataType.VARCHAR),
            DSL.val(blockXParam, SQLDataType.INTEGER),
            DSL.val(blockYParam, SQLDataType.INTEGER),
            DSL.val(blockZParam, SQLDataType.INTEGER),
            DSL.val(pageOffset, SQLDataType.INTEGER),
            DSL.val(pageLimit, SQLDataType.INTEGER)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetWorldLogsForBlock call(
          Field<Integer> realmParam
        , Field<String> worldParam
        , Field<Integer> blockXParam
        , Field<Integer> blockYParam
        , Field<Integer> blockZParam
        , Field<Integer> pageOffset
        , Field<Integer> pageLimit
    ) {
        GetWorldLogsForBlock result = new GetWorldLogsForBlock(DSL.name("get_world_logs_for_block"), null, new Field[] {
            realmParam,
            worldParam,
            blockXParam,
            blockYParam,
            blockZParam,
            pageOffset,
            pageLimit
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
