/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Items.ItemsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.ItemloreRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Itemlore extends TableImpl<ItemloreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.itemlore</code>
     */
    public static final Itemlore ITEMLORE = new Itemlore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemloreRecord> getRecordType() {
        return ItemloreRecord.class;
    }

    /**
     * The column <code>public.itemlore.item</code>.
     */
    public final TableField<ItemloreRecord, Integer> ITEM = createField(DSL.name("item"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.itemlore.priority</code>.
     */
    public final TableField<ItemloreRecord, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.itemlore.text</code>.
     */
    public final TableField<ItemloreRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Itemlore(Name alias, Table<ItemloreRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Itemlore(Name alias, Table<ItemloreRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.itemlore</code> table reference
     */
    public Itemlore(String alias) {
        this(DSL.name(alias), ITEMLORE);
    }

    /**
     * Create an aliased <code>public.itemlore</code> table reference
     */
    public Itemlore(Name alias) {
        this(alias, ITEMLORE);
    }

    /**
     * Create a <code>public.itemlore</code> table reference
     */
    public Itemlore() {
        this(DSL.name("itemlore"), null);
    }

    public <O extends Record> Itemlore(Table<O> path, ForeignKey<O, ItemloreRecord> childPath, InverseForeignKey<O, ItemloreRecord> parentPath) {
        super(path, childPath, parentPath, ITEMLORE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemlorePath extends Itemlore implements Path<ItemloreRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemlorePath(Table<O> path, ForeignKey<O, ItemloreRecord> childPath, InverseForeignKey<O, ItemloreRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemlorePath(Name alias, Table<ItemloreRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemlorePath as(String alias) {
            return new ItemlorePath(DSL.name(alias), this);
        }

        @Override
        public ItemlorePath as(Name alias) {
            return new ItemlorePath(alias, this);
        }

        @Override
        public ItemlorePath as(Table<?> alias) {
            return new ItemlorePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<UniqueKey<ItemloreRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ITEMLORE_ITEM_PRIORITY_UK);
    }

    @Override
    public List<ForeignKey<ItemloreRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ITEMLORE__ITEMLORE_ITEM_FKEY);
    }

    private transient ItemsPath _items;

    /**
     * Get the implicit join path to the <code>public.items</code> table.
     */
    public ItemsPath items() {
        if (_items == null)
            _items = new ItemsPath(this, Keys.ITEMLORE__ITEMLORE_ITEM_FKEY, null);

        return _items;
    }

    @Override
    public Itemlore as(String alias) {
        return new Itemlore(DSL.name(alias), this);
    }

    @Override
    public Itemlore as(Name alias) {
        return new Itemlore(alias, this);
    }

    @Override
    public Itemlore as(Table<?> alias) {
        return new Itemlore(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Itemlore rename(String name) {
        return new Itemlore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Itemlore rename(Name name) {
        return new Itemlore(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Itemlore rename(Table<?> name) {
        return new Itemlore(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Itemlore where(Condition condition) {
        return new Itemlore(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Itemlore where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Itemlore where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Itemlore where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Itemlore where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Itemlore where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Itemlore where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Itemlore where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Itemlore whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Itemlore whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
