/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Logs.LogsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.LogsContextRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LogsContext extends TableImpl<LogsContextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.logs_context</code>
     */
    public static final LogsContext LOGS_CONTEXT = new LogsContext();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LogsContextRecord> getRecordType() {
        return LogsContextRecord.class;
    }

    /**
     * The column <code>public.logs_context.log_id</code>.
     */
    public final TableField<LogsContextRecord, Long> LOG_ID = createField(DSL.name("log_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.logs_context.realm</code>.
     */
    public final TableField<LogsContextRecord, Integer> REALM = createField(DSL.name("realm"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.logs_context.context</code>.
     */
    public final TableField<LogsContextRecord, String> CONTEXT = createField(DSL.name("context"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.logs_context.value</code>.
     */
    public final TableField<LogsContextRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private LogsContext(Name alias, Table<LogsContextRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LogsContext(Name alias, Table<LogsContextRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.logs_context</code> table reference
     */
    public LogsContext(String alias) {
        this(DSL.name(alias), LOGS_CONTEXT);
    }

    /**
     * Create an aliased <code>public.logs_context</code> table reference
     */
    public LogsContext(Name alias) {
        this(alias, LOGS_CONTEXT);
    }

    /**
     * Create a <code>public.logs_context</code> table reference
     */
    public LogsContext() {
        this(DSL.name("logs_context"), null);
    }

    public <O extends Record> LogsContext(Table<O> path, ForeignKey<O, LogsContextRecord> childPath, InverseForeignKey<O, LogsContextRecord> parentPath) {
        super(path, childPath, parentPath, LOGS_CONTEXT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LogsContextPath extends LogsContext implements Path<LogsContextRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LogsContextPath(Table<O> path, ForeignKey<O, LogsContextRecord> childPath, InverseForeignKey<O, LogsContextRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LogsContextPath(Name alias, Table<LogsContextRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LogsContextPath as(String alias) {
            return new LogsContextPath(DSL.name(alias), this);
        }

        @Override
        public LogsContextPath as(Name alias) {
            return new LogsContextPath(alias, this);
        }

        @Override
        public LogsContextPath as(Table<?> alias) {
            return new LogsContextPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LOGS_CONTEXT_CONTEXT_VALUE, Indexes.IDX_LOGS_CONTEXT_LOG_ID);
    }

    @Override
    public List<ForeignKey<LogsContextRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LOGS_CONTEXT__LOGS_CONTEXT_LOG_ID_FKEY);
    }

    private transient LogsPath _logs;

    /**
     * Get the implicit join path to the <code>public.logs</code> table.
     */
    public LogsPath logs() {
        if (_logs == null)
            _logs = new LogsPath(this, Keys.LOGS_CONTEXT__LOGS_CONTEXT_LOG_ID_FKEY, null);

        return _logs;
    }

    @Override
    public LogsContext as(String alias) {
        return new LogsContext(DSL.name(alias), this);
    }

    @Override
    public LogsContext as(Name alias) {
        return new LogsContext(alias, this);
    }

    @Override
    public LogsContext as(Table<?> alias) {
        return new LogsContext(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LogsContext rename(String name) {
        return new LogsContext(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LogsContext rename(Name name) {
        return new LogsContext(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LogsContext rename(Table<?> name) {
        return new LogsContext(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LogsContext where(Condition condition) {
        return new LogsContext(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LogsContext where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LogsContext where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LogsContext where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LogsContext where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LogsContext where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LogsContext where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LogsContext where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LogsContext whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LogsContext whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
