/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.records.PeriodMetaRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDate;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PeriodMeta extends TableImpl<PeriodMetaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.period_meta</code>
     */
    public static final PeriodMeta PERIOD_META = new PeriodMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PeriodMetaRecord> getRecordType() {
        return PeriodMetaRecord.class;
    }

    /**
     * The column <code>public.period_meta.period</code>.
     */
    public final TableField<PeriodMetaRecord, String> PERIOD = createField(DSL.name("period"), SQLDataType.VARCHAR(127).nullable(false), this, "");

    /**
     * The column <code>public.period_meta.start</code>.
     */
    public final TableField<PeriodMetaRecord, LocalDate> START = createField(DSL.name("start"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_DATE"), SQLDataType.LOCALDATE)), this, "");

    private PeriodMeta(Name alias, Table<PeriodMetaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PeriodMeta(Name alias, Table<PeriodMetaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.period_meta</code> table reference
     */
    public PeriodMeta(String alias) {
        this(DSL.name(alias), PERIOD_META);
    }

    /**
     * Create an aliased <code>public.period_meta</code> table reference
     */
    public PeriodMeta(Name alias) {
        this(alias, PERIOD_META);
    }

    /**
     * Create a <code>public.period_meta</code> table reference
     */
    public PeriodMeta() {
        this(DSL.name("period_meta"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PeriodMetaRecord> getPrimaryKey() {
        return Keys.PERIOD_META_PKEY;
    }

    @Override
    public PeriodMeta as(String alias) {
        return new PeriodMeta(DSL.name(alias), this);
    }

    @Override
    public PeriodMeta as(Name alias) {
        return new PeriodMeta(alias, this);
    }

    @Override
    public PeriodMeta as(Table<?> alias) {
        return new PeriodMeta(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PeriodMeta rename(String name) {
        return new PeriodMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PeriodMeta rename(Name name) {
        return new PeriodMeta(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PeriodMeta rename(Table<?> name) {
        return new PeriodMeta(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PeriodMeta where(Condition condition) {
        return new PeriodMeta(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PeriodMeta where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PeriodMeta where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PeriodMeta where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PeriodMeta where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PeriodMeta where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PeriodMeta where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PeriodMeta where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PeriodMeta whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PeriodMeta whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
