/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.core.database.jooq.Indexes;
import me.mykindos.betterpvp.core.database.jooq.Keys;
import me.mykindos.betterpvp.core.database.jooq.Public;
import me.mykindos.betterpvp.core.database.jooq.tables.Clients.ClientsPath;
import me.mykindos.betterpvp.core.database.jooq.tables.records.PunishmentsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Punishments extends TableImpl<PunishmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.punishments</code>
     */
    public static final Punishments PUNISHMENTS = new Punishments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PunishmentsRecord> getRecordType() {
        return PunishmentsRecord.class;
    }

    /**
     * The column <code>public.punishments.id</code>.
     */
    public final TableField<PunishmentsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.punishments.client</code>.
     */
    public final TableField<PunishmentsRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.punishments.type</code>.
     */
    public final TableField<PunishmentsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.punishments.rule</code>.
     */
    public final TableField<PunishmentsRecord, String> RULE = createField(DSL.name("rule"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.punishments.apply_time</code>.
     */
    public final TableField<PunishmentsRecord, Long> APPLY_TIME = createField(DSL.name("apply_time"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.punishments.expiry_time</code>.
     */
    public final TableField<PunishmentsRecord, Long> EXPIRY_TIME = createField(DSL.name("expiry_time"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.punishments.reason</code>.
     */
    public final TableField<PunishmentsRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.punishments.punisher</code>.
     */
    public final TableField<PunishmentsRecord, String> PUNISHER = createField(DSL.name("punisher"), SQLDataType.VARCHAR(36), this, "");

    /**
     * The column <code>public.punishments.revoker</code>.
     */
    public final TableField<PunishmentsRecord, String> REVOKER = createField(DSL.name("revoker"), SQLDataType.VARCHAR(36), this, "");

    /**
     * The column <code>public.punishments.revoke_type</code>.
     */
    public final TableField<PunishmentsRecord, String> REVOKE_TYPE = createField(DSL.name("revoke_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.punishments.revoke_time</code>.
     */
    public final TableField<PunishmentsRecord, Long> REVOKE_TIME = createField(DSL.name("revoke_time"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.punishments.revoke_reason</code>.
     */
    public final TableField<PunishmentsRecord, String> REVOKE_REASON = createField(DSL.name("revoke_reason"), SQLDataType.VARCHAR(255), this, "");

    private Punishments(Name alias, Table<PunishmentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Punishments(Name alias, Table<PunishmentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.punishments</code> table reference
     */
    public Punishments(String alias) {
        this(DSL.name(alias), PUNISHMENTS);
    }

    /**
     * Create an aliased <code>public.punishments</code> table reference
     */
    public Punishments(Name alias) {
        this(alias, PUNISHMENTS);
    }

    /**
     * Create a <code>public.punishments</code> table reference
     */
    public Punishments() {
        this(DSL.name("punishments"), null);
    }

    public <O extends Record> Punishments(Table<O> path, ForeignKey<O, PunishmentsRecord> childPath, InverseForeignKey<O, PunishmentsRecord> parentPath) {
        super(path, childPath, parentPath, PUNISHMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PunishmentsPath extends Punishments implements Path<PunishmentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PunishmentsPath(Table<O> path, ForeignKey<O, PunishmentsRecord> childPath, InverseForeignKey<O, PunishmentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PunishmentsPath(Name alias, Table<PunishmentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PunishmentsPath as(String alias) {
            return new PunishmentsPath(DSL.name(alias), this);
        }

        @Override
        public PunishmentsPath as(Name alias) {
            return new PunishmentsPath(alias, this);
        }

        @Override
        public PunishmentsPath as(Table<?> alias) {
            return new PunishmentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PUNISHMENTS_CLIENT);
    }

    @Override
    public Identity<PunishmentsRecord, Integer> getIdentity() {
        return (Identity<PunishmentsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PunishmentsRecord> getPrimaryKey() {
        return Keys.PUNISHMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<PunishmentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PUNISHMENTS__PUNISHMENTS_CLIENT_FKEY);
    }

    private transient ClientsPath _clients;

    /**
     * Get the implicit join path to the <code>public.clients</code> table.
     */
    public ClientsPath clients() {
        if (_clients == null)
            _clients = new ClientsPath(this, Keys.PUNISHMENTS__PUNISHMENTS_CLIENT_FKEY, null);

        return _clients;
    }

    @Override
    public Punishments as(String alias) {
        return new Punishments(DSL.name(alias), this);
    }

    @Override
    public Punishments as(Name alias) {
        return new Punishments(alias, this);
    }

    @Override
    public Punishments as(Table<?> alias) {
        return new Punishments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Punishments rename(String name) {
        return new Punishments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Punishments rename(Name name) {
        return new Punishments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Punishments rename(Table<?> name) {
        return new Punishments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punishments where(Condition condition) {
        return new Punishments(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punishments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punishments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punishments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punishments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punishments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punishments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Punishments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punishments whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Punishments whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
