# Assassin
# +8 health (set total)
reinforced_assassin_helmet:
  health:
    base: 1.5
    min: 0.0
    max: 4.5
  durability: 1020
reinforced_assassin_chestplate:
  health:
    base: 2.5
    min: 0.0
    max: 5.5
  durability: 1020
reinforced_assassin_leggings:
  health:
    base: 1.5
    min: 0.0
    max: 5.5
  durability: 1020
reinforced_assassin_boots:
  health:
    base: 1.5
    min: 0.0
    max: 4.5
  durability: 1020

# Knight
# +18 health (set total)
reinforced_knight_helmet:
  health:
    base: 4.5
    min: 0.0
    max: 9.0
  durability: 1020
reinforced_knight_chestplate:
  health:
    base: 5.5
    min: 2.5
    max: 10.0
  durability: 1020
reinforced_knight_leggings:
  health:
    base: 5.5
    min: 2.5
    max: 10.0
  durability: 1020
reinforced_knight_boots:
  health:
    base: 2.5
    min: 0.0
    max: 5.5
  durability: 1020

# Brute
# +18 health (set total)
reinforced_brute_helmet:
  health:
    base: 4.5
    min: 0.0
    max: 9.0
  durability: 1020
reinforced_brute_chestplate:
  health:
    base: 5.5
    min: 2.5
    max: 10.0
  durability: 1020
reinforced_brute_leggings:
  health:
    base: 5.5
    min: 2.5
    max: 10.0
  durability: 1020
reinforced_brute_boots:
  health:
    base: 2.5
    min: 0.0
    max: 5.5
  durability: 1020

# Ranger
# +14 health (set total)
reinforced_ranger_helmet:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_ranger_chestplate:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_ranger_leggings:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_ranger_boots:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020

# Mage
# +14 health (set total)
reinforced_mage_helmet:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_mage_chestplate:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_mage_leggings:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_mage_boots:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020

# Warlock
# +14 health (set total)
reinforced_warlock_helmet:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_warlock_chestplate:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_warlock_leggings:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
reinforced_warlock_boots:
  health:
    base: 3.5
    min: 0.0
    max: 6.5
  durability: 1020
