/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq;


import me.mykindos.betterpvp.core.database.jooq.tables.GetAchievementCompletions;
import me.mykindos.betterpvp.core.database.jooq.tables.GetClientAchievementRanks;
import me.mykindos.betterpvp.core.database.jooq.tables.GetClientStats;
import me.mykindos.betterpvp.core.database.jooq.tables.GetCombatData;
import me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndAction;
import me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndValue;
import me.mykindos.betterpvp.core.database.jooq.tables.GetOfflineMessagesByTime;
import me.mykindos.betterpvp.core.database.jooq.tables.GetTopDeaths;
import me.mykindos.betterpvp.core.database.jooq.tables.GetTopHighestKillstreak;
import me.mykindos.betterpvp.core.database.jooq.tables.GetTopKdr;
import me.mykindos.betterpvp.core.database.jooq.tables.GetTopKills;
import me.mykindos.betterpvp.core.database.jooq.tables.GetTopKillstreak;
import me.mykindos.betterpvp.core.database.jooq.tables.GetTopRating;
import me.mykindos.betterpvp.core.database.jooq.tables.GetTotalAchievementCompletions;
import me.mykindos.betterpvp.core.database.jooq.tables.GetWorldLogsForBlock;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetAchievementCompletionsRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetClientAchievementRanksRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetClientStatsRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetCombatDataRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetLogMessagesByContextAndActionRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetLogMessagesByContextAndValueRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetOfflineMessagesByTimeRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopDeathsRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopHighestKillstreakRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopKdrRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopKillsRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopKillstreakRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTopRatingRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetTotalAchievementCompletionsRecord;
import me.mykindos.betterpvp.core.database.jooq.tables.records.GetWorldLogsForBlockRecord;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.get_achievement_completions</code>.
     */
    public static Result<GetAchievementCompletionsRecord> getAchievementCompletions(
          Configuration configuration
        , Long clientParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetAchievementCompletions.GET_ACHIEVEMENT_COMPLETIONS.call(
              clientParam
        )).fetch();
    }

    /**
     * Get <code>public.get_achievement_completions</code> as a table.
     */
    public static GetAchievementCompletions getAchievementCompletions(
          Long clientParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetAchievementCompletions.GET_ACHIEVEMENT_COMPLETIONS.call(
            clientParam
        );
    }

    /**
     * Get <code>public.get_achievement_completions</code> as a table.
     */
    public static GetAchievementCompletions getAchievementCompletions(
          Field<Long> clientParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetAchievementCompletions.GET_ACHIEVEMENT_COMPLETIONS.call(
            clientParam
        );
    }

    /**
     * Call <code>public.get_client_achievement_ranks</code>.
     */
    public static Result<GetClientAchievementRanksRecord> getClientAchievementRanks(
          Configuration configuration
        , Long clientParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetClientAchievementRanks.GET_CLIENT_ACHIEVEMENT_RANKS.call(
              clientParam
        )).fetch();
    }

    /**
     * Get <code>public.get_client_achievement_ranks</code> as a table.
     */
    public static GetClientAchievementRanks getClientAchievementRanks(
          Long clientParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetClientAchievementRanks.GET_CLIENT_ACHIEVEMENT_RANKS.call(
            clientParam
        );
    }

    /**
     * Get <code>public.get_client_achievement_ranks</code> as a table.
     */
    public static GetClientAchievementRanks getClientAchievementRanks(
          Field<Long> clientParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetClientAchievementRanks.GET_CLIENT_ACHIEVEMENT_RANKS.call(
            clientParam
        );
    }

    /**
     * Call <code>public.get_client_stats</code>.
     */
    public static Result<GetClientStatsRecord> getClientStats(
          Configuration configuration
        , Long clientParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetClientStats.GET_CLIENT_STATS.call(
              clientParam
        )).fetch();
    }

    /**
     * Get <code>public.get_client_stats</code> as a table.
     */
    public static GetClientStats getClientStats(
          Long clientParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetClientStats.GET_CLIENT_STATS.call(
            clientParam
        );
    }

    /**
     * Get <code>public.get_client_stats</code> as a table.
     */
    public static GetClientStats getClientStats(
          Field<Long> clientParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetClientStats.GET_CLIENT_STATS.call(
            clientParam
        );
    }

    /**
     * Call <code>public.get_combat_data</code>.
     */
    public static Result<GetCombatDataRecord> getCombatData(
          Configuration configuration
        , String clientUuid
        , Integer realmParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetCombatData.GET_COMBAT_DATA.call(
              clientUuid
            , realmParam
        )).fetch();
    }

    /**
     * Get <code>public.get_combat_data</code> as a table.
     */
    public static GetCombatData getCombatData(
          String clientUuid
        , Integer realmParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetCombatData.GET_COMBAT_DATA.call(
            clientUuid,
            realmParam
        );
    }

    /**
     * Get <code>public.get_combat_data</code> as a table.
     */
    public static GetCombatData getCombatData(
          Field<String> clientUuid
        , Field<Integer> realmParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetCombatData.GET_COMBAT_DATA.call(
            clientUuid,
            realmParam
        );
    }

    /**
     * Call <code>public.get_log_messages_by_context_and_action</code>.
     */
    public static Result<GetLogMessagesByContextAndActionRecord> getLogMessagesByContextAndAction(
          Configuration configuration
        , String contextParam
        , String valueParam
        , String actionParam
        , Integer realmParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndAction.GET_LOG_MESSAGES_BY_CONTEXT_AND_ACTION.call(
              contextParam
            , valueParam
            , actionParam
            , realmParam
        )).fetch();
    }

    /**
     * Get <code>public.get_log_messages_by_context_and_action</code> as a
     * table.
     */
    public static GetLogMessagesByContextAndAction getLogMessagesByContextAndAction(
          String contextParam
        , String valueParam
        , String actionParam
        , Integer realmParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndAction.GET_LOG_MESSAGES_BY_CONTEXT_AND_ACTION.call(
            contextParam,
            valueParam,
            actionParam,
            realmParam
        );
    }

    /**
     * Get <code>public.get_log_messages_by_context_and_action</code> as a
     * table.
     */
    public static GetLogMessagesByContextAndAction getLogMessagesByContextAndAction(
          Field<String> contextParam
        , Field<String> valueParam
        , Field<String> actionParam
        , Field<Integer> realmParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndAction.GET_LOG_MESSAGES_BY_CONTEXT_AND_ACTION.call(
            contextParam,
            valueParam,
            actionParam,
            realmParam
        );
    }

    /**
     * Call <code>public.get_log_messages_by_context_and_value</code>.
     */
    public static Result<GetLogMessagesByContextAndValueRecord> getLogMessagesByContextAndValue(
          Configuration configuration
        , String contextParam
        , String valueParam
        , Integer realmParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndValue.GET_LOG_MESSAGES_BY_CONTEXT_AND_VALUE.call(
              contextParam
            , valueParam
            , realmParam
        )).fetch();
    }

    /**
     * Get <code>public.get_log_messages_by_context_and_value</code> as a table.
     */
    public static GetLogMessagesByContextAndValue getLogMessagesByContextAndValue(
          String contextParam
        , String valueParam
        , Integer realmParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndValue.GET_LOG_MESSAGES_BY_CONTEXT_AND_VALUE.call(
            contextParam,
            valueParam,
            realmParam
        );
    }

    /**
     * Get <code>public.get_log_messages_by_context_and_value</code> as a table.
     */
    public static GetLogMessagesByContextAndValue getLogMessagesByContextAndValue(
          Field<String> contextParam
        , Field<String> valueParam
        , Field<Integer> realmParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndValue.GET_LOG_MESSAGES_BY_CONTEXT_AND_VALUE.call(
            contextParam,
            valueParam,
            realmParam
        );
    }

    /**
     * Call <code>public.get_offline_messages_by_time</code>.
     */
    public static Result<GetOfflineMessagesByTimeRecord> getOfflineMessagesByTime(
          Configuration configuration
        , Long clientParam
        , Long timeParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetOfflineMessagesByTime.GET_OFFLINE_MESSAGES_BY_TIME.call(
              clientParam
            , timeParam
        )).fetch();
    }

    /**
     * Get <code>public.get_offline_messages_by_time</code> as a table.
     */
    public static GetOfflineMessagesByTime getOfflineMessagesByTime(
          Long clientParam
        , Long timeParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetOfflineMessagesByTime.GET_OFFLINE_MESSAGES_BY_TIME.call(
            clientParam,
            timeParam
        );
    }

    /**
     * Get <code>public.get_offline_messages_by_time</code> as a table.
     */
    public static GetOfflineMessagesByTime getOfflineMessagesByTime(
          Field<Long> clientParam
        , Field<Long> timeParam
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetOfflineMessagesByTime.GET_OFFLINE_MESSAGES_BY_TIME.call(
            clientParam,
            timeParam
        );
    }

    /**
     * Call <code>public.get_top_deaths</code>.
     */
    public static Result<GetTopDeathsRecord> getTopDeaths(
          Configuration configuration
        , Integer realmParam
        , Integer top
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetTopDeaths.GET_TOP_DEATHS.call(
              realmParam
            , top
        )).fetch();
    }

    /**
     * Get <code>public.get_top_deaths</code> as a table.
     */
    public static GetTopDeaths getTopDeaths(
          Integer realmParam
        , Integer top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopDeaths.GET_TOP_DEATHS.call(
            realmParam,
            top
        );
    }

    /**
     * Get <code>public.get_top_deaths</code> as a table.
     */
    public static GetTopDeaths getTopDeaths(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopDeaths.GET_TOP_DEATHS.call(
            realmParam,
            top
        );
    }

    /**
     * Call <code>public.get_top_highest_killstreak</code>.
     */
    public static Result<GetTopHighestKillstreakRecord> getTopHighestKillstreak(
          Configuration configuration
        , Integer realmParam
        , Integer top
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetTopHighestKillstreak.GET_TOP_HIGHEST_KILLSTREAK.call(
              realmParam
            , top
        )).fetch();
    }

    /**
     * Get <code>public.get_top_highest_killstreak</code> as a table.
     */
    public static GetTopHighestKillstreak getTopHighestKillstreak(
          Integer realmParam
        , Integer top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopHighestKillstreak.GET_TOP_HIGHEST_KILLSTREAK.call(
            realmParam,
            top
        );
    }

    /**
     * Get <code>public.get_top_highest_killstreak</code> as a table.
     */
    public static GetTopHighestKillstreak getTopHighestKillstreak(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopHighestKillstreak.GET_TOP_HIGHEST_KILLSTREAK.call(
            realmParam,
            top
        );
    }

    /**
     * Call <code>public.get_top_kdr</code>.
     */
    public static Result<GetTopKdrRecord> getTopKdr(
          Configuration configuration
        , Integer realmParam
        , Integer top
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetTopKdr.GET_TOP_KDR.call(
              realmParam
            , top
        )).fetch();
    }

    /**
     * Get <code>public.get_top_kdr</code> as a table.
     */
    public static GetTopKdr getTopKdr(
          Integer realmParam
        , Integer top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopKdr.GET_TOP_KDR.call(
            realmParam,
            top
        );
    }

    /**
     * Get <code>public.get_top_kdr</code> as a table.
     */
    public static GetTopKdr getTopKdr(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopKdr.GET_TOP_KDR.call(
            realmParam,
            top
        );
    }

    /**
     * Call <code>public.get_top_kills</code>.
     */
    public static Result<GetTopKillsRecord> getTopKills(
          Configuration configuration
        , Integer realmParam
        , Integer top
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetTopKills.GET_TOP_KILLS.call(
              realmParam
            , top
        )).fetch();
    }

    /**
     * Get <code>public.get_top_kills</code> as a table.
     */
    public static GetTopKills getTopKills(
          Integer realmParam
        , Integer top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopKills.GET_TOP_KILLS.call(
            realmParam,
            top
        );
    }

    /**
     * Get <code>public.get_top_kills</code> as a table.
     */
    public static GetTopKills getTopKills(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopKills.GET_TOP_KILLS.call(
            realmParam,
            top
        );
    }

    /**
     * Call <code>public.get_top_killstreak</code>.
     */
    public static Result<GetTopKillstreakRecord> getTopKillstreak(
          Configuration configuration
        , Integer realmParam
        , Integer top
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetTopKillstreak.GET_TOP_KILLSTREAK.call(
              realmParam
            , top
        )).fetch();
    }

    /**
     * Get <code>public.get_top_killstreak</code> as a table.
     */
    public static GetTopKillstreak getTopKillstreak(
          Integer realmParam
        , Integer top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopKillstreak.GET_TOP_KILLSTREAK.call(
            realmParam,
            top
        );
    }

    /**
     * Get <code>public.get_top_killstreak</code> as a table.
     */
    public static GetTopKillstreak getTopKillstreak(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopKillstreak.GET_TOP_KILLSTREAK.call(
            realmParam,
            top
        );
    }

    /**
     * Call <code>public.get_top_rating</code>.
     */
    public static Result<GetTopRatingRecord> getTopRating(
          Configuration configuration
        , Integer realmParam
        , Integer top
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetTopRating.GET_TOP_RATING.call(
              realmParam
            , top
        )).fetch();
    }

    /**
     * Get <code>public.get_top_rating</code> as a table.
     */
    public static GetTopRating getTopRating(
          Integer realmParam
        , Integer top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopRating.GET_TOP_RATING.call(
            realmParam,
            top
        );
    }

    /**
     * Get <code>public.get_top_rating</code> as a table.
     */
    public static GetTopRating getTopRating(
          Field<Integer> realmParam
        , Field<Integer> top
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTopRating.GET_TOP_RATING.call(
            realmParam,
            top
        );
    }

    /**
     * Call <code>public.get_total_achievement_completions</code>.
     */
    public static Result<GetTotalAchievementCompletionsRecord> getTotalAchievementCompletions(
          Configuration configuration
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetTotalAchievementCompletions.GET_TOTAL_ACHIEVEMENT_COMPLETIONS.call(
        )).fetch();
    }

    /**
     * Get <code>public.get_total_achievement_completions</code> as a table.
     */
    public static GetTotalAchievementCompletions getTotalAchievementCompletions() {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetTotalAchievementCompletions.GET_TOTAL_ACHIEVEMENT_COMPLETIONS.call(
        );
    }

    /**
     * Call <code>public.get_world_logs_for_block</code>.
     */
    public static Result<GetWorldLogsForBlockRecord> getWorldLogsForBlock(
          Configuration configuration
        , Integer realmParam
        , String worldParam
        , Integer blockXParam
        , Integer blockYParam
        , Integer blockZParam
        , Integer pageOffset
        , Integer pageLimit
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.core.database.jooq.tables.GetWorldLogsForBlock.GET_WORLD_LOGS_FOR_BLOCK.call(
              realmParam
            , worldParam
            , blockXParam
            , blockYParam
            , blockZParam
            , pageOffset
            , pageLimit
        )).fetch();
    }

    /**
     * Get <code>public.get_world_logs_for_block</code> as a table.
     */
    public static GetWorldLogsForBlock getWorldLogsForBlock(
          Integer realmParam
        , String worldParam
        , Integer blockXParam
        , Integer blockYParam
        , Integer blockZParam
        , Integer pageOffset
        , Integer pageLimit
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetWorldLogsForBlock.GET_WORLD_LOGS_FOR_BLOCK.call(
            realmParam,
            worldParam,
            blockXParam,
            blockYParam,
            blockZParam,
            pageOffset,
            pageLimit
        );
    }

    /**
     * Get <code>public.get_world_logs_for_block</code> as a table.
     */
    public static GetWorldLogsForBlock getWorldLogsForBlock(
          Field<Integer> realmParam
        , Field<String> worldParam
        , Field<Integer> blockXParam
        , Field<Integer> blockYParam
        , Field<Integer> blockZParam
        , Field<Integer> pageOffset
        , Field<Integer> pageLimit
    ) {
        return me.mykindos.betterpvp.core.database.jooq.tables.GetWorldLogsForBlock.GET_WORLD_LOGS_FOR_BLOCK.call(
            realmParam,
            worldParam,
            blockXParam,
            blockYParam,
            blockZParam,
            pageOffset,
            pageLimit
        );
    }
}
