/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.shops.database.jooq.tables.records;


import me.mykindos.betterpvp.shops.database.jooq.tables.AuctionTransactionHistory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuctionTransactionHistoryRecord extends UpdatableRecordImpl<AuctionTransactionHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.auction_transaction_history.auction_id</code>.
     */
    public AuctionTransactionHistoryRecord setAuctionId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.auction_transaction_history.auction_id</code>.
     */
    public Long getAuctionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.auction_transaction_history.buyer</code>.
     */
    public AuctionTransactionHistoryRecord setBuyer(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.auction_transaction_history.buyer</code>.
     */
    public Long getBuyer() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.auction_transaction_history.time_sold</code>.
     */
    public AuctionTransactionHistoryRecord setTimeSold(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.auction_transaction_history.time_sold</code>.
     */
    public Long getTimeSold() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuctionTransactionHistoryRecord
     */
    public AuctionTransactionHistoryRecord() {
        super(AuctionTransactionHistory.AUCTION_TRANSACTION_HISTORY);
    }

    /**
     * Create a detached, initialised AuctionTransactionHistoryRecord
     */
    public AuctionTransactionHistoryRecord(Long auctionId, Long buyer, Long timeSold) {
        super(AuctionTransactionHistory.AUCTION_TRANSACTION_HISTORY);

        setAuctionId(auctionId);
        setBuyer(buyer);
        setTimeSold(timeSold);
        resetChangedOnNotNull();
    }
}
