/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.shops.database.jooq.tables.records;


import me.mykindos.betterpvp.shops.database.jooq.tables.Shopitems;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShopitemsRecord extends UpdatableRecordImpl<ShopitemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shopitems.id</code>.
     */
    public ShopitemsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.shopitems.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shopitems.shopkeeper</code>.
     */
    public ShopitemsRecord setShopkeeper(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.shopitems.shopkeeper</code>.
     */
    public String getShopkeeper() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.shopitems.buy_price</code>.
     */
    public ShopitemsRecord setBuyPrice(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.shopitems.buy_price</code>.
     */
    public Integer getBuyPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.shopitems.sell_price</code>.
     */
    public ShopitemsRecord setSellPrice(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.shopitems.sell_price</code>.
     */
    public Integer getSellPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.shopitems.item_key</code>.
     */
    public ShopitemsRecord setItemKey(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.shopitems.item_key</code>.
     */
    public String getItemKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.shopitems.order</code>.
     */
    public ShopitemsRecord setOrder(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.shopitems.order</code>.
     */
    public Integer getOrder() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopitemsRecord
     */
    public ShopitemsRecord() {
        super(Shopitems.SHOPITEMS);
    }

    /**
     * Create a detached, initialised ShopitemsRecord
     */
    public ShopitemsRecord(Integer id, String shopkeeper, Integer buyPrice, Integer sellPrice, String itemKey, Integer order) {
        super(Shopitems.SHOPITEMS);

        setId(id);
        setShopkeeper(shopkeeper);
        setBuyPrice(buyPrice);
        setSellPrice(sellPrice);
        setItemKey(itemKey);
        setOrder(order);
        resetChangedOnNotNull();
    }
}
