/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq;


import me.mykindos.betterpvp.clans.database.jooq.tables.ClanInsurance;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClansKills;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CLAN_INSURANCE_CLAN_TIME_INDEX = Internal.createIndex(DSL.name("clan_insurance_clan_time_index"), ClanInsurance.CLAN_INSURANCE, new OrderField[] { ClanInsurance.CLAN_INSURANCE.CLAN, ClanInsurance.CLAN_INSURANCE.TIME.desc() }, false);
    public static final Index CLAN_INSURANCE_TIME_INDEX = Internal.createIndex(DSL.name("clan_insurance_time_index"), ClanInsurance.CLAN_INSURANCE, new OrderField[] { ClanInsurance.CLAN_INSURANCE.TIME.desc() }, false);
    public static final Index CLANS_KILLS_KILLER_CLAN_INDEX = Internal.createIndex(DSL.name("clans_kills_killer_clan_index"), ClansKills.CLANS_KILLS, new OrderField[] { ClansKills.CLANS_KILLS.KILLER_CLAN }, false);
    public static final Index CLANS_KILLS_VICTIM_CLAN_INDEX = Internal.createIndex(DSL.name("clans_kills_victim_clan_index"), ClansKills.CLANS_KILLS, new OrderField[] { ClansKills.CLANS_KILLS.VICTIM_CLAN }, false);
}
