/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq;


import java.util.Arrays;
import java.util.List;

import me.mykindos.betterpvp.clans.database.jooq.tables.ClanAlliances;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClanEnemies;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClanInsurance;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClanMembers;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClanMetadata;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClanProperties;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClanTerritory;
import me.mykindos.betterpvp.clans.database.jooq.tables.Clans;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClansDominanceScale;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClansFieldsOres;
import me.mykindos.betterpvp.clans.database.jooq.tables.ClansKills;
import me.mykindos.betterpvp.clans.database.jooq.tables.GetClanKillLogs;
import me.mykindos.betterpvp.clans.database.jooq.tables.records.GetClanKillLogsRecord;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.clan_alliances</code>.
     */
    public final ClanAlliances CLAN_ALLIANCES = ClanAlliances.CLAN_ALLIANCES;

    /**
     * The table <code>public.clan_enemies</code>.
     */
    public final ClanEnemies CLAN_ENEMIES = ClanEnemies.CLAN_ENEMIES;

    /**
     * The table <code>public.clan_insurance</code>.
     */
    public final ClanInsurance CLAN_INSURANCE = ClanInsurance.CLAN_INSURANCE;

    /**
     * The table <code>public.clan_members</code>.
     */
    public final ClanMembers CLAN_MEMBERS = ClanMembers.CLAN_MEMBERS;

    /**
     * The table <code>public.clan_metadata</code>.
     */
    public final ClanMetadata CLAN_METADATA = ClanMetadata.CLAN_METADATA;

    /**
     * The table <code>public.clan_properties</code>.
     */
    public final ClanProperties CLAN_PROPERTIES = ClanProperties.CLAN_PROPERTIES;

    /**
     * The table <code>public.clan_territory</code>.
     */
    public final ClanTerritory CLAN_TERRITORY = ClanTerritory.CLAN_TERRITORY;

    /**
     * The table <code>public.clans</code>.
     */
    public final Clans CLANS = Clans.CLANS;

    /**
     * The table <code>public.clans_dominance_scale</code>.
     */
    public final ClansDominanceScale CLANS_DOMINANCE_SCALE = ClansDominanceScale.CLANS_DOMINANCE_SCALE;

    /**
     * The table <code>public.clans_fields_ores</code>.
     */
    public final ClansFieldsOres CLANS_FIELDS_ORES = ClansFieldsOres.CLANS_FIELDS_ORES;

    /**
     * The table <code>public.clans_kills</code>.
     */
    public final ClansKills CLANS_KILLS = ClansKills.CLANS_KILLS;

    /**
     * The table <code>public.get_clan_kill_logs</code>.
     */
    public final GetClanKillLogs GET_CLAN_KILL_LOGS = GetClanKillLogs.GET_CLAN_KILL_LOGS;

    /**
     * Call <code>public.get_clan_kill_logs</code>.
     */
    public static Result<GetClanKillLogsRecord> GET_CLAN_KILL_LOGS(
          Configuration configuration
        , Long pClanId
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.clans.database.jooq.tables.GetClanKillLogs.GET_CLAN_KILL_LOGS.call(
              pClanId
        )).fetch();
    }

    /**
     * Get <code>public.get_clan_kill_logs</code> as a table.
     */
    public static GetClanKillLogs GET_CLAN_KILL_LOGS(
          Long pClanId
    ) {
        return me.mykindos.betterpvp.clans.database.jooq.tables.GetClanKillLogs.GET_CLAN_KILL_LOGS.call(
            pClanId
        );
    }

    /**
     * Get <code>public.get_clan_kill_logs</code> as a table.
     */
    public static GetClanKillLogs GET_CLAN_KILL_LOGS(
          Field<Long> pClanId
    ) {
        return me.mykindos.betterpvp.clans.database.jooq.tables.GetClanKillLogs.GET_CLAN_KILL_LOGS.call(
            pClanId
        );
    }

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ClanAlliances.CLAN_ALLIANCES,
            ClanEnemies.CLAN_ENEMIES,
            ClanInsurance.CLAN_INSURANCE,
            ClanMembers.CLAN_MEMBERS,
            ClanMetadata.CLAN_METADATA,
            ClanProperties.CLAN_PROPERTIES,
            ClanTerritory.CLAN_TERRITORY,
            Clans.CLANS,
            ClansDominanceScale.CLANS_DOMINANCE_SCALE,
            ClansFieldsOres.CLANS_FIELDS_ORES,
            ClansKills.CLANS_KILLS,
            GetClanKillLogs.GET_CLAN_KILL_LOGS
        );
    }
}
