/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.game.database.jooq;


import me.mykindos.betterpvp.game.database.jooq.tables.ChampionsHotbarLayouts;
import me.mykindos.betterpvp.game.database.jooq.tables.records.ChampionsHotbarLayoutsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChampionsHotbarLayoutsRecord> CHAMPIONS_HOTBAR_LAYOUTS_PKEY = Internal.createUniqueKey(ChampionsHotbarLayouts.CHAMPIONS_HOTBAR_LAYOUTS, DSL.name("champions_hotbar_layouts_pkey"), new TableField[] { ChampionsHotbarLayouts.CHAMPIONS_HOTBAR_LAYOUTS.CLIENT, ChampionsHotbarLayouts.CHAMPIONS_HOTBAR_LAYOUTS.ROLE, ChampionsHotbarLayouts.CHAMPIONS_HOTBAR_LAYOUTS.ID, ChampionsHotbarLayouts.CHAMPIONS_HOTBAR_LAYOUTS.SLOT }, true);
}
