/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.game.database.jooq;


import java.util.Arrays;
import java.util.List;

import me.mykindos.betterpvp.game.database.jooq.tables.ChampionsHotbarLayouts;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.champions_hotbar_layouts</code>.
     */
    public final ChampionsHotbarLayouts CHAMPIONS_HOTBAR_LAYOUTS = ChampionsHotbarLayouts.CHAMPIONS_HOTBAR_LAYOUTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ChampionsHotbarLayouts.CHAMPIONS_HOTBAR_LAYOUTS
        );
    }
}
