/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import java.time.LocalDateTime;

import me.mykindos.betterpvp.core.database.jooq.tables.ClientIps;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientIpsRecord extends UpdatableRecordImpl<ClientIpsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client_ips.id</code>.
     */
    public ClientIpsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.client_ips.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.client_ips.client</code>.
     */
    public ClientIpsRecord setClient(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.client_ips.client</code>.
     */
    public Long getClient() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.client_ips.ip_hash</code>.
     */
    public ClientIpsRecord setIpHash(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.client_ips.ip_hash</code>.
     */
    public String getIpHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.client_ips.created_at</code>.
     */
    public ClientIpsRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.client_ips.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.client_ips.last_seen</code>.
     */
    public ClientIpsRecord setLastSeen(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.client_ips.last_seen</code>.
     */
    public Long getLastSeen() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientIpsRecord
     */
    public ClientIpsRecord() {
        super(ClientIps.CLIENT_IPS);
    }

    /**
     * Create a detached, initialised ClientIpsRecord
     */
    public ClientIpsRecord(Integer id, Long client, String ipHash, LocalDateTime createdAt, Long lastSeen) {
        super(ClientIps.CLIENT_IPS);

        setId(id);
        setClient(client);
        setIpHash(ipHash);
        setCreatedAt(createdAt);
        setLastSeen(lastSeen);
        resetChangedOnNotNull();
    }
}
