/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.ClientRewards;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRewardsRecord extends UpdatableRecordImpl<ClientRewardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client_rewards.client</code>.
     */
    public ClientRewardsRecord setClient(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.client_rewards.client</code>.
     */
    public Long getClient() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.client_rewards.season</code>.
     */
    public ClientRewardsRecord setSeason(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.client_rewards.season</code>.
     */
    public Integer getSeason() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.client_rewards.rewards</code>.
     */
    public ClientRewardsRecord setRewards(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.client_rewards.rewards</code>.
     */
    public String getRewards() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRewardsRecord
     */
    public ClientRewardsRecord() {
        super(ClientRewards.CLIENT_REWARDS);
    }

    /**
     * Create a detached, initialised ClientRewardsRecord
     */
    public ClientRewardsRecord(Long client, Integer season, String rewards) {
        super(ClientRewards.CLIENT_REWARDS);

        setClient(client);
        setSeason(season);
        setRewards(rewards);
        resetChangedOnNotNull();
    }
}
