/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.CombatStats;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CombatStatsRecord extends UpdatableRecordImpl<CombatStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.combat_stats.client</code>.
     */
    public CombatStatsRecord setClient(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.combat_stats.client</code>.
     */
    public Long getClient() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.combat_stats.realm</code>.
     */
    public CombatStatsRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.combat_stats.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.combat_stats.rating</code>.
     */
    public CombatStatsRecord setRating(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.combat_stats.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.combat_stats.killstreak</code>.
     */
    public CombatStatsRecord setKillstreak(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.combat_stats.killstreak</code>.
     */
    public Integer getKillstreak() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.combat_stats.highest_killstreak</code>.
     */
    public CombatStatsRecord setHighestKillstreak(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.combat_stats.highest_killstreak</code>.
     */
    public Integer getHighestKillstreak() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.combat_stats.valid</code>.
     */
    public CombatStatsRecord setValid(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.combat_stats.valid</code>.
     */
    public Boolean getValid() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CombatStatsRecord
     */
    public CombatStatsRecord() {
        super(CombatStats.COMBAT_STATS);
    }

    /**
     * Create a detached, initialised CombatStatsRecord
     */
    public CombatStatsRecord(Long client, Integer realm, Integer rating, Integer killstreak, Integer highestKillstreak, Boolean valid) {
        super(CombatStats.COMBAT_STATS);

        setClient(client);
        setRealm(realm);
        setRating(rating);
        setKillstreak(killstreak);
        setHighestKillstreak(highestKillstreak);
        setValid(valid);
        resetChangedOnNotNull();
    }
}
