/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GameData;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameDataRecord extends UpdatableRecordImpl<GameDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_data.id</code>.
     */
    public GameDataRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.game_data.game</code>.
     */
    public GameDataRecord setGame(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game_data.game</code>.
     */
    public String getGame() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.game_data.map</code>.
     */
    public GameDataRecord setMap(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game_data.map</code>.
     */
    public String getMap() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameDataRecord
     */
    public GameDataRecord() {
        super(GameData.GAME_DATA);
    }

    /**
     * Create a detached, initialised GameDataRecord
     */
    public GameDataRecord(Long id, String game, String map) {
        super(GameData.GAME_DATA);

        setId(id);
        setGame(game);
        setMap(map);
        resetChangedOnNotNull();
    }
}
