/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GameTeams;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameTeamsRecord extends UpdatableRecordImpl<GameTeamsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_teams.id</code>.
     */
    public GameTeamsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game_teams.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.game_teams.client</code>.
     */
    public GameTeamsRecord setClient(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game_teams.client</code>.
     */
    public Long getClient() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.game_teams.team</code>.
     */
    public GameTeamsRecord setTeam(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game_teams.team</code>.
     */
    public String getTeam() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameTeamsRecord
     */
    public GameTeamsRecord() {
        super(GameTeams.GAME_TEAMS);
    }

    /**
     * Create a detached, initialised GameTeamsRecord
     */
    public GameTeamsRecord(Long id, Long client, String team) {
        super(GameTeams.GAME_TEAMS);

        setId(id);
        setClient(client);
        setTeam(team);
        resetChangedOnNotNull();
    }
}
