/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GetClientStats;
import org.jooq.JSONB;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetClientStatsRecord extends TableRecordImpl<GetClientStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_client_stats.period</code>.
     */
    public GetClientStatsRecord setPeriod(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_client_stats.period</code>.
     */
    public Long getPeriod() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.get_client_stats.stattype</code>.
     */
    public GetClientStatsRecord setStattype(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_client_stats.stattype</code>.
     */
    public Long getStattype() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.get_client_stats.data</code>.
     */
    public GetClientStatsRecord setData(JSONB value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.get_client_stats.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.get_client_stats.stat</code>.
     */
    public GetClientStatsRecord setStat(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.get_client_stats.stat</code>.
     */
    public Long getStat() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetClientStatsRecord
     */
    public GetClientStatsRecord() {
        super(GetClientStats.GET_CLIENT_STATS);
    }

    /**
     * Create a detached, initialised GetClientStatsRecord
     */
    public GetClientStatsRecord(Long period, Long stattype, JSONB data, Long stat) {
        super(GetClientStats.GET_CLIENT_STATS);

        setPeriod(period);
        setStattype(stattype);
        setData(data);
        setStat(stat);
        resetChangedOnNotNull();
    }
}
