/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndValue;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetLogMessagesByContextAndValueRecord extends TableRecordImpl<GetLogMessagesByContextAndValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_value.message</code>.
     */
    public GetLogMessagesByContextAndValueRecord setMessage(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_value.message</code>.
     */
    public String getMessage() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_value.action</code>.
     */
    public GetLogMessagesByContextAndValueRecord setAction(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_value.action</code>.
     */
    public String getAction() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_value.log_time</code>.
     */
    public GetLogMessagesByContextAndValueRecord setLogTime(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_value.log_time</code>.
     */
    public Long getLogTime() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_value.context_values</code>.
     */
    public GetLogMessagesByContextAndValueRecord setContextValues(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_value.context_values</code>.
     */
    public String getContextValues() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetLogMessagesByContextAndValueRecord
     */
    public GetLogMessagesByContextAndValueRecord() {
        super(GetLogMessagesByContextAndValue.GET_LOG_MESSAGES_BY_CONTEXT_AND_VALUE);
    }

    /**
     * Create a detached, initialised GetLogMessagesByContextAndValueRecord
     */
    public GetLogMessagesByContextAndValueRecord(String message, String action, Long logTime, String contextValues) {
        super(GetLogMessagesByContextAndValue.GET_LOG_MESSAGES_BY_CONTEXT_AND_VALUE);

        setMessage(message);
        setAction(action);
        setLogTime(logTime);
        setContextValues(contextValues);
        resetChangedOnNotNull();
    }
}
