/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GetLogMessagesByContextAndAction;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetLogMessagesByContextAndActionRecord extends TableRecordImpl<GetLogMessagesByContextAndActionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_action.message</code>.
     */
    public GetLogMessagesByContextAndActionRecord setMessage(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_action.message</code>.
     */
    public String getMessage() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_action.action</code>.
     */
    public GetLogMessagesByContextAndActionRecord setAction(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_action.action</code>.
     */
    public String getAction() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_action.log_time</code>.
     */
    public GetLogMessagesByContextAndActionRecord setLogTime(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_action.log_time</code>.
     */
    public Long getLogTime() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>public.get_log_messages_by_context_and_action.context_values</code>.
     */
    public GetLogMessagesByContextAndActionRecord setContextValues(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_log_messages_by_context_and_action.context_values</code>.
     */
    public String getContextValues() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetLogMessagesByContextAndActionRecord
     */
    public GetLogMessagesByContextAndActionRecord() {
        super(GetLogMessagesByContextAndAction.GET_LOG_MESSAGES_BY_CONTEXT_AND_ACTION);
    }

    /**
     * Create a detached, initialised GetLogMessagesByContextAndActionRecord
     */
    public GetLogMessagesByContextAndActionRecord(String message, String action, Long logTime, String contextValues) {
        super(GetLogMessagesByContextAndAction.GET_LOG_MESSAGES_BY_CONTEXT_AND_ACTION);

        setMessage(message);
        setAction(action);
        setLogTime(logTime);
        setContextValues(contextValues);
        resetChangedOnNotNull();
    }
}
