/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GetTotalAchievementCompletions;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTotalAchievementCompletionsRecord extends TableRecordImpl<GetTotalAchievementCompletionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.get_total_achievement_completions.namespace</code>.
     */
    public GetTotalAchievementCompletionsRecord setNamespace(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_total_achievement_completions.namespace</code>.
     */
    public String getNamespace() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.get_total_achievement_completions.keyname</code>.
     */
    public GetTotalAchievementCompletionsRecord setKeyname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_total_achievement_completions.keyname</code>.
     */
    public String getKeyname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.get_total_achievement_completions.total</code>.
     */
    public GetTotalAchievementCompletionsRecord setTotal(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.get_total_achievement_completions.total</code>.
     */
    public Long getTotal() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.get_total_achievement_completions.season</code>.
     */
    public GetTotalAchievementCompletionsRecord setSeason(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.get_total_achievement_completions.season</code>.
     */
    public Integer getSeason() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.get_total_achievement_completions.realm</code>.
     */
    public GetTotalAchievementCompletionsRecord setRealm(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.get_total_achievement_completions.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetTotalAchievementCompletionsRecord
     */
    public GetTotalAchievementCompletionsRecord() {
        super(GetTotalAchievementCompletions.GET_TOTAL_ACHIEVEMENT_COMPLETIONS);
    }

    /**
     * Create a detached, initialised GetTotalAchievementCompletionsRecord
     */
    public GetTotalAchievementCompletionsRecord(String namespace, String keyname, Long total, Integer season, Integer realm) {
        super(GetTotalAchievementCompletions.GET_TOTAL_ACHIEVEMENT_COMPLETIONS);

        setNamespace(namespace);
        setKeyname(keyname);
        setTotal(total);
        setSeason(season);
        setRealm(realm);
        resetChangedOnNotNull();
    }
}
