/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.GetTopKills;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopKillsRecord extends TableRecordImpl<GetTopKillsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_top_kills.client</code>.
     */
    public GetTopKillsRecord setClient(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_top_kills.client</code>.
     */
    public String getClient() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.get_top_kills.kills</code>.
     */
    public GetTopKillsRecord setKills(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_top_kills.kills</code>.
     */
    public Long getKills() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetTopKillsRecord
     */
    public GetTopKillsRecord() {
        super(GetTopKills.GET_TOP_KILLS);
    }

    /**
     * Create a detached, initialised GetTopKillsRecord
     */
    public GetTopKillsRecord(String client, Long kills) {
        super(GetTopKills.GET_TOP_KILLS);

        setClient(client);
        setKills(kills);
        resetChangedOnNotNull();
    }
}
