/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.Logs;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LogsRecord extends UpdatableRecordImpl<LogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.logs.id</code>.
     */
    public LogsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.logs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.logs.realm</code>.
     */
    public LogsRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.logs.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.logs.level</code>.
     */
    public LogsRecord setLevel(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.logs.level</code>.
     */
    public String getLevel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.logs.action</code>.
     */
    public LogsRecord setAction(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.logs.action</code>.
     */
    public String getAction() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.logs.message</code>.
     */
    public LogsRecord setMessage(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.logs.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.logs.log_time</code>.
     */
    public LogsRecord setLogTime(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.logs.log_time</code>.
     */
    public Long getLogTime() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogsRecord
     */
    public LogsRecord() {
        super(Logs.LOGS);
    }

    /**
     * Create a detached, initialised LogsRecord
     */
    public LogsRecord(Long id, Integer realm, String level, String action, String message, Long logTime) {
        super(Logs.LOGS);

        setId(id);
        setRealm(realm);
        setLevel(level);
        setAction(action);
        setMessage(message);
        setLogTime(logTime);
        resetChangedOnNotNull();
    }
}
