/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.LogsContext;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LogsContextRecord extends TableRecordImpl<LogsContextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.logs_context.log_id</code>.
     */
    public LogsContextRecord setLogId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.logs_context.log_id</code>.
     */
    public Long getLogId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.logs_context.realm</code>.
     */
    public LogsContextRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.logs_context.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.logs_context.context</code>.
     */
    public LogsContextRecord setContext(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.logs_context.context</code>.
     */
    public String getContext() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.logs_context.value</code>.
     */
    public LogsContextRecord setValue(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.logs_context.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogsContextRecord
     */
    public LogsContextRecord() {
        super(LogsContext.LOGS_CONTEXT);
    }

    /**
     * Create a detached, initialised LogsContextRecord
     */
    public LogsContextRecord(Long logId, Integer realm, String context, String value) {
        super(LogsContext.LOGS_CONTEXT);

        setLogId(logId);
        setRealm(realm);
        setContext(context);
        setValue(value);
        resetChangedOnNotNull();
    }
}
