/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.OfflineMessages;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OfflineMessagesRecord extends UpdatableRecordImpl<OfflineMessagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.offline_messages.id</code>.
     */
    public OfflineMessagesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.offline_messages.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.offline_messages.client</code>.
     */
    public OfflineMessagesRecord setClient(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.offline_messages.client</code>.
     */
    public Long getClient() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.offline_messages.time_sent</code>.
     */
    public OfflineMessagesRecord setTimeSent(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.offline_messages.time_sent</code>.
     */
    public Long getTimeSent() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.offline_messages.action</code>.
     */
    public OfflineMessagesRecord setAction(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.offline_messages.action</code>.
     */
    public String getAction() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.offline_messages.message</code>.
     */
    public OfflineMessagesRecord setMessage(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.offline_messages.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OfflineMessagesRecord
     */
    public OfflineMessagesRecord() {
        super(OfflineMessages.OFFLINE_MESSAGES);
    }

    /**
     * Create a detached, initialised OfflineMessagesRecord
     */
    public OfflineMessagesRecord(Integer id, Long client, Long timeSent, String action, String message) {
        super(OfflineMessages.OFFLINE_MESSAGES);

        setId(id);
        setClient(client);
        setTimeSent(timeSent);
        setAction(action);
        setMessage(message);
        resetChangedOnNotNull();
    }
}
