/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.PeriodMeta;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PeriodMetaRecord extends UpdatableRecordImpl<PeriodMetaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.period_meta.id</code>.
     */
    public PeriodMetaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.period_meta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.period_meta.period</code>.
     */
    public PeriodMetaRecord setPeriod(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.period_meta.period</code>.
     */
    public String getPeriod() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.period_meta.start</code>.
     */
    public PeriodMetaRecord setStart(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.period_meta.start</code>.
     */
    public LocalDate getStart() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeriodMetaRecord
     */
    public PeriodMetaRecord() {
        super(PeriodMeta.PERIOD_META);
    }

    /**
     * Create a detached, initialised PeriodMetaRecord
     */
    public PeriodMetaRecord(Integer id, String period, LocalDate start) {
        super(PeriodMeta.PERIOD_META);

        setId(id);
        setPeriod(period);
        setStart(start);
        resetChangedOnNotNull();
    }
}
