/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.Seasons;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeasonsRecord extends UpdatableRecordImpl<SeasonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.seasons.id</code>.
     */
    public SeasonsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.seasons.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.seasons.start</code>.
     */
    public SeasonsRecord setStart(LocalDate value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.seasons.start</code>.
     */
    public LocalDate getStart() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.seasons.name</code>.
     */
    public SeasonsRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.seasons.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeasonsRecord
     */
    public SeasonsRecord() {
        super(Seasons.SEASONS);
    }

    /**
     * Create a detached, initialised SeasonsRecord
     */
    public SeasonsRecord(Integer id, LocalDate start, String name) {
        super(Seasons.SEASONS);

        setId(id);
        setStart(start);
        setName(name);
        resetChangedOnNotNull();
    }
}
