/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.core.database.jooq.tables.records;


import me.mykindos.betterpvp.core.database.jooq.tables.Uuiditems;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UuiditemsRecord extends UpdatableRecordImpl<UuiditemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.uuiditems.uuid</code>.
     */
    public UuiditemsRecord setUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.uuiditems.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.uuiditems.realm</code>.
     */
    public UuiditemsRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.uuiditems.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.uuiditems.namespace</code>.
     */
    public UuiditemsRecord setNamespace(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.uuiditems.namespace</code>.
     */
    public String getNamespace() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.uuiditems.keyname</code>.
     */
    public UuiditemsRecord setKeyname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.uuiditems.keyname</code>.
     */
    public String getKeyname() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UuiditemsRecord
     */
    public UuiditemsRecord() {
        super(Uuiditems.UUIDITEMS);
    }

    /**
     * Create a detached, initialised UuiditemsRecord
     */
    public UuiditemsRecord(String uuid, Integer realm, String namespace, String keyname) {
        super(Uuiditems.UUIDITEMS);

        setUuid(uuid);
        setRealm(realm);
        setNamespace(namespace);
        setKeyname(keyname);
        resetChangedOnNotNull();
    }
}
