/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables;


import me.mykindos.betterpvp.clans.database.jooq.Indexes;
import me.mykindos.betterpvp.clans.database.jooq.Keys;
import me.mykindos.betterpvp.clans.database.jooq.Public;
import me.mykindos.betterpvp.clans.database.jooq.tables.Clans.ClansPath;
import me.mykindos.betterpvp.clans.database.jooq.tables.records.ClanXpContributionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanXpContributions extends TableImpl<ClanXpContributionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clan_xp_contributions</code>
     */
    public static final ClanXpContributions CLAN_XP_CONTRIBUTIONS = new ClanXpContributions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClanXpContributionsRecord> getRecordType() {
        return ClanXpContributionsRecord.class;
    }

    /**
     * The column <code>public.clan_xp_contributions.clan</code>.
     */
    public final TableField<ClanXpContributionsRecord, Long> CLAN = createField(DSL.name("clan"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.clan_xp_contributions.member</code>.
     */
    public final TableField<ClanXpContributionsRecord, String> MEMBER = createField(DSL.name("member"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.clan_xp_contributions.contribution</code>.
     */
    public final TableField<ClanXpContributionsRecord, Double> CONTRIBUTION = createField(DSL.name("contribution"), SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)), this, "");

    private ClanXpContributions(Name alias, Table<ClanXpContributionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClanXpContributions(Name alias, Table<ClanXpContributionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clan_xp_contributions</code> table
     * reference
     */
    public ClanXpContributions(String alias) {
        this(DSL.name(alias), CLAN_XP_CONTRIBUTIONS);
    }

    /**
     * Create an aliased <code>public.clan_xp_contributions</code> table
     * reference
     */
    public ClanXpContributions(Name alias) {
        this(alias, CLAN_XP_CONTRIBUTIONS);
    }

    /**
     * Create a <code>public.clan_xp_contributions</code> table reference
     */
    public ClanXpContributions() {
        this(DSL.name("clan_xp_contributions"), null);
    }

    public <O extends Record> ClanXpContributions(Table<O> path, ForeignKey<O, ClanXpContributionsRecord> childPath, InverseForeignKey<O, ClanXpContributionsRecord> parentPath) {
        super(path, childPath, parentPath, CLAN_XP_CONTRIBUTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClanXpContributionsPath extends ClanXpContributions implements Path<ClanXpContributionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClanXpContributionsPath(Table<O> path, ForeignKey<O, ClanXpContributionsRecord> childPath, InverseForeignKey<O, ClanXpContributionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClanXpContributionsPath(Name alias, Table<ClanXpContributionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClanXpContributionsPath as(String alias) {
            return new ClanXpContributionsPath(DSL.name(alias), this);
        }

        @Override
        public ClanXpContributionsPath as(Name alias) {
            return new ClanXpContributionsPath(alias, this);
        }

        @Override
        public ClanXpContributionsPath as(Table<?> alias) {
            return new ClanXpContributionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLAN_XP_CONTRIBUTIONS_CLAN);
    }

    @Override
    public UniqueKey<ClanXpContributionsRecord> getPrimaryKey() {
        return Keys.CLAN_XP_CONTRIBUTIONS_PKEY;
    }

    @Override
    public List<ForeignKey<ClanXpContributionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLAN_XP_CONTRIBUTIONS__CLAN_XP_CONTRIBUTIONS_CLAN_FKEY);
    }

    private transient ClansPath _clans;

    /**
     * Get the implicit join path to the <code>public.clans</code> table.
     */
    public ClansPath clans() {
        if (_clans == null)
            _clans = new ClansPath(this, Keys.CLAN_XP_CONTRIBUTIONS__CLAN_XP_CONTRIBUTIONS_CLAN_FKEY, null);

        return _clans;
    }

    @Override
    public ClanXpContributions as(String alias) {
        return new ClanXpContributions(DSL.name(alias), this);
    }

    @Override
    public ClanXpContributions as(Name alias) {
        return new ClanXpContributions(alias, this);
    }

    @Override
    public ClanXpContributions as(Table<?> alias) {
        return new ClanXpContributions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanXpContributions rename(String name) {
        return new ClanXpContributions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanXpContributions rename(Name name) {
        return new ClanXpContributions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanXpContributions rename(Table<?> name) {
        return new ClanXpContributions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanXpContributions where(Condition condition) {
        return new ClanXpContributions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanXpContributions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanXpContributions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanXpContributions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanXpContributions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanXpContributions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanXpContributions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanXpContributions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanXpContributions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanXpContributions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
