/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.clans.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import me.mykindos.betterpvp.clans.database.jooq.Keys;
import me.mykindos.betterpvp.clans.database.jooq.Public;
import me.mykindos.betterpvp.clans.database.jooq.tables.Clans.ClansPath;
import me.mykindos.betterpvp.clans.database.jooq.tables.records.ClanEnemiesRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanEnemies extends TableImpl<ClanEnemiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clan_enemies</code>
     */
    public static final ClanEnemies CLAN_ENEMIES = new ClanEnemies();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClanEnemiesRecord> getRecordType() {
        return ClanEnemiesRecord.class;
    }

    /**
     * The column <code>public.clan_enemies.id</code>.
     */
    public final TableField<ClanEnemiesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.clan_enemies.clan</code>.
     */
    public final TableField<ClanEnemiesRecord, Long> CLAN = createField(DSL.name("clan"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.clan_enemies.enemy_clan</code>.
     */
    public final TableField<ClanEnemiesRecord, Long> ENEMY_CLAN = createField(DSL.name("enemy_clan"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.clan_enemies.dominance</code>.
     */
    public final TableField<ClanEnemiesRecord, Integer> DOMINANCE = createField(DSL.name("dominance"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private ClanEnemies(Name alias, Table<ClanEnemiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClanEnemies(Name alias, Table<ClanEnemiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clan_enemies</code> table reference
     */
    public ClanEnemies(String alias) {
        this(DSL.name(alias), CLAN_ENEMIES);
    }

    /**
     * Create an aliased <code>public.clan_enemies</code> table reference
     */
    public ClanEnemies(Name alias) {
        this(alias, CLAN_ENEMIES);
    }

    /**
     * Create a <code>public.clan_enemies</code> table reference
     */
    public ClanEnemies() {
        this(DSL.name("clan_enemies"), null);
    }

    public <O extends Record> ClanEnemies(Table<O> path, ForeignKey<O, ClanEnemiesRecord> childPath, InverseForeignKey<O, ClanEnemiesRecord> parentPath) {
        super(path, childPath, parentPath, CLAN_ENEMIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClanEnemiesPath extends ClanEnemies implements Path<ClanEnemiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClanEnemiesPath(Table<O> path, ForeignKey<O, ClanEnemiesRecord> childPath, InverseForeignKey<O, ClanEnemiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClanEnemiesPath(Name alias, Table<ClanEnemiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClanEnemiesPath as(String alias) {
            return new ClanEnemiesPath(DSL.name(alias), this);
        }

        @Override
        public ClanEnemiesPath as(Name alias) {
            return new ClanEnemiesPath(alias, this);
        }

        @Override
        public ClanEnemiesPath as(Table<?> alias) {
            return new ClanEnemiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ClanEnemiesRecord, Integer> getIdentity() {
        return (Identity<ClanEnemiesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClanEnemiesRecord> getPrimaryKey() {
        return Keys.CLAN_ENEMIES_PKEY;
    }

    @Override
    public List<UniqueKey<ClanEnemiesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CLAN_ENEMIES_CLAN_ENEMY_CLAN_KEY);
    }

    @Override
    public List<ForeignKey<ClanEnemiesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLAN_ENEMIES__CLAN_ENEMIES_CLAN_FKEY, Keys.CLAN_ENEMIES__CLAN_ENEMIES_ENEMY_CLAN_FKEY);
    }

    private transient ClansPath _clanEnemiesClanFkey;

    /**
     * Get the implicit join path to the <code>public.clans</code> table, via
     * the <code>clan_enemies_clan_fkey</code> key.
     */
    public ClansPath clanEnemiesClanFkey() {
        if (_clanEnemiesClanFkey == null)
            _clanEnemiesClanFkey = new ClansPath(this, Keys.CLAN_ENEMIES__CLAN_ENEMIES_CLAN_FKEY, null);

        return _clanEnemiesClanFkey;
    }

    private transient ClansPath _clanEnemiesEnemyClanFkey;

    /**
     * Get the implicit join path to the <code>public.clans</code> table, via
     * the <code>clan_enemies_enemy_clan_fkey</code> key.
     */
    public ClansPath clanEnemiesEnemyClanFkey() {
        if (_clanEnemiesEnemyClanFkey == null)
            _clanEnemiesEnemyClanFkey = new ClansPath(this, Keys.CLAN_ENEMIES__CLAN_ENEMIES_ENEMY_CLAN_FKEY, null);

        return _clanEnemiesEnemyClanFkey;
    }

    @Override
    public ClanEnemies as(String alias) {
        return new ClanEnemies(DSL.name(alias), this);
    }

    @Override
    public ClanEnemies as(Name alias) {
        return new ClanEnemies(alias, this);
    }

    @Override
    public ClanEnemies as(Table<?> alias) {
        return new ClanEnemies(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanEnemies rename(String name) {
        return new ClanEnemies(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanEnemies rename(Name name) {
        return new ClanEnemies(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanEnemies rename(Table<?> name) {
        return new ClanEnemies(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanEnemies where(Condition condition) {
        return new ClanEnemies(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanEnemies where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanEnemies where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanEnemies where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanEnemies where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanEnemies where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanEnemies where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanEnemies where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanEnemies whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanEnemies whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
