# Sets the permissions for the following BPvP Ranks. This is bukkit permissions
# BPvP Legacy commands use these to hide legacy commands from players
# BPvP specific command permissions can be set in `commands.yml`

PLAYER:
  - bpvp.player
YOUTUBE:
  - bpvp.youtube
HELPER:
  - bpvp.helper
TRIAL_MOD:
  - bpvp.trial_mod
MODERATOR:
  - bpvp.moderator
MINEPLEX:
  - bpvp.mineplex
ADMIN:
  - bpvp.admin
DEVELOPER:
  - bpvp.developer
