skills:
  knight:
    swordsmanship:
      enabled: true
      timeBetweenCharges: 2.0
      timeOutOfCombat: 2.5
      damagePerCharge: 1.0
      maxCharges: 3
    bullscharge:
      enabled: true
      cooldown: 14.0
      speedDuration: 5.0
      speedStrength: 3
      slowDuration: 3.0
      slownessStrength: 3
    magneticaxe:
      enabled: true
      cooldown: 5.0
      damage: 5.0
      duration: 10.0
      hitboxSize: 0.4
      xSize: 0.75
      ySize: 0.75
      zSize: 0.75
      magnitude: 5.0
      gravity: 1.0
      yawOffset: 90.0
      rotations: 20
      dragConstant: 0.2
      initialAngle: 15.0
      blocksPerSecond: 30.0
      maxVelocity: 5.0
    sacrifice:
      enabled: true
      percentage: 0.24
    cleave:
      enabled: true
      distance: 3.0
      percentageOfDamage: 0.75
      maxEnemiesHit: 5
    vengeance:
      enabled: true
      damage: 1.0
      maxDamage: 2.0
      expirationTime: 6.0
    hiltsmash:
      enabled: true
      cooldown: 15.0
      damage: 8.0
      duration: 1.2
      slowStrength: 3
      hitDistance: 4.0
    thorns:
      enabled: false
      internalCooldown: 2.0
      damage: 0.8
    ride:
      enabled: false
      cooldown: 30.0
      lifespan: 2.0
    holdposition:
      enabled: true
      cooldown: 25.0
      duration: 4.0
      slownessStrength: 3
      resistanceStrength: 2
    fortitude:
      enabled: true
      healRate: 1.0
      maxHeal: 4.0
      healInterval: 1.5
    riposte:
      enabled: true
      cooldown: 12.0
      duration: 1.5
      bonusDamageDuration: 2.0
      bonusDamage: 6.0
    shieldsmash:
      enabled: true
      cooldown: 10.0
      multiplier: 1.8
    deflection:
      enabled: true
      timeBetweenCharges: 2.0
      timeOutOfCombat: 2.0
      maxCharges: 3
      damageReduction: 1.0
    defensivestance:
      enabled: true
      cooldown: 1.5
      energy: 32
      damage: 2.0
      damageReduction: 1.0
      blocksMelee: true
      blocksArrow: false
    unstoppableforce:
      enabled: true
      energy: 40
      damage: 4.0
      cooldown: 12.0
      hitboxExpansion: 0.3
  mage:
    immolate:
      enabled: true
      energy: 28
      energyStartCost: 10.0
      fireTickDuration: 4.0
      fireTrailDuration: 2.0
      speedStrength: 1
      strengthLevel: 1
      vulnerabilityStrength: 1
    iceprison:
      enabled: true
      cooldown: 25.0
      sphereSize: 4
      duration: 7.0
      speed: 1.5
      variance: 0.5
    nullblade:
      enabled: true
      energySiphoned: 7.0
    defensiveaura:
      enabled: true
      cooldown: 12.5
      duration: 10.0
      radius: 6.0
      healthBoostStrength: 1
    moltenshield:
      enabled: false
    magmablade:
      enabled: true
      damage: 2.0
    fireblast:
      enabled: true
      cooldown: 12.0
      fallDamageLimit: 8.0
      speed: 0.2
      damage: 2.0
      fireDuration: 2.0
      radius: 4.0
      velocityMultiplier: 2.0
      yAdd: 0.4
      yMax: 0.8
      groundBoost: true
    inferno:
      enabled: true
      cooldown: 4.0
      energy: 19
      fireDuration: 3.0
      damage: 1.0
      charge: 100.0
      numFlames: 7
    glacialblade:
      enabled: true
      cooldown: 1.5
      damage: 1.0
    lightningorb:
      enabled: true
      cooldown: 12.0
      radiusDistance: 4.0
      slowDuration: 4.0
      slowStrength: 2
      shockDuration: 2.0
      damage: 7.0
      velocityStrength: 3.0/bu
      delay: 60.0
    arcticarmour:
      enabled: true
      energy: 26
      energyStartCost: 10.0
      radius: 6
      duration: 2.0
      resistanceStrength: 1
      slownessStrength: 1
      slowDuration: 2.0
      canUseInLiquid: true
    blizzard:
      enabled: true
      energy: 50
      slowDuration: 2.0
      slowStrength: 3
      pushForwardStrength: 0.3
      pushUpwardStrength: 0.15
    staticlazer:
      enabled: false
      cooldown: 10.0
      energy: 25
      charge: 40.0
      damage: 2.0
      range: 15.0
      collisionRadius: 1.8
      explosionRadius: 3.5
    swarm:
      enabled: false
      energy: 85
      batLifespan: 2.0
      batDamage: 1.0
    void:
      enabled: true
      energy: 28
      energyStartCost: 10.0
      damageReduction: 3.0
      energyReduction: 2.5
      slownessStrength: 3
    pestilence:
      enabled: true
      cooldown: 16.0
      energy: 20
      poisonDuration: 6.0
      poisonLevel: 2
      speed: 2.0
      radius: 8.0
      hitboxSize: 0.7
      expirySeconds: 2.0
    rupture:
      enabled: true
      cooldown: 12.0
      damage: 8.0
      slowDuration: 1.5
      slowStrength: 3
    fissure:
      enabled: false
      cooldown: 12.0
      fissureDistance: 14
      fissureExpireDuration: 10.0
      extraDamagePerBlock: 0.6
      effectDuration: 1.0
      slownessLevel: 2
      fissureForbiddenBlocks:
        - TNT
        - ENCHANTING_TABLE
    rootingaxe:
      enabled: true
      cooldown: 8.0
      duration: 2.0
    holylight:
      enabled: true
      radius: 8.0
      duration: 7.0
      regenerationStrength: 1
  ranger:
    stormsphere:
      enabled: false
      cooldown: 20.0
      radius: 5.0
      duration: 4.0
      burstDuration: 1.0
    agility:
      enabled: true
      cooldown: 20.0
      duration: 3.0
      damageReduction: 0.6
      speedStrength: 3
      missedSwings: 1.0
    windburst:
      enabled: true
      cooldown: 18.0
      damage: 2.0
      radius: 4.0
      velocity: 1.0
      selfVelocity: 1.0
      particleSpeed: 0.0
      burstDuration: 5
      yAdd: 0.6
      yMax: 0.8
      yAddSelf: 0.8
      yMaxSelf: 0.8
      fallDamageLimit: 20.0
      ySetSelf: 1.0
      ySet: 0.0
    tri-shot:
      enabled: true
      cooldown: 15.0
      numTridents: 3
      damage: 3.0
      tridentDelay: 0.2
    precision:
      enabled: true
      damage: 0.5
    kinetics:
      enabled: true
      damageResetTime: 4.0
      storedVelocityCount: 3
      fallDamageLimit: 4.0
    vitalityspores:
      enabled: true
      maxSporeCharges: 2
      sporeRemovalTime: 5.0
      healing: 1.5
    bioticquiver:
      enabled: true
      cooldown: 2.0
      friendlyHeal: 1.5
      enemyDebuffDuration: 2.0
    explosivearrow:
      enabled: true
      cooldown: 16.0
      damage: 3.0
      velocityMultiplier: 1.5
      radius: 4.0
      groundBoost: true
      yAdd: 0.8
      yMax: 1.0
    heavyarrows:
      enabled: false
      energy: 19
      pushBack: 1.0
    barbedarrows:
      enabled: true
      damage: 1.0
      damageResetTime: 2.0
      slownessStrength: 1
      slowDuration: 1.0
    tethershot:
      enabled: true
      cooldown: 18.0
      duration: 2.0
      radius: 7.0
      escapeDistance: 2.0
      damage: 5.0
      slowDuration: 4.0
    sharpshooter:
      enabled: true
      duration: 5.0
      maxConsecutiveHits: 5
      damage: 1.0
    wolfsfury:
      enabled: true
      cooldown: 25.0
      duration: 5.0
      missedSwings: 2
      strengthLevel: 2
    wolfspounce:
      enabled: true
      cooldown: 8.0
      charge: 150.0
      damage: 5.0
      slowDuration: 3.0
      slowStrength: 2
    huntersthrill:
      enabled: true
      maxTimeBetweenShots: 8.0
      duration: 6.0
      maxConsecutiveHits: 4
    barrage:
      enabled: false
      charge: 40.0
      arrowDamage: 1.0
      numArrows: 3
      spread: 3.0
    disengage:
      enabled: true
      cooldown: 14.0
      slowDuration: 2.0
      channelDuration: 1.0
      slowStrength: 4
    napalmarrow:
      enabled: true
      cooldown: 20.0
      burnDuration: 3.0
      damage: 1.0
      duration: 10.0
      velocityMultiplier: 0.4
      yComponentVelocityMultiplier: 1.0
      damageDelay: 300
      numFlames: 75
    bullseye:
      enabled: false
      cooldown: 9.0
      bonusCurveDistance: 2.5
      bonusDamage: 2.0
      curveDistance: 0.5
    longshot:
      enabled: true
      maxDamage: 13.0
      minDamage: 1.0
      maxDistance: 64.0
      deathMessageThreshold: 32.0
    levitatingshot:
      enabled: false
      cooldown: 14.0
      duration: 1.0
      levitationStrength: 4
    markofthewolf:
      enabled: false
      cooldown: 20.0
      duration: 2.0
      extraDamage: 2.0
      speedStrength: 2
    ropedarrow:
      enabled: true
      cooldown: 8.0
      fallDamageLimit: 8.0
      velocityStrength: 2.0
  brute:
    threateningshout:
      enabled: true
      cooldown: 20.0
      radius: 1.5
      duration: 3.0
      vulnerabilityStrength: 2
      tickDelay: 12
      damage: 5.0
      startDistance: 1.0
      distance: 15
    bloodlust:
      enabled: true
      duration: 5.0
      maxStacks: 3
      health: 4.0
    stampede:
      enabled: true
      durationPerStack: 5.0
      damage: 1.0
      maxSpeedStrength: 3
      knockback: 0.25
    whirlwindsword:
      enabled: true
      cooldown: 20.0
      distance: 6.5
      damage: 4.0
    seismicslam:
      enabled: true
      cooldown: 20.0
      radius: 5.5
      damage: 1.0
      bonusDamagePerTenBlocks: 5.0
    fleshhook:
      enabled: true
      cooldown: 14.0
      damage: 6.0
    takedown:
      enabled: true
      cooldown: 16.0
      damage: 5.0
      duration: 1.0
      slownessStrength: 4
      recoilDamage: 1.5
      velocityStrength: 1.5
      fallDamageLimit: 4.0
    overwhelm:
      enabled: true
      bonusDamage: 0.5
      healthOverTarget: 2.0
      maxDamage: 1.0
    intimidation:
      enabled: true
      radius: 6
      slownessStrength: 1
    adrenaline:
      enabled: true
      speedOneHealth: 0.50
      speedTwoHealth: 0.30
    fortify:
      enabled: false
      reduction: 0.2
    colossus:
      enabled: true
      reduction: 0.15
    blocktoss:
      enabled: true
      cooldown: 10.0
      charge: 100.0
      damage: 4.0
      radius: 3.0
      speed: 1.4
      size: 0.6
      hitBoxSize: 1.0
    cripplingblow:
      enabled: true
      duration: 2.0
      slownessStrength: 1
    battletaunt:
      enabled: false
      cooldown: 0.5
      energy: 15
      radius: 2.0
  warlock:
    leech:
      enabled: true
      cooldown: 25.0
      range: 7.0
      leechedHealth: 0.7
      maximumEnemies: 3
    bloodthirst:
      enabled: true
      healthPercent: 0.3
      speedStrength: 2
    tormentedsoil:
      enabled: true
      cooldown: 30.0
      duration: 7.0
      range: 5.0
      damageIncrease: 0.33
    bloodshed:
      enabled: true
      cooldown: 15.0
      radius: 5.0
      duration: 5.0
      speedStrength: 2
    soulharvest:
      enabled: true
      buffDuration: 2.0
      speedStrength: 2
      regenerationStrength: 2
    soulbonds:
      enabled: true
      energy: 19
      energyStartCost: 10.0
      radius: 5.0
      healCooldown: 2.0
      healSpeed: 0.3
      healMultiplier: 0.25
    frailty:
      enabled: true
      healthPercent: 0.3
      damagePercent: 0.15
    wreath:
      enabled: true
      slowDuration: 2.0
      damage: 4.0
      slowStrength: 2
      maxCharges: 3
      rechargeSeconds: 6.5
    cleanse:
      enabled: false
      cooldown: 15.0
      range: 5.0
      duration: 2.0
    bloodsphere:
      enabled: true
      cooldown: 15.0
      growthPerSecond: 20.0
      expireSeconds: 6.0
      applyRadius: 3.0
      passiveTravelSpeed: 0.8
      applyTravelSpeed: 0.5
      maxDamage: 15.0
      damagePerSecond: 8.0
      impactHealthMultiplier: 0.6
      healthSeconds: 0.5
      mobHealthModifier: 0.5
    grasp:
      enabled: true
      cooldown: 20.0
      distance: 20.0
      damage: 6.0
    bloodbarrier:
      enabled: true
      cooldown: 30.0
      range: 8.0
      duration: 20.0
      damageReduction: 0.3
      numAttacksToReduce: 3
    impotence:
      enabled: true
      radius: 4.0
      decrease: 0.15
      decreasePerPlayer: 0.05
      maxEnemies: 3
    siphon:
      enabled: true
      radius: 6.0
      energySiphoned: 1.0
      speedStrength: 2
      speedDuration: 2.5
      elapsedTimeToProcAbility: 2.0
      healthGainedOnRandomSiphon: 1.0
      randomSiphonHealthGainChance: 0.1
    bloodcompass:
      enabled: false
      cooldown: 13.0
      numLines: 1
      maxDistance: 64.0
      effectDuration: 6
      numPoints: 30
      escapeRadius: 8.0
    clone:
      enabled: true
      cooldown: 18.0
      duration: 3.0
      health: 10.0
      leapStrength: 2.0
      blindnessLevel: 2
      slownessLevel: 1
      effectDuration: 1.0
  global:
    levelfield:
      enabled: true
      radius: 6.0
      maxEnemies: 2
      damage: 1.0
      damageReduced: 1.0
    fastrecovery:
      enabled: true
      percentage: 0.15
    swim:
      enabled: false
      energy: 10
      internalCooldown: 0.35
    resistance:
      enabled: true
      durationReduction: 30.0
    breakfall:
      enabled: true
      damageReduction: 3.0
    tranquility:
      enabled: true
      timeOutOfCombat: 5.0
      regenerationStrength: 1
  assassin:
    toxicarrow:
      enabled: false
      cooldown: 14.0
      duration: 4.0
      poisonStrength: 2
    sever:
      enabled: true
      cooldown: 15.0
      duration: 2.5
      hitDistance: 4.0
    evade:
      enabled: true
      cooldown: 15.0
      duration: 0.7
      forcedDamageDelay: 400
      internalCooldown: 0.6
    concussion:
      enabled: false
      cooldown: 14.0
      duration: 1.5
      concussionStrength: 1
    comboattack:
      enabled: true
      damageIncrement: 0.5
      maxDamageIncrement: 2.0
      duration: 1.5
    markedfordeath:
      enabled: true
      cooldown: 15.0
      duration: 3.0
      vulnerabilityStrength: 2
    shockingstrikes:
      enabled: false
      duration: 1.0
      hitsNeeded: 3
      timeSpan: 1.0
      slownessStrength: 1
    excessiveforce:
      enabled: true
      cooldown: 16.0
      duration: 3.0
    slash:
      enabled: true
      cooldown: 16.0
      damage: 6.0
      distance: 6.0
      cooldownReduction: 4.0
    recall:
      enabled: true
      cooldown: 23.0
      percentHealthRecovered: 0.1
      duration: 5.0
      canUseWhileSlowed: false
    backstab:
      enabled: true
      damage: 2.5
    leap:
      enabled: true
      cooldown: 7.0
      leapStrength: 1.3
      wallKickStrength: 0.9
      wallKickInternalCooldown: 0.5
      wallkickEnergyCost: 40.0
      fallDamageLimit: 8.0
      canUseWhileSlowed: false
    silencingstrikes:
      enabled: false
      hitsNeeded: 3
      timeSpan: 0.8
      duration: 0.8
    smokearrow:
      enabled: true
      cooldown: 20.0
      duration: 3.0
      slownessStrength: 1
    silencingarrow:
      enabled: true
      cooldown: 12.5
      duration: 2.0
    viperstrikes:
      enabled: true
      duration: 3.0
      poisonStrength: 1
    flash:
      enabled: true
      maxCharges: 5
      rechargeSeconds: 6.5
      teleportDistance: 5.0
      canUseWhileSlowed: false
    blink:
      enabled: true
      cooldown: 13.0
      maxTravelDistance: 17
      deblinkTime: 4
    smokebomb:
      enabled: true
      cooldown: 21.0
      duration: 4.0
      blindDuration: 1.75
      blindRadius: 4.0
      allowPickupItems: false
