# For model specific data use the following format:
#   material:model_data
# For all models of a material use the following format:
#   material
# For model specific data with the ability to bypass with a specific perk, use the following format:
#   material:model_data:perk_name
# For all models of a material with the ability to bypass with a specific perk, use the following format:
#   material::perk_name
# If you wish to specify an allowed item count
type-blacklist:
  - music_disc_ward:1
  - stone
  - dirt::+1 Vault Slots

# For all subclasses of a class, use the following format:
#   class:all
# For specific classes, with no subclasses, use the following format:
#   class
# For all subclasses of a class with the ability to bypass with a specific perk, use the following format:
#   class:all:perk_name
# For specific classes, with no subclasses, with the ability to bypass with a specific perk, use the following format:
#   class::perk_name
class-blacklist:
  - me.mykindos.betterpvp.core.combat.weapon.types.LegendaryWeapon:all