package me.mykindos.betterpvp.core.world.logger;

public enum WorldLogAction {
    BLOCK_BREAK,
    BLOCK_PLACE,
    BLOCK_EXPLODE,
    BLOCK_DISPENSE,
    BLOCK_DROP_ITEM,
    BLOCK_PICKUP_ITEM,
    BLOCK_MOVE_ITEM,
    ITEM_DEPSAWN,
    ENTITY_DROP_ITEM,
    ENTITY_PICKUP_ITEM,
    CONTAINER_DEPOSIT_ITEM,
    CONTAINER_WITHDRAW_ITEM,
}
