name: Clans
version: '1.0'
main: me.mykindos.betterpvp.clans.Clans
api-version: '1.21'

dependencies:
  bootstrap:
    Core:
      load: BEFORE
      required: true
      join-classpath: true
    Champions:
      load: BEFORE
      required: false
      join-classpath: true
    Progression:
      load: BEFORE
      required: false
      join-classpath: true
    Shops:
      load: BEFORE
      required: false
      join-classpath: true
  server:
    Core:
      load: BEFORE
      required: true
      join-classpath: true
    Champions:
      load: BEFORE
      required: false
      join-classpath: true
    Progression:
      load: BEFORE
      required: false
      join-classpath: true
    Shops:
      load: BEFORE
      required: false
      join-classpath: true