author: Mykindos
main: me.mykindos.betterpvp.clans.Clans
name: Clans
load: POSTWORLD
version: '1.0'
depend: [Core]
api-version: '1.21'
softdepend:
  - ProtocolLib
  - Progression
  - LibsDisguises
  - ModelEngine
  - Champions