/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables;


import java.util.Collection;

import me.mykindos.betterpvp.champions.database.jooq.Keys;
import me.mykindos.betterpvp.champions.database.jooq.Public;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.ChampionsBuildsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChampionsBuilds extends TableImpl<ChampionsBuildsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.champions_builds</code>
     */
    public static final ChampionsBuilds CHAMPIONS_BUILDS = new ChampionsBuilds();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChampionsBuildsRecord> getRecordType() {
        return ChampionsBuildsRecord.class;
    }

    /**
     * The column <code>public.champions_builds.client</code>.
     */
    public final TableField<ChampionsBuildsRecord, Long> CLIENT = createField(DSL.name("client"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.champions_builds.role</code>.
     */
    public final TableField<ChampionsBuildsRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.champions_builds.id</code>.
     */
    public final TableField<ChampionsBuildsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.champions_builds.sword</code>.
     */
    public final TableField<ChampionsBuildsRecord, String> SWORD = createField(DSL.name("sword"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.champions_builds.axe</code>.
     */
    public final TableField<ChampionsBuildsRecord, String> AXE = createField(DSL.name("axe"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.champions_builds.bow</code>.
     */
    public final TableField<ChampionsBuildsRecord, String> BOW = createField(DSL.name("bow"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.champions_builds.passive_a</code>.
     */
    public final TableField<ChampionsBuildsRecord, String> PASSIVE_A = createField(DSL.name("passive_a"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.champions_builds.passive_b</code>.
     */
    public final TableField<ChampionsBuildsRecord, String> PASSIVE_B = createField(DSL.name("passive_b"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.champions_builds.global</code>.
     */
    public final TableField<ChampionsBuildsRecord, String> GLOBAL = createField(DSL.name("global"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.champions_builds.active</code>.
     */
    public final TableField<ChampionsBuildsRecord, Integer> ACTIVE = createField(DSL.name("active"), SQLDataType.INTEGER, this, "");

    private ChampionsBuilds(Name alias, Table<ChampionsBuildsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChampionsBuilds(Name alias, Table<ChampionsBuildsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.champions_builds</code> table reference
     */
    public ChampionsBuilds(String alias) {
        this(DSL.name(alias), CHAMPIONS_BUILDS);
    }

    /**
     * Create an aliased <code>public.champions_builds</code> table reference
     */
    public ChampionsBuilds(Name alias) {
        this(alias, CHAMPIONS_BUILDS);
    }

    /**
     * Create a <code>public.champions_builds</code> table reference
     */
    public ChampionsBuilds() {
        this(DSL.name("champions_builds"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ChampionsBuildsRecord> getPrimaryKey() {
        return Keys.CHAMPIONS_BUILDS_PKEY;
    }

    @Override
    public ChampionsBuilds as(String alias) {
        return new ChampionsBuilds(DSL.name(alias), this);
    }

    @Override
    public ChampionsBuilds as(Name alias) {
        return new ChampionsBuilds(alias, this);
    }

    @Override
    public ChampionsBuilds as(Table<?> alias) {
        return new ChampionsBuilds(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChampionsBuilds rename(String name) {
        return new ChampionsBuilds(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChampionsBuilds rename(Name name) {
        return new ChampionsBuilds(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChampionsBuilds rename(Table<?> name) {
        return new ChampionsBuilds(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChampionsBuilds where(Condition condition) {
        return new ChampionsBuilds(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChampionsBuilds where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChampionsBuilds where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChampionsBuilds where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChampionsBuilds where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChampionsBuilds where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChampionsBuilds where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChampionsBuilds where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChampionsBuilds whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChampionsBuilds whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
