/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables;


import me.mykindos.betterpvp.champions.database.jooq.Public;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetTopKillstreakByClassRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopKillstreakByClass extends TableImpl<GetTopKillstreakByClassRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.get_top_killstreak_by_class</code>
     */
    public static final GetTopKillstreakByClass GET_TOP_KILLSTREAK_BY_CLASS = new GetTopKillstreakByClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetTopKillstreakByClassRecord> getRecordType() {
        return GetTopKillstreakByClassRecord.class;
    }

    /**
     * The column <code>public.get_top_killstreak_by_class.client</code>.
     */
    public final TableField<GetTopKillstreakByClassRecord, String> CLIENT = createField(DSL.name("client"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.get_top_killstreak_by_class.killstreak</code>.
     */
    public final TableField<GetTopKillstreakByClassRecord, Integer> KILLSTREAK = createField(DSL.name("killstreak"), SQLDataType.INTEGER, this, "");

    private GetTopKillstreakByClass(Name alias, Table<GetTopKillstreakByClassRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.INTEGER),
            DSL.val(null, SQLDataType.VARCHAR)
        });
    }

    private GetTopKillstreakByClass(Name alias, Table<GetTopKillstreakByClassRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private GetTopKillstreakByClass(Name alias, Table<GetTopKillstreakByClassRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.get_top_killstreak_by_class</code> table
     * reference
     */
    public GetTopKillstreakByClass(String alias) {
        this(DSL.name(alias), GET_TOP_KILLSTREAK_BY_CLASS);
    }

    /**
     * Create an aliased <code>public.get_top_killstreak_by_class</code> table
     * reference
     */
    public GetTopKillstreakByClass(Name alias) {
        this(alias, GET_TOP_KILLSTREAK_BY_CLASS);
    }

    /**
     * Create a <code>public.get_top_killstreak_by_class</code> table reference
     */
    public GetTopKillstreakByClass() {
        this(DSL.name("get_top_killstreak_by_class"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public GetTopKillstreakByClass as(String alias) {
        return new GetTopKillstreakByClass(DSL.name(alias), this, parameters);
    }

    @Override
    public GetTopKillstreakByClass as(Name alias) {
        return new GetTopKillstreakByClass(alias, this, parameters);
    }

    @Override
    public GetTopKillstreakByClass as(Table<?> alias) {
        return new GetTopKillstreakByClass(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopKillstreakByClass rename(String name) {
        return new GetTopKillstreakByClass(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopKillstreakByClass rename(Name name) {
        return new GetTopKillstreakByClass(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetTopKillstreakByClass rename(Table<?> name) {
        return new GetTopKillstreakByClass(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetTopKillstreakByClass call(
          Integer realmVar
        , Integer top
        , String classParam
    ) {
        GetTopKillstreakByClass result = new GetTopKillstreakByClass(DSL.name("get_top_killstreak_by_class"), null, new Field[] {
            DSL.val(realmVar, SQLDataType.INTEGER),
            DSL.val(top, SQLDataType.INTEGER),
            DSL.val(classParam, SQLDataType.VARCHAR)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public GetTopKillstreakByClass call(
          Field<Integer> realmVar
        , Field<Integer> top
        , Field<String> classParam
    ) {
        GetTopKillstreakByClass result = new GetTopKillstreakByClass(DSL.name("get_top_killstreak_by_class"), null, new Field[] {
            realmVar,
            top,
            classParam
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
