/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables;


import me.mykindos.betterpvp.champions.database.jooq.Indexes;
import me.mykindos.betterpvp.champions.database.jooq.Keys;
import me.mykindos.betterpvp.champions.database.jooq.Public;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GrafanaRoleMatchupSnapshotRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GrafanaRoleMatchupSnapshot extends TableImpl<GrafanaRoleMatchupSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.grafana_role_matchup_snapshot</code>
     */
    public static final GrafanaRoleMatchupSnapshot GRAFANA_ROLE_MATCHUP_SNAPSHOT = new GrafanaRoleMatchupSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrafanaRoleMatchupSnapshotRecord> getRecordType() {
        return GrafanaRoleMatchupSnapshotRecord.class;
    }

    /**
     * The column <code>public.grafana_role_matchup_snapshot.id</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.grafana_role_matchup_snapshot.realm</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, Integer> REALM = createField(DSL.name("realm"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.grafana_role_matchup_snapshot.captured_at</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, OffsetDateTime> CAPTURED_AT = createField(DSL.name("captured_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.grafana_role_matchup_snapshot.role</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.grafana_role_matchup_snapshot.vs_role</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, String> VS_ROLE = createField(DSL.name("vs_role"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.grafana_role_matchup_snapshot.kills</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, Long> KILLS = createField(DSL.name("kills"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.grafana_role_matchup_snapshot.deaths</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, Long> DEATHS = createField(DSL.name("deaths"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.grafana_role_matchup_snapshot.kdr</code>.
     */
    public final TableField<GrafanaRoleMatchupSnapshotRecord, BigDecimal> KDR = createField(DSL.name("kdr"), SQLDataType.NUMERIC(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    private GrafanaRoleMatchupSnapshot(Name alias, Table<GrafanaRoleMatchupSnapshotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GrafanaRoleMatchupSnapshot(Name alias, Table<GrafanaRoleMatchupSnapshotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.grafana_role_matchup_snapshot</code> table
     * reference
     */
    public GrafanaRoleMatchupSnapshot(String alias) {
        this(DSL.name(alias), GRAFANA_ROLE_MATCHUP_SNAPSHOT);
    }

    /**
     * Create an aliased <code>public.grafana_role_matchup_snapshot</code> table
     * reference
     */
    public GrafanaRoleMatchupSnapshot(Name alias) {
        this(alias, GRAFANA_ROLE_MATCHUP_SNAPSHOT);
    }

    /**
     * Create a <code>public.grafana_role_matchup_snapshot</code> table
     * reference
     */
    public GrafanaRoleMatchupSnapshot() {
        this(DSL.name("grafana_role_matchup_snapshot"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_GRAFANA_ROLE_MATCHUP_REALM_TIME);
    }

    @Override
    public Identity<GrafanaRoleMatchupSnapshotRecord, Long> getIdentity() {
        return (Identity<GrafanaRoleMatchupSnapshotRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GrafanaRoleMatchupSnapshotRecord> getPrimaryKey() {
        return Keys.GRAFANA_ROLE_MATCHUP_SNAPSHOT_PKEY;
    }

    @Override
    public GrafanaRoleMatchupSnapshot as(String alias) {
        return new GrafanaRoleMatchupSnapshot(DSL.name(alias), this);
    }

    @Override
    public GrafanaRoleMatchupSnapshot as(Name alias) {
        return new GrafanaRoleMatchupSnapshot(alias, this);
    }

    @Override
    public GrafanaRoleMatchupSnapshot as(Table<?> alias) {
        return new GrafanaRoleMatchupSnapshot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot rename(String name) {
        return new GrafanaRoleMatchupSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot rename(Name name) {
        return new GrafanaRoleMatchupSnapshot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot rename(Table<?> name) {
        return new GrafanaRoleMatchupSnapshot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot where(Condition condition) {
        return new GrafanaRoleMatchupSnapshot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GrafanaRoleMatchupSnapshot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GrafanaRoleMatchupSnapshot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GrafanaRoleMatchupSnapshot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GrafanaRoleMatchupSnapshot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GrafanaRoleMatchupSnapshot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
