/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.progression.database.jooq;


import me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaught;
import me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaughtByClient;
import me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingCount;
import me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingWeight;
import me.mykindos.betterpvp.progression.database.jooq.tables.GetClientOresMined;
import me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByCount;
import me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByWeight;
import me.mykindos.betterpvp.progression.database.jooq.tables.GetTopMiningByOre;
import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionBuilds;
import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionExp;
import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionFishing;
import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionMining;
import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionProperties;
import me.mykindos.betterpvp.progression.database.jooq.tables.ProgressionWoodcutting;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetBiggestFishCaughtByClientRecord;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetBiggestFishCaughtRecord;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetClientFishingCountRecord;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetClientFishingWeightRecord;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetClientOresMinedRecord;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetTopFishingByCountRecord;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetTopFishingByWeightRecord;
import me.mykindos.betterpvp.progression.database.jooq.tables.records.GetTopMiningByOreRecord;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.get_biggest_fish_caught</code>.
     */
    public static final GetBiggestFishCaught GET_BIGGEST_FISH_CAUGHT = GetBiggestFishCaught.GET_BIGGEST_FISH_CAUGHT;

    /**
     * Call <code>public.get_biggest_fish_caught</code>.
     */
    public static Result<GetBiggestFishCaughtRecord> GET_BIGGEST_FISH_CAUGHT(
          Configuration configuration
        , Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaught.GET_BIGGEST_FISH_CAUGHT.call(
              seasonParam
            , days
            , maxResults
        )).fetch();
    }

    /**
     * Get <code>public.get_biggest_fish_caught</code> as a table.
     */
    public static GetBiggestFishCaught GET_BIGGEST_FISH_CAUGHT(
          Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaught.GET_BIGGEST_FISH_CAUGHT.call(
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * Get <code>public.get_biggest_fish_caught</code> as a table.
     */
    public static GetBiggestFishCaught GET_BIGGEST_FISH_CAUGHT(
          Field<Integer> seasonParam
        , Field<Double> days
        , Field<Integer> maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaught.GET_BIGGEST_FISH_CAUGHT.call(
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * The table <code>public.get_biggest_fish_caught_by_client</code>.
     */
    public static final GetBiggestFishCaughtByClient GET_BIGGEST_FISH_CAUGHT_BY_CLIENT = GetBiggestFishCaughtByClient.GET_BIGGEST_FISH_CAUGHT_BY_CLIENT;

    /**
     * Call <code>public.get_biggest_fish_caught_by_client</code>.
     */
    public static Result<GetBiggestFishCaughtByClientRecord> GET_BIGGEST_FISH_CAUGHT_BY_CLIENT(
          Configuration configuration
        , Long pClientId
        , Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaughtByClient.GET_BIGGEST_FISH_CAUGHT_BY_CLIENT.call(
              pClientId
            , seasonParam
            , days
            , maxResults
        )).fetch();
    }

    /**
     * Get <code>public.get_biggest_fish_caught_by_client</code> as a table.
     */
    public static GetBiggestFishCaughtByClient GET_BIGGEST_FISH_CAUGHT_BY_CLIENT(
          Long pClientId
        , Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaughtByClient.GET_BIGGEST_FISH_CAUGHT_BY_CLIENT.call(
            pClientId,
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * Get <code>public.get_biggest_fish_caught_by_client</code> as a table.
     */
    public static GetBiggestFishCaughtByClient GET_BIGGEST_FISH_CAUGHT_BY_CLIENT(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<Double> days
        , Field<Integer> maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetBiggestFishCaughtByClient.GET_BIGGEST_FISH_CAUGHT_BY_CLIENT.call(
            pClientId,
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * The table <code>public.get_client_fishing_count</code>.
     */
    public static final GetClientFishingCount GET_CLIENT_FISHING_COUNT = GetClientFishingCount.GET_CLIENT_FISHING_COUNT;

    /**
     * Call <code>public.get_client_fishing_count</code>.
     */
    public static Result<GetClientFishingCountRecord> GET_CLIENT_FISHING_COUNT(
          Configuration configuration
        , Long pClientId
        , Integer seasonParam
        , Double days
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingCount.GET_CLIENT_FISHING_COUNT.call(
              pClientId
            , seasonParam
            , days
        )).fetch();
    }

    /**
     * Get <code>public.get_client_fishing_count</code> as a table.
     */
    public static GetClientFishingCount GET_CLIENT_FISHING_COUNT(
          Long pClientId
        , Integer seasonParam
        , Double days
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingCount.GET_CLIENT_FISHING_COUNT.call(
            pClientId,
            seasonParam,
            days
        );
    }

    /**
     * Get <code>public.get_client_fishing_count</code> as a table.
     */
    public static GetClientFishingCount GET_CLIENT_FISHING_COUNT(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<Double> days
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingCount.GET_CLIENT_FISHING_COUNT.call(
            pClientId,
            seasonParam,
            days
        );
    }

    /**
     * The table <code>public.get_client_fishing_weight</code>.
     */
    public static final GetClientFishingWeight GET_CLIENT_FISHING_WEIGHT = GetClientFishingWeight.GET_CLIENT_FISHING_WEIGHT;

    /**
     * Call <code>public.get_client_fishing_weight</code>.
     */
    public static Result<GetClientFishingWeightRecord> GET_CLIENT_FISHING_WEIGHT(
          Configuration configuration
        , Long pClientId
        , Integer seasonParam
        , Double days
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingWeight.GET_CLIENT_FISHING_WEIGHT.call(
              pClientId
            , seasonParam
            , days
        )).fetch();
    }

    /**
     * Get <code>public.get_client_fishing_weight</code> as a table.
     */
    public static GetClientFishingWeight GET_CLIENT_FISHING_WEIGHT(
          Long pClientId
        , Integer seasonParam
        , Double days
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingWeight.GET_CLIENT_FISHING_WEIGHT.call(
            pClientId,
            seasonParam,
            days
        );
    }

    /**
     * Get <code>public.get_client_fishing_weight</code> as a table.
     */
    public static GetClientFishingWeight GET_CLIENT_FISHING_WEIGHT(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<Double> days
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetClientFishingWeight.GET_CLIENT_FISHING_WEIGHT.call(
            pClientId,
            seasonParam,
            days
        );
    }

    /**
     * The table <code>public.get_client_ores_mined</code>.
     */
    public static final GetClientOresMined GET_CLIENT_ORES_MINED = GetClientOresMined.GET_CLIENT_ORES_MINED;

    /**
     * Call <code>public.get_client_ores_mined</code>.
     */
    public static Result<GetClientOresMinedRecord> GET_CLIENT_ORES_MINED(
          Configuration configuration
        , Long pClientId
        , Integer seasonParam
        , String[] blocks
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetClientOresMined.GET_CLIENT_ORES_MINED.call(
              pClientId
            , seasonParam
            , blocks
        )).fetch();
    }

    /**
     * Get <code>public.get_client_ores_mined</code> as a table.
     */
    public static GetClientOresMined GET_CLIENT_ORES_MINED(
          Long pClientId
        , Integer seasonParam
        , String[] blocks
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetClientOresMined.GET_CLIENT_ORES_MINED.call(
            pClientId,
            seasonParam,
            blocks
        );
    }

    /**
     * Get <code>public.get_client_ores_mined</code> as a table.
     */
    public static GetClientOresMined GET_CLIENT_ORES_MINED(
          Field<Long> pClientId
        , Field<Integer> seasonParam
        , Field<String[]> blocks
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetClientOresMined.GET_CLIENT_ORES_MINED.call(
            pClientId,
            seasonParam,
            blocks
        );
    }

    /**
     * The table <code>public.get_top_fishing_by_count</code>.
     */
    public static final GetTopFishingByCount GET_TOP_FISHING_BY_COUNT = GetTopFishingByCount.GET_TOP_FISHING_BY_COUNT;

    /**
     * Call <code>public.get_top_fishing_by_count</code>.
     */
    public static Result<GetTopFishingByCountRecord> GET_TOP_FISHING_BY_COUNT(
          Configuration configuration
        , Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByCount.GET_TOP_FISHING_BY_COUNT.call(
              seasonParam
            , days
            , maxResults
        )).fetch();
    }

    /**
     * Get <code>public.get_top_fishing_by_count</code> as a table.
     */
    public static GetTopFishingByCount GET_TOP_FISHING_BY_COUNT(
          Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByCount.GET_TOP_FISHING_BY_COUNT.call(
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * Get <code>public.get_top_fishing_by_count</code> as a table.
     */
    public static GetTopFishingByCount GET_TOP_FISHING_BY_COUNT(
          Field<Integer> seasonParam
        , Field<Double> days
        , Field<Integer> maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByCount.GET_TOP_FISHING_BY_COUNT.call(
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * The table <code>public.get_top_fishing_by_weight</code>.
     */
    public static final GetTopFishingByWeight GET_TOP_FISHING_BY_WEIGHT = GetTopFishingByWeight.GET_TOP_FISHING_BY_WEIGHT;

    /**
     * Call <code>public.get_top_fishing_by_weight</code>.
     */
    public static Result<GetTopFishingByWeightRecord> GET_TOP_FISHING_BY_WEIGHT(
          Configuration configuration
        , Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByWeight.GET_TOP_FISHING_BY_WEIGHT.call(
              seasonParam
            , days
            , maxResults
        )).fetch();
    }

    /**
     * Get <code>public.get_top_fishing_by_weight</code> as a table.
     */
    public static GetTopFishingByWeight GET_TOP_FISHING_BY_WEIGHT(
          Integer seasonParam
        , Double days
        , Integer maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByWeight.GET_TOP_FISHING_BY_WEIGHT.call(
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * Get <code>public.get_top_fishing_by_weight</code> as a table.
     */
    public static GetTopFishingByWeight GET_TOP_FISHING_BY_WEIGHT(
          Field<Integer> seasonParam
        , Field<Double> days
        , Field<Integer> maxResults
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetTopFishingByWeight.GET_TOP_FISHING_BY_WEIGHT.call(
            seasonParam,
            days,
            maxResults
        );
    }

    /**
     * The table <code>public.get_top_mining_by_ore</code>.
     */
    public static final GetTopMiningByOre GET_TOP_MINING_BY_ORE = GetTopMiningByOre.GET_TOP_MINING_BY_ORE;

    /**
     * Call <code>public.get_top_mining_by_ore</code>.
     */
    public static Result<GetTopMiningByOreRecord> GET_TOP_MINING_BY_ORE(
          Configuration configuration
        , Integer seasonParam
        , Integer maxResults
        , String[] blocks
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.progression.database.jooq.tables.GetTopMiningByOre.GET_TOP_MINING_BY_ORE.call(
              seasonParam
            , maxResults
            , blocks
        )).fetch();
    }

    /**
     * Get <code>public.get_top_mining_by_ore</code> as a table.
     */
    public static GetTopMiningByOre GET_TOP_MINING_BY_ORE(
          Integer seasonParam
        , Integer maxResults
        , String[] blocks
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetTopMiningByOre.GET_TOP_MINING_BY_ORE.call(
            seasonParam,
            maxResults,
            blocks
        );
    }

    /**
     * Get <code>public.get_top_mining_by_ore</code> as a table.
     */
    public static GetTopMiningByOre GET_TOP_MINING_BY_ORE(
          Field<Integer> seasonParam
        , Field<Integer> maxResults
        , Field<String[]> blocks
    ) {
        return me.mykindos.betterpvp.progression.database.jooq.tables.GetTopMiningByOre.GET_TOP_MINING_BY_ORE.call(
            seasonParam,
            maxResults,
            blocks
        );
    }

    /**
     * The table <code>public.progression_builds</code>.
     */
    public static final ProgressionBuilds PROGRESSION_BUILDS = ProgressionBuilds.PROGRESSION_BUILDS;

    /**
     * The table <code>public.progression_exp</code>.
     */
    public static final ProgressionExp PROGRESSION_EXP = ProgressionExp.PROGRESSION_EXP;

    /**
     * The table <code>public.progression_fishing</code>.
     */
    public static final ProgressionFishing PROGRESSION_FISHING = ProgressionFishing.PROGRESSION_FISHING;

    /**
     * The table <code>public.progression_mining</code>.
     */
    public static final ProgressionMining PROGRESSION_MINING = ProgressionMining.PROGRESSION_MINING;

    /**
     * The table <code>public.progression_properties</code>.
     */
    public static final ProgressionProperties PROGRESSION_PROPERTIES = ProgressionProperties.PROGRESSION_PROPERTIES;

    /**
     * The table <code>public.progression_woodcutting</code>.
     */
    public static final ProgressionWoodcutting PROGRESSION_WOODCUTTING = ProgressionWoodcutting.PROGRESSION_WOODCUTTING;
}
