DELETE FROM shopitems;

-- SHOP ITEMS
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (113, 'Farmer', 5, 1, 'minecraft:beetroot_seeds', 7);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (111, 'Farmer', 5, 1, 'minecraft:pumpkin_seeds', 1);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (102, 'Farmer', 20, 10, 'minecraft:melon', 2);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (109, 'Farmer', 3334, 600, 'minecraft:honeycomb', 17);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (112, 'Farmer', 5, 1, 'minecraft:melon_seeds', 3);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (114, 'Farmer', 5, 1, 'minecraft:wheat_seeds', 5);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (106, 'Farmer', 60, 30, 'minecraft:wheat', 4);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (100, 'Farmer', 50, 25, 'minecraft:cocoa_beans', 8);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (104, 'Farmer', 40, 20, 'minecraft:potato', 10);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (108, 'Farmer', 40, 20, 'minecraft:sweet_berries', 13);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (105, 'Farmer', 50, 25, 'minecraft:nether_wart', 12);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (110, 'Farmer', 10000, 5000, 'minecraft:beehive', 15);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (95, 'Resource Merchant', 100000, 50000, 'champions:build_editor', 15);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (64, 'Blacksmith', 300, 0, 'core:bow', 12);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (61, 'Blacksmith', 5000, 0, 'core:power_sword', 0);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (83, 'Resource Merchant', 1000, 250, 'minecraft:emerald', 6);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (85, 'Resource Merchant', 1000, 250, 'minecraft:netherite_ingot', 8);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (81, 'Resource Merchant', 1000, 250, 'minecraft:gold_ingot', 4);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (79, 'Resource Merchant', 1000, 250, 'minecraft:iron_ingot', 2);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (78, 'Resource Merchant', 9000, 2250, 'minecraft:diamond_block', 1);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (84, 'Resource Merchant', 9000, 2250, 'minecraft:emerald_block', 7);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (80, 'Resource Merchant', 9000, 2250, 'minecraft:iron_block', 3);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (82, 'Resource Merchant', 9000, 2250, 'minecraft:gold_block', 5);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (70, 'Blacksmith', 500, 0, 'core:standard_shovel', 10);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (63, 'Blacksmith', 2000, 0, 'core:standard_sword', 7);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (62, 'Blacksmith', 5000, 2500, 'core:booster_sword', 5);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (68, 'Blacksmith', 2000, 500, 'core:power_hoe', 4);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (66, 'Blacksmith', 3000, 750, 'core:power_pickaxe', 2);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (71, 'Blacksmith', 1000, 0, 'core:standard_hoe', 11);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (75, 'Blacksmith', 3000, 750, 'core:standard_axe', 8);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (73, 'Blacksmith', 6000, 3000, 'core:booster_axe', 6);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (69, 'Blacksmith', 2000, 0, 'core:standard_pickaxe', 9);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (67, 'Blacksmith', 1000, 250, 'core:power_shovel', 3);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (65, 'Blacksmith', 12, 0, 'minecraft:arrow', 13);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (72, 'Blacksmith', 6000, 3000, 'core:power_axe', 1);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (77, 'Resource Merchant', 1000, 250, 'minecraft:diamond', 0);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (47, 'Block Merchant', 50, 25, 'minecraft:birch_log', 29);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (26, 'Block Merchant', 20, 5, 'minecraft:cobblestone', 1);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (46, 'Block Merchant', 50, 25, 'minecraft:dark_oak_log', 28);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (27, 'Block Merchant', 5, 2, 'minecraft:dirt', 3);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (38, 'Block Merchant', 100, 20, 'minecraft:gravel', 45);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (44, 'Block Merchant', 50, 25, 'minecraft:jungle_log', 27);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (49, 'Block Merchant', 40, 10, 'minecraft:mossy_cobblestone', 2);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (41, 'Block Merchant', 40, 10, 'minecraft:nether_bricks', 14);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (45, 'Block Merchant', 20, 10, 'minecraft:soul_sand', 46);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (48, 'Block Merchant', 50, 25, 'minecraft:spruce_log', 30);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (115, 'Fisherman', 500, 0, 'core:fishing_rod', 45);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (116, 'Lumberjack', 16, 0, 'core:power_axe', 12);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (117, 'Lumberjack', 12, 0, 'core:booster_axe', 13);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (118, 'Lumberjack', 6, 0, 'core:standard_axe', 14);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (119, 'Lumberjack', 3, 0, 'minecraft:mangrove_propagule', 8);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (120, 'Lumberjack', 3200, 1600, 'progression:compacted_log', 27);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (122, 'Fisherman', 5000, 0, 'progression:speedy_bait', 46);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (99, 'Farmer', 60, 30, 'minecraft:pumpkin', 0);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (25, 'Block Merchant', 40, 10, 'minecraft:stone', 0);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (36, 'Block Merchant', 40, 10, 'minecraft:stone_bricks', 9);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (53, 'Block Merchant', 40, 10, 'minecraft:white_concrete', 8);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (189, 'Block Merchant', 20, 5, 'minecraft:grass_block', 4);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (190, 'Block Merchant', 450, 50, 'minecraft:white_wool', 7);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (40, 'Block Merchant', 20, 5, 'minecraft:podzol', 5);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (37, 'Block Merchant', 40, 10, 'minecraft:polished_blackstone_bricks', 10);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (191, 'Block Merchant', 40, 10, 'minecraft:blackstone', 11);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (192, 'Block Merchant', 40, 10, 'minecraft:mud', 12);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (193, 'Block Merchant', 30, 15, 'minecraft:calcite', 13);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (39, 'Block Merchant', 2000, 1000, 'minecraft:sponge', 16);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (28, 'Block Merchant', 40, 10, 'minecraft:deepslate', 18);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (29, 'Block Merchant', 40, 10, 'minecraft:cobbled_deepslate', 19);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (195, 'Block Merchant', 40, 10, 'minecraft:basalt', 20);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (128, 'Block Merchant', 40, 10, 'minecraft:mud_bricks', 21);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (129, 'Block Merchant', 40, 10, 'minecraft:end_stone_bricks', 22);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (51, 'Block Merchant', 40, 10, 'minecraft:purpur_block', 23);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (30, 'Block Merchant', 20, 2, 'minecraft:snow_block', 26);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (153, 'Lumberjack', 100, 10, 'minecraft:oak_sapling', 37);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (154, 'Lumberjack', 100, 10, 'minecraft:spruce_sapling', 38);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (155, 'Lumberjack', 100, 10, 'minecraft:birch_sapling', 39);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (156, 'Lumberjack', 100, 10, 'minecraft:jungle_sapling', 40);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (130, 'Farmer', 60, 30, 'minecraft:glow_berries', 9);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (107, 'Farmer', 60, 30, 'minecraft:beetroot', 6);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (103, 'Farmer', 40, 20, 'minecraft:carrot', 14);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (101, 'Farmer', 10, 5, 'minecraft:sugar_cane', 11);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (86, 'Resource Merchant', 9000, 2250, 'minecraft:netherite_block', 9);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (89, 'Resource Merchant', 200, 100, 'minecraft:redstone', 13);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (90, 'Resource Merchant', 1800, 900, 'minecraft:redstone_block', 14);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (94, 'Resource Merchant', 300, 150, 'core:coal', 10);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (87, 'Resource Merchant', 1000, 250, 'minecraft:leather', 11);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (121, 'Resource Merchant', 50000, 0, 'core:anvil', 16);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (160, 'Resource Merchant', 10, 1, 'minecraft:prismarine_shard', 20);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (92, 'Resource Merchant', 1000, 500, 'minecraft:bone', 21);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (91, 'Resource Merchant', 1000, 500, 'minecraft:quartz', 19);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (96, 'Resource Merchant', 100000, 100000, 'minecraft:music_disc_wait', 24);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (98, 'Resource Merchant', 1000000, 1000000, 'minecraft:music_disc_pigstep', 25);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (97, 'Resource Merchant', 50000, 50000, 'minecraft:music_disc_13', 23);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (126, 'Blacksmith', 1000, 500, 'champions:rabbit_stew', 16);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (127, 'Blacksmith', 1000, 500, 'champions:suspicious_stew', 15);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (125, 'Blacksmith', 1000, 500, 'champions:mushroom_stew', 14);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (123, 'Blacksmith', 30000, 15000, 'core:cannon', 18);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (124, 'Blacksmith', 15000, 7500, 'core:cannonball', 19);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (58, 'Blacksmith', 500, 250, 'champions:energy_apple', 17);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (157, 'Lumberjack', 100, 10, 'minecraft:acacia_sapling', 41);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (158, 'Lumberjack', 100, 10, 'minecraft:dark_oak_sapling', 42);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (159, 'Lumberjack', 100, 10, 'minecraft:cherry_sapling', 43);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (161, 'Lumberjack', 20, 5, 'minecraft:moss_block', 55);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (162, 'Lumberjack', 500, 10, 'minecraft:flowering_azalea', 56);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (163, 'Lumberjack', 500, 10, 'minecraft:azalea', 57);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (164, 'Lumberjack', 500, 10, 'minecraft:big_dripleaf', 58);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (165, 'Lumberjack', 500, 10, 'minecraft:small_dripleaf', 59);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (166, 'Lumberjack', 40, 10, 'minecraft:warped_nylium', 60);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (167, 'Lumberjack', 40, 10, 'minecraft:crimson_nylium', 61);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (168, 'Lumberjack', 150, 5, 'minecraft:pink_petals', 64);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (169, 'Lumberjack', 2000, 50, 'minecraft:spore_blossom', 65);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (170, 'Lumberjack', 50, 5, 'minecraft:vine', 66);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (171, 'Lumberjack', 1500, 75, 'minecraft:lily_pad', 67);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (172, 'Lumberjack', 2000, 100, 'minecraft:decorated_pot', 68);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (173, 'Lumberjack', 250, 10, 'minecraft:twisting_vines', 69);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (174, 'Lumberjack', 250, 10, 'minecraft:weeping_vines', 70);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (175, 'Lumberjack', 750, 200, 'minecraft:horn_coral', 73);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (176, 'Lumberjack', 750, 200, 'minecraft:brain_coral', 74);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (177, 'Lumberjack', 750, 200, 'minecraft:fire_coral', 75);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (218, 'Fisherman', 40, 25, 'progression:trout', 0);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (178, 'Lumberjack', 750, 200, 'minecraft:bubble_coral', 76);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (179, 'Lumberjack', 750, 200, 'minecraft:tube_coral', 77);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (180, 'Lumberjack', 100, 5, 'minecraft:warped_roots', 78);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (181, 'Lumberjack', 100, 5, 'minecraft:crimson_roots', 79);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (182, 'Lumberjack', 750, 50, 'minecraft:peony', 82);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (183, 'Lumberjack', 750, 50, 'minecraft:rose_bush', 83);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (184, 'Lumberjack', 750, 50, 'minecraft:lilac', 84);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (185, 'Lumberjack', 1000, 250, 'minecraft:torchflower', 85);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (186, 'Lumberjack', 50, 5, 'minecraft:seagrass', 86);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (187, 'Lumberjack', 2000, 100, 'minecraft:sea_pickle', 87);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (188, 'Lumberjack', 50, 5, 'minecraft:kelp', 88);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (219, 'Fisherman', 40, 25, 'progression:salmon', 1);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (220, 'Fisherman', 40, 25, 'progression:bluegill', 2);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (221, 'Fisherman', 40, 25, 'progression:gar', 3);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (222, 'Fisherman', 40, 25, 'progression:carp', 4);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (223, 'Fisherman', 40, 25, 'progression:catfish', 5);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (224, 'Fisherman', 40, 25, 'progression:cod', 6);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (225, 'Fisherman', 40, 25, 'progression:drum', 7);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (226, 'Fisherman', 40, 25, 'progression:sablefish', 8);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (227, 'Fisherman', 40, 25, 'progression:kingfish', 9);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (228, 'Fisherman', 40, 25, 'progression:cobia', 10);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (229, 'Fisherman', 40, 25, 'progression:sea_bass', 11);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (230, 'Fisherman', 40, 25, 'progression:tuna', 12);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (231, 'Fisherman', 40, 25, 'progression:swordfish', 13);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (232, 'Fisherman', 40, 25, 'progression:marlin', 14);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (233, 'Fisherman', 40, 25, 'progression:grouper', 15);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (234, 'Fisherman', 40, 25, 'progression:sturgeon', 16);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (235, 'Fisherman', 40, 25, 'progression:sunfish', 17);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (50, 'Block Merchant', 50, 25, 'minecraft:bamboo_block', 31);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (43, 'Block Merchant', 40, 10, 'minecraft:smooth_quartz', 34);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (196, 'Block Merchant', 700, 350, 'minecraft:glowstone', 35);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (31, 'Block Merchant', 50, 25, 'minecraft:oak_log', 36);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (197, 'Block Merchant', 50, 25, 'minecraft:acacia_log', 39);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (33, 'Block Merchant', 50, 25, 'minecraft:warped_stem', 38);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (32, 'Block Merchant', 50, 25, 'minecraft:crimson_stem', 37);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (198, 'Block Merchant', 50, 25, 'minecraft:cherry_log', 40);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (199, 'Block Merchant', 40, 10, 'minecraft:prismarine_bricks', 42);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (200, 'Block Merchant', 20, 5, 'minecraft:prismarine', 43);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (201, 'Block Merchant', 700, 350, 'minecraft:sea_lantern', 44);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (202, 'Block Merchant', 50, 10, 'minecraft:clay', 47);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (203, 'Block Merchant', 40, 10, 'minecraft:smooth_sandstone', 51);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (204, 'Block Merchant', 10, 2, 'minecraft:sand', 52);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (205, 'Block Merchant', 100, 2, 'minecraft:glass', 41);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (206, 'Block Merchant', 1000, 100, 'minecraft:glow_ink_sac', 159);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (207, 'Block Merchant', 1000, 100, 'minecraft:end_rod', 158);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (208, 'Block Merchant', 100, 15, 'minecraft:glow_lichen', 156);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (209, 'Block Merchant', 700, 150, 'minecraft:shroomlight', 157);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (210, 'Block Merchant', 700, 150, 'minecraft:ochre_froglight', 166);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (145, 'Block Merchant', 500, 0, 'minecraft:red_dye', 110);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (211, 'Block Merchant', 700, 150, 'minecraft:verdant_froglight', 165);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (212, 'Block Merchant', 700, 150, 'minecraft:pearlescent_froglight', 167);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (213, 'Block Merchant', 100, 15, 'minecraft:sculk_vein', 155);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (151, 'Block Merchant', 500, 0, 'minecraft:black_dye', 121);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (149, 'Block Merchant', 500, 0, 'minecraft:blue_dye', 114);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (146, 'Block Merchant', 500, 0, 'minecraft:brown_dye', 111);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (148, 'Block Merchant', 500, 0, 'minecraft:green_dye', 113);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (150, 'Block Merchant', 500, 0, 'minecraft:purple_dye', 120);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (152, 'Block Merchant', 500, 0, 'minecraft:white_dye', 122);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (147, 'Block Merchant', 500, 0, 'minecraft:yellow_dye', 112);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (132, 'Block Merchant', 3000, 0, 'minecraft:comparator', 56);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (139, 'Block Merchant', 2000, 0, 'minecraft:daylight_detector', 78);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (143, 'Block Merchant', 5000, 0, 'minecraft:detector_rail', 84);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (141, 'Block Merchant', 10000, 0, 'minecraft:hopper_minecart', 82);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (134, 'Block Merchant', 500, 0, 'minecraft:iron_door', 61);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (133, 'Block Merchant', 500, 0, 'minecraft:iron_trapdoor', 60);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (137, 'Block Merchant', 20, 0, 'minecraft:lever', 74);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (34, 'Block Merchant', 3000, 0, 'minecraft:piston', 87);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (144, 'Block Merchant', 5000, 0, 'minecraft:powered_rail', 85);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (142, 'Block Merchant', 5000, 0, 'minecraft:rail', 83);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (140, 'Block Merchant', 1000, 0, 'minecraft:redstone_lamp', 79);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (135, 'Block Merchant', 200, 0, 'minecraft:redstone_torch', 64);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (131, 'Block Merchant', 2500, 0, 'minecraft:repeater', 55);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (35, 'Block Merchant', 5000, 0, 'minecraft:sticky_piston', 88);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (136, 'Block Merchant', 2000, 0, 'minecraft:target', 73);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (138, 'Block Merchant', 2000, 0, 'minecraft:tripwire_hook', 75);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (215, 'Farmer', 50000, 0, 'minecraft:bee_spawn_egg', 16);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (214, 'Resource Merchant', 100, 25, 'minecraft:copper_ingot', 12);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (93, 'Resource Merchant', 1000, 50, 'minecraft:string', 22);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (194, 'Block Merchant', 2000, 500, 'clans:water_block', 17);
INSERT INTO public.shopitems (id, shopkeeper, buy_price, sell_price, item_key, "order") VALUES (237, 'Resource Merchant', 25000, 0, 'champions:class_selector', 50);

-- dynamic pricing
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (99, 0, 10, 20, 30, 60, 70, 80, 100000, 200000, 100000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (100, 0, 5, 25, 30, 40, 50, 60, 25000, 50000, 25000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (101, 0, 10, 20, 25, 30, 35, 40, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (102, 0, 10, 30, 40, 65, 75, 85, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (103, 0, 10, 25, 40, 40, 45, 50, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (104, 0, 10, 25, 40, 40, 45, 50, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (105, 0, 10, 25, 40, 45, 55, 65, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (106, 0, 10, 25, 40, 50, 55, 60, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (107, 0, 10, 25, 40, 50, 55, 60, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (108, 0, 7, 23, 35, 40, 45, 50, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (110, 0, 10, 25, 40, 50, 55, 60, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (109, 0, 50, 500, 1000, 3333, 3333, 3333, 5000, 15000, 7500, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (130, 0, 10, 25, 40, 50, 55, 60, 50000, 100000, 50000, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (125, 0, 100, 500, 900, 600, 1000, 1400, 500, 1000, 500, 1769702804957, 1769702804957);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (220, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (222, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (223, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (228, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (224, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (225, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (221, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (233, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (227, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (232, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (226, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (219, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (229, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (234, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (235, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (231, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (218, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);
INSERT INTO public.shopitems_dynamic_pricing (shop_item_id, realm, min_sell_price, base_sell_price, max_sell_price, min_buy_price, base_buy_price, max_buy_price, base_stock, max_stock, current_stock, created_time, updated_time) VALUES (230, 0, 10, 25, 35, 35, 40, 45, 25000, 50000, 25000, 1769702804957, 1769702804983);

-- flags
INSERT INTO public.shopitems_flags (id, shop_item_id, persistent_key, persistent_value) VALUES (1, 116, 'SHOP_CURRENCY', 'BARK');
INSERT INTO public.shopitems_flags (id, shop_item_id, persistent_key, persistent_value) VALUES (2, 117, 'SHOP_CURRENCY', 'BARK');
INSERT INTO public.shopitems_flags (id, shop_item_id, persistent_key, persistent_value) VALUES (3, 118, 'SHOP_CURRENCY', 'BARK');
INSERT INTO public.shopitems_flags (id, shop_item_id, persistent_key, persistent_value) VALUES (4, 119, 'SHOP_CURRENCY', 'BARK');
