name: Core
version: '1.0'
main: me.mykindos.betterpvp.core.Core
api-version: '1.21'

dependencies:
  bootstrap:
    StudioEngine:
      load: BEFORE
      required: false
      join-classpath: true
    ModelEngine:
      load: AFTER
      required: false
      join-classpath: true
    MythicMobs:
      load: AFTER
      required: false
      join-classpath: true
  server:
    StudioEngine:
      load: BEFORE
      required: false
      join-classpath: true
    ModelEngine:
      load: AFTER
      required: false
      join-classpath: true
    MythicMobs:
      load: AFTER
      required: false
      join-classpath: true