skills:
  tree_tactician:
    enabled: true
    maxlevel: 250
    xpBonusPerLvl: 0.004
  bark_bounty:
    enabled: true
    maxlevel: 250
    'barkChanceIncreasePerLvl ': 0.002
    barkChanceIncreasePerLvl: 0.004
  forest_flourisher:
    enabled: true
    maxlevel: 250
    'growFactorIncreasePerLvl ': 0.003
    growFactorIncreasePerLvl: 0.003
  tree_feller:
    enabled: true
    maxlevel: 25
    cooldown: 30.0
    cooldownDecreasePerLevel: 1.0
    maxBlocksThatCanBeFelled: 25
  enchanted_lumberfall:
    enabled: true
    maxlevel: 1
  auto_planter:
    enabled: true
    maxlevel: 1
  tree_compactor:
    enabled: true
    maxlevel: 1
    cooldown: 20.0
