/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq;


import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsCombatStats;
import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsKillContributions;
import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsKills;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_CHAMPIONS_COMBAT_STATS_REALM_CLASS_HIGHEST_KILLSTREAK = Internal.createIndex(DSL.name("idx_champions_combat_stats_realm_class_highest_killstreak"), ChampionsCombatStats.CHAMPIONS_COMBAT_STATS, new OrderField[] { ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.REALM, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.CLASS, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.VALID, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.HIGHEST_KILLSTREAK.desc() }, false);
    public static final Index IDX_CHAMPIONS_COMBAT_STATS_REALM_CLASS_KILLSTREAK = Internal.createIndex(DSL.name("idx_champions_combat_stats_realm_class_killstreak"), ChampionsCombatStats.CHAMPIONS_COMBAT_STATS, new OrderField[] { ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.REALM, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.CLASS, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.VALID, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.KILLSTREAK.desc() }, false);
    public static final Index IDX_CHAMPIONS_COMBAT_STATS_REALM_CLASS_RATING = Internal.createIndex(DSL.name("idx_champions_combat_stats_realm_class_rating"), ChampionsCombatStats.CHAMPIONS_COMBAT_STATS, new OrderField[] { ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.REALM, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.CLASS, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.VALID, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.RATING.desc() }, false);
    public static final Index IDX_CHAMPIONS_COMBAT_STATS_REALM_CLASS_VALID = Internal.createIndex(DSL.name("idx_champions_combat_stats_realm_class_valid"), ChampionsCombatStats.CHAMPIONS_COMBAT_STATS, new OrderField[] { ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.REALM, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.CLASS, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.VALID }, false);
    public static final Index IDX_CHAMPIONS_COMBAT_STATS_REALM_CLIENT_VALID = Internal.createIndex(DSL.name("idx_champions_combat_stats_realm_client_valid"), ChampionsCombatStats.CHAMPIONS_COMBAT_STATS, new OrderField[] { ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.REALM, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.CLIENT, ChampionsCombatStats.CHAMPIONS_COMBAT_STATS.VALID }, false);
    public static final Index IDX_CHAMPIONS_KILL_CONTRIBUTIONS_CONTRIBUTOR_CLASS = Internal.createIndex(DSL.name("idx_champions_kill_contributions_contributor_class"), ChampionsKillContributions.CHAMPIONS_KILL_CONTRIBUTIONS, new OrderField[] { ChampionsKillContributions.CHAMPIONS_KILL_CONTRIBUTIONS.CONTRIBUTOR_CLASS }, false);
    public static final Index IDX_CHAMPIONS_KILLS_KILLER_CLASS = Internal.createIndex(DSL.name("idx_champions_kills_killer_class"), ChampionsKills.CHAMPIONS_KILLS, new OrderField[] { ChampionsKills.CHAMPIONS_KILLS.KILLER_CLASS }, false);
    public static final Index IDX_CHAMPIONS_KILLS_VICTIM_CLASS = Internal.createIndex(DSL.name("idx_champions_kills_victim_class"), ChampionsKills.CHAMPIONS_KILLS, new OrderField[] { ChampionsKills.CHAMPIONS_KILLS.VICTIM_CLASS }, false);
}
