/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq;


import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsBuilds;
import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsCombatStats;
import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsKillContributions;
import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsKilldeathData;
import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsKills;
import me.mykindos.betterpvp.champions.database.jooq.tables.GetChampionsData;
import me.mykindos.betterpvp.champions.database.jooq.tables.GetTopDeathsByClass;
import me.mykindos.betterpvp.champions.database.jooq.tables.GetTopHighestKillstreakByClass;
import me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKdrByClass;
import me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillsByClass;
import me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillstreakByClass;
import me.mykindos.betterpvp.champions.database.jooq.tables.GetTopRatingByClass;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetChampionsDataRecord;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetTopDeathsByClassRecord;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetTopHighestKillstreakByClassRecord;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetTopKdrByClassRecord;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetTopKillsByClassRecord;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetTopKillstreakByClassRecord;
import me.mykindos.betterpvp.champions.database.jooq.tables.records.GetTopRatingByClassRecord;
import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.champions_builds</code>.
     */
    public final ChampionsBuilds CHAMPIONS_BUILDS = ChampionsBuilds.CHAMPIONS_BUILDS;

    /**
     * The table <code>public.champions_combat_stats</code>.
     */
    public final ChampionsCombatStats CHAMPIONS_COMBAT_STATS = ChampionsCombatStats.CHAMPIONS_COMBAT_STATS;

    /**
     * The table <code>public.champions_kill_contributions</code>.
     */
    public final ChampionsKillContributions CHAMPIONS_KILL_CONTRIBUTIONS = ChampionsKillContributions.CHAMPIONS_KILL_CONTRIBUTIONS;

    /**
     * The table <code>public.champions_killdeath_data</code>.
     */
    public final ChampionsKilldeathData CHAMPIONS_KILLDEATH_DATA = ChampionsKilldeathData.CHAMPIONS_KILLDEATH_DATA;

    /**
     * The table <code>public.champions_kills</code>.
     */
    public final ChampionsKills CHAMPIONS_KILLS = ChampionsKills.CHAMPIONS_KILLS;

    /**
     * The table <code>public.get_champions_data</code>.
     */
    public final GetChampionsData GET_CHAMPIONS_DATA = GetChampionsData.GET_CHAMPIONS_DATA;

    /**
     * Call <code>public.get_champions_data</code>.
     */
    public static Result<GetChampionsDataRecord> GET_CHAMPIONS_DATA(
          Configuration configuration
        , String clientUuid
        , Integer realmVar
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.champions.database.jooq.tables.GetChampionsData.GET_CHAMPIONS_DATA.call(
              clientUuid
            , realmVar
        )).fetch();
    }

    /**
     * Get <code>public.get_champions_data</code> as a table.
     */
    public static GetChampionsData GET_CHAMPIONS_DATA(
          String clientUuid
        , Integer realmVar
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetChampionsData.GET_CHAMPIONS_DATA.call(
            clientUuid,
            realmVar
        );
    }

    /**
     * Get <code>public.get_champions_data</code> as a table.
     */
    public static GetChampionsData GET_CHAMPIONS_DATA(
          Field<String> clientUuid
        , Field<Integer> realmVar
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetChampionsData.GET_CHAMPIONS_DATA.call(
            clientUuid,
            realmVar
        );
    }

    /**
     * The table <code>public.get_top_deaths_by_class</code>.
     */
    public final GetTopDeathsByClass GET_TOP_DEATHS_BY_CLASS = GetTopDeathsByClass.GET_TOP_DEATHS_BY_CLASS;

    /**
     * Call <code>public.get_top_deaths_by_class</code>.
     */
    public static Result<GetTopDeathsByClassRecord> GET_TOP_DEATHS_BY_CLASS(
          Configuration configuration
        , Integer realmVar
        , Integer top
        , String classParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.champions.database.jooq.tables.GetTopDeathsByClass.GET_TOP_DEATHS_BY_CLASS.call(
              realmVar
            , top
            , classParam
        )).fetch();
    }

    /**
     * Get <code>public.get_top_deaths_by_class</code> as a table.
     */
    public static GetTopDeathsByClass GET_TOP_DEATHS_BY_CLASS(
          Integer realmVar
        , Integer top
        , String classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopDeathsByClass.GET_TOP_DEATHS_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * Get <code>public.get_top_deaths_by_class</code> as a table.
     */
    public static GetTopDeathsByClass GET_TOP_DEATHS_BY_CLASS(
          Field<Integer> realmVar
        , Field<Integer> top
        , Field<String> classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopDeathsByClass.GET_TOP_DEATHS_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * The table <code>public.get_top_highest_killstreak_by_class</code>.
     */
    public final GetTopHighestKillstreakByClass GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS = GetTopHighestKillstreakByClass.GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS;

    /**
     * Call <code>public.get_top_highest_killstreak_by_class</code>.
     */
    public static Result<GetTopHighestKillstreakByClassRecord> GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS(
          Configuration configuration
        , Integer realmVar
        , Integer top
        , String classParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.champions.database.jooq.tables.GetTopHighestKillstreakByClass.GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS.call(
              realmVar
            , top
            , classParam
        )).fetch();
    }

    /**
     * Get <code>public.get_top_highest_killstreak_by_class</code> as a table.
     */
    public static GetTopHighestKillstreakByClass GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS(
          Integer realmVar
        , Integer top
        , String classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopHighestKillstreakByClass.GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * Get <code>public.get_top_highest_killstreak_by_class</code> as a table.
     */
    public static GetTopHighestKillstreakByClass GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS(
          Field<Integer> realmVar
        , Field<Integer> top
        , Field<String> classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopHighestKillstreakByClass.GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * The table <code>public.get_top_kdr_by_class</code>.
     */
    public final GetTopKdrByClass GET_TOP_KDR_BY_CLASS = GetTopKdrByClass.GET_TOP_KDR_BY_CLASS;

    /**
     * Call <code>public.get_top_kdr_by_class</code>.
     */
    public static Result<GetTopKdrByClassRecord> GET_TOP_KDR_BY_CLASS(
          Configuration configuration
        , Integer realmVar
        , Integer top
        , String classParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKdrByClass.GET_TOP_KDR_BY_CLASS.call(
              realmVar
            , top
            , classParam
        )).fetch();
    }

    /**
     * Get <code>public.get_top_kdr_by_class</code> as a table.
     */
    public static GetTopKdrByClass GET_TOP_KDR_BY_CLASS(
          Integer realmVar
        , Integer top
        , String classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKdrByClass.GET_TOP_KDR_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * Get <code>public.get_top_kdr_by_class</code> as a table.
     */
    public static GetTopKdrByClass GET_TOP_KDR_BY_CLASS(
          Field<Integer> realmVar
        , Field<Integer> top
        , Field<String> classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKdrByClass.GET_TOP_KDR_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * The table <code>public.get_top_kills_by_class</code>.
     */
    public final GetTopKillsByClass GET_TOP_KILLS_BY_CLASS = GetTopKillsByClass.GET_TOP_KILLS_BY_CLASS;

    /**
     * Call <code>public.get_top_kills_by_class</code>.
     */
    public static Result<GetTopKillsByClassRecord> GET_TOP_KILLS_BY_CLASS(
          Configuration configuration
        , Integer realmVar
        , Integer top
        , String classParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillsByClass.GET_TOP_KILLS_BY_CLASS.call(
              realmVar
            , top
            , classParam
        )).fetch();
    }

    /**
     * Get <code>public.get_top_kills_by_class</code> as a table.
     */
    public static GetTopKillsByClass GET_TOP_KILLS_BY_CLASS(
          Integer realmVar
        , Integer top
        , String classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillsByClass.GET_TOP_KILLS_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * Get <code>public.get_top_kills_by_class</code> as a table.
     */
    public static GetTopKillsByClass GET_TOP_KILLS_BY_CLASS(
          Field<Integer> realmVar
        , Field<Integer> top
        , Field<String> classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillsByClass.GET_TOP_KILLS_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * The table <code>public.get_top_killstreak_by_class</code>.
     */
    public final GetTopKillstreakByClass GET_TOP_KILLSTREAK_BY_CLASS = GetTopKillstreakByClass.GET_TOP_KILLSTREAK_BY_CLASS;

    /**
     * Call <code>public.get_top_killstreak_by_class</code>.
     */
    public static Result<GetTopKillstreakByClassRecord> GET_TOP_KILLSTREAK_BY_CLASS(
          Configuration configuration
        , Integer realmVar
        , Integer top
        , String classParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillstreakByClass.GET_TOP_KILLSTREAK_BY_CLASS.call(
              realmVar
            , top
            , classParam
        )).fetch();
    }

    /**
     * Get <code>public.get_top_killstreak_by_class</code> as a table.
     */
    public static GetTopKillstreakByClass GET_TOP_KILLSTREAK_BY_CLASS(
          Integer realmVar
        , Integer top
        , String classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillstreakByClass.GET_TOP_KILLSTREAK_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * Get <code>public.get_top_killstreak_by_class</code> as a table.
     */
    public static GetTopKillstreakByClass GET_TOP_KILLSTREAK_BY_CLASS(
          Field<Integer> realmVar
        , Field<Integer> top
        , Field<String> classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopKillstreakByClass.GET_TOP_KILLSTREAK_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * The table <code>public.get_top_rating_by_class</code>.
     */
    public final GetTopRatingByClass GET_TOP_RATING_BY_CLASS = GetTopRatingByClass.GET_TOP_RATING_BY_CLASS;

    /**
     * Call <code>public.get_top_rating_by_class</code>.
     */
    public static Result<GetTopRatingByClassRecord> GET_TOP_RATING_BY_CLASS(
          Configuration configuration
        , Integer realmVar
        , Integer top
        , String classParam
    ) {
        return configuration.dsl().selectFrom(me.mykindos.betterpvp.champions.database.jooq.tables.GetTopRatingByClass.GET_TOP_RATING_BY_CLASS.call(
              realmVar
            , top
            , classParam
        )).fetch();
    }

    /**
     * Get <code>public.get_top_rating_by_class</code> as a table.
     */
    public static GetTopRatingByClass GET_TOP_RATING_BY_CLASS(
          Integer realmVar
        , Integer top
        , String classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopRatingByClass.GET_TOP_RATING_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * Get <code>public.get_top_rating_by_class</code> as a table.
     */
    public static GetTopRatingByClass GET_TOP_RATING_BY_CLASS(
          Field<Integer> realmVar
        , Field<Integer> top
        , Field<String> classParam
    ) {
        return me.mykindos.betterpvp.champions.database.jooq.tables.GetTopRatingByClass.GET_TOP_RATING_BY_CLASS.call(
            realmVar,
            top,
            classParam
        );
    }

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ChampionsBuilds.CHAMPIONS_BUILDS,
            ChampionsCombatStats.CHAMPIONS_COMBAT_STATS,
            ChampionsKillContributions.CHAMPIONS_KILL_CONTRIBUTIONS,
            ChampionsKilldeathData.CHAMPIONS_KILLDEATH_DATA,
            ChampionsKills.CHAMPIONS_KILLS,
            GetChampionsData.GET_CHAMPIONS_DATA,
            GetTopDeathsByClass.GET_TOP_DEATHS_BY_CLASS,
            GetTopHighestKillstreakByClass.GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS,
            GetTopKdrByClass.GET_TOP_KDR_BY_CLASS,
            GetTopKillsByClass.GET_TOP_KILLS_BY_CLASS,
            GetTopKillstreakByClass.GET_TOP_KILLSTREAK_BY_CLASS,
            GetTopRatingByClass.GET_TOP_RATING_BY_CLASS
        );
    }
}
