/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.shops.database.jooq;


import java.util.Arrays;
import java.util.List;

import me.mykindos.betterpvp.shops.database.jooq.tables.AuctionTransactionHistory;
import me.mykindos.betterpvp.shops.database.jooq.tables.Auctions;
import me.mykindos.betterpvp.shops.database.jooq.tables.Shopitems;
import me.mykindos.betterpvp.shops.database.jooq.tables.ShopitemsDynamicPricing;
import me.mykindos.betterpvp.shops.database.jooq.tables.ShopitemsFlags;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.auction_transaction_history</code>.
     */
    public final AuctionTransactionHistory AUCTION_TRANSACTION_HISTORY = AuctionTransactionHistory.AUCTION_TRANSACTION_HISTORY;

    /**
     * The table <code>public.auctions</code>.
     */
    public final Auctions AUCTIONS = Auctions.AUCTIONS;

    /**
     * The table <code>public.shopitems</code>.
     */
    public final Shopitems SHOPITEMS = Shopitems.SHOPITEMS;

    /**
     * The table <code>public.shopitems_dynamic_pricing</code>.
     */
    public final ShopitemsDynamicPricing SHOPITEMS_DYNAMIC_PRICING = ShopitemsDynamicPricing.SHOPITEMS_DYNAMIC_PRICING;

    /**
     * The table <code>public.shopitems_flags</code>.
     */
    public final ShopitemsFlags SHOPITEMS_FLAGS = ShopitemsFlags.SHOPITEMS_FLAGS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuctionTransactionHistory.AUCTION_TRANSACTION_HISTORY,
            Auctions.AUCTIONS,
            Shopitems.SHOPITEMS,
            ShopitemsDynamicPricing.SHOPITEMS_DYNAMIC_PRICING,
            ShopitemsFlags.SHOPITEMS_FLAGS
        );
    }
}
