package me.mykindos.betterpvp.core.loot;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Value;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Stream;

/**
 * Represents a collection of loot entries that is generated by a {@link LootTable}
 * upon a {@link LootContext} request.
 * <p>
 * An instance of {@link LootBundle} is generated each time new loot is petitioned
 * by a {@link LootContext}.
 */
@Value
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class LootBundle implements Iterable<Loot<?, ?>> {

    /**
     * The context for which the loot bundle is being generated.
     */
    LootContext context;

    /**
     * The list of loot entries.
     * <p>
     * This list is not guaranteed to be populated with any entries, as some loot tables
     * may not generate any loot.
     */
    @NotNull List<@NotNull Loot<?, ?>> loot;

    public @NotNull Collection<@NotNull Loot<?, ?>> getLoot() {
        return Collections.unmodifiableCollection(loot);
    }

    public int getSize() {
        return this.loot.size();
    }

    /**
     * Returns an iterator over elements of type {@code T}.
     *
     * @return an Iterator.
     */
    @Override
    public @NotNull Iterator<Loot<?, ?>> iterator() {
        return loot.iterator();
    }

    /**
     * Awards the loot entries contained in this bundle to the context.
     * @see Loot#award(LootContext)
     */
    public Stream<Object> award() {
        final List<Object> results = new ArrayList<>();
        for (Loot<?, ?> entry : this) {
            results.add(entry.award(this.context));
        }
        return results.stream();
    }
}
