-- Page 2 of Lumberjack
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'MOSS_BLOCK', 'Moss Block', 0, 10, 2, 1, 20, 5);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'FLOWERING_AZALEA', 'Flowering Azalea', 0, 11, 2, 1, 500, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'AZALEA', 'Azalea', 0, 12, 2, 1, 500, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'BIG_DRIPLEAF', 'Big Dripleaf', 0, 13, 2, 1, 500, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'SMALL_DRIPLEAF', 'Small Dripleaf', 0, 14, 2, 1, 500, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'WARPED_NYLIUM', 'Warped Nylium', 0, 15, 2, 1, 40, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'CRIMSON_NYLIUM', 'Crimson Nylium', 0, 16, 2, 1, 40, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'PINK_PETALS', 'Pink Petals', 0, 19, 2, 1, 150, 5);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'SPORE_BLOSSOM', 'Spore Blossom', 0, 20, 2, 1, 2000, 50);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'VINE', 'Vines', 0, 21, 2, 1, 50, 5);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'LILY_PAD', 'Lily Pad', 0, 22, 2, 1, 1500, 75);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'DECORATED_POT', 'Decorated Pot', 0, 23, 2, 1, 2000, 100);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'TWISTING_VINES', 'Twisting Vines', 0, 24, 2, 1, 250, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'WEEPING_VINES', 'Weeping Vines', 0, 25, 2, 1, 250, 10);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'HORN_CORAL', 'Horn Coral', 0, 28, 2, 1, 750, 200);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'BRAIN_CORAL', 'Brain Coral', 0, 29, 2, 1, 750, 200);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'FIRE_CORAL', 'Fire Coral', 0, 30, 2, 1, 750, 200);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'BUBBLE_CORAL', 'Bubble Coral', 0, 31, 2, 1, 750, 200);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'TUBE_CORAL', 'Tube Coral', 0, 32, 2, 1, 750, 200);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'WARPED_ROOTS', 'Warped Roots', 0, 33, 2, 1, 100, 5);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'CRIMSON_ROOTS', 'Crimson Roots', 0, 34, 2, 1, 100, 5);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'PEONY', 'Peony', 0, 37, 2, 1, 750, 50);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'ROSE_BUSH', 'Rose Bush', 0, 38, 2, 1, 750, 50);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'LILAC', 'Lilac', 0, 39, 2, 1, 750, 50);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'TORCHFLOWER', 'Torchflower', 0, 40, 2, 1, 1000, 250);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'SEAGRASS', 'Seagrass', 0, 41, 2, 1, 50, 5);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'SEA_PICKLE', 'Sea Pickle', 0, 42, 2, 1, 2000, 100);
INSERT IGNORE INTO shopitems (Shopkeeper, Material, ItemName, ModelData, MenuSlot, MenuPage, Amount, BuyPrice, SellPrice) VALUES ('Lumberjack', 'KELP', 'Kelp', 0, 43, 2, 1, 50, 5);

