hotbar-layout-tokens: 10

command:
  spectate:
    enabled: true
    requiredRank: PLAYER
  teamchat:
    enabled: true
    requiredRank: PLAYER
  spectatorchat:
    enabled: true
    requiredRank: PLAYER
  game:
    enabled: true
    requiredRank: ADMIN
    start:
      enabled: true
      requiredRank: MODERATOR
# Web Config settings
# If enabled, the plugin will load from local files first,
# then override any values found in the web configuration.
# The web configuration supports directories for each plugin, e.g.:
# core/resourcepacks.yml, champions/skills/skills.yml, clans/config.yml
webconfig:
  enabled: true
  url: https://betterpvp.net/configs