name: Champions
version: '1.0'
main: me.mykindos.betterpvp.champions.Champions
api-version: '1.21'

dependencies:
  bootstrap:
    Core:
      load: BEFORE
      required: true
      join-classpath: true
    Progression:
      load: BEFORE
      required: false
      join-classpath: true
  server:
    Core:
      load: BEFORE
      required: true
      join-classpath: true
    Progression:
      load: BEFORE
      required: false
      join-classpath: true