package me.mykindos.betterpvp.core.utilities;

import net.kyori.adventure.key.Key;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.TextComponent;
import net.kyori.adventure.text.TranslatableComponent;
import net.kyori.adventure.text.format.TextDecoration;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.Map;

/**
 * Pixel-advance calculators for the Minecraft default font and the pack fonts menus draw text in. "Advance" is the cursor
 * movement a glyph causes: its visible width plus the 1px spacing the client inserts
 * after every glyph. Self-cancelling action bars and HUDs rely on them: a
 * block of text must be paid back with an equal negative {@code space.-N} so the
 * centered component's total advance (and therefore its on-screen position) is untouched.
 * <p>
 * Advances come from {@code font/default_advances.bin}, generated from the vanilla client's
 * font sheets and unifont by {@code core/tools/font_advances.py}, and from one table per pack font
 * generated by {@code core/tools/pack_font_advances.py}. Regenerate a pack font's table whenever its
 * font json or textures change.
 */
public final class UtilFont {

    private static final int UNIFONT_FLAG = 0x80;
    private static final byte[] ADVANCES = loadAdvances("default_advances.bin");
    private static final Map<Key, byte[]> PACK_FONT_ADVANCES = Map.of(
            Key.key("betterpvp", "rpg"), loadAdvances("rpg_advances.bin"),
            Key.key("betterpvp", "rpg_large"), loadAdvances("rpg_large_advances.bin"));

    private UtilFont() {
    }

    /** Pixel advance of a single default-font glyph (glyph width + 1px spacing). */
    public static int charWidth(char c) {
        return ADVANCES[c] & 0xFF & ~UNIFONT_FLAG;
    }

    /** Pixel advance of a string in the default font (sum of each glyph's advance). */
    public static int textWidth(String text) {
        int width = 0;
        for (int i = 0; i < text.length(); i++) {
            width += charWidth(text.charAt(i));
        }
        return width;
    }

    /** Pixel advance of a string in the given font. Fonts without a table measure as the default font. */
    public static int textWidth(String text, Key font) {
        return Math.floorDiv(textHalfWidth(text, false, advancesFor(font)) + 1, 2);
    }

    /**
     * Pixel advance of a fully-rendered component tree, rounded up the way the client rounds it.
     * Bold widens a sheet glyph by 1px and a unifont glyph by half a pixel, and {@code space.N}
     * nodes in the space font advance by N. Text in a pack font with a table (such as
     * {@link Resources.Font#UI}) is measured in that font, and text in any other font as the default
     * font. Fonts are inherited from the parent like the client does. Resolve translatable nodes (e.g. via {@code Translations.render}) before calling,
     * otherwise their text isn't present to measure.
     */
    public static int componentWidth(Component component) {
        return Math.floorDiv(componentHalfWidth(component, false, Resources.Font.DEFAULT) + 1, 2);
    }

    // Measured in half pixels so bold unifont glyphs stay exact until the final round-up.
    private static int componentHalfWidth(Component component, boolean parentBold, Key parentFont) {
        final boolean bold = switch (component.decoration(TextDecoration.BOLD)) {
            case TRUE -> true;
            case FALSE -> false;
            case NOT_SET -> parentBold;
        };

        final Key font = component.font() != null ? component.font() : parentFont;

        int width = 0;
        if (component instanceof TextComponent text) {
            width += textHalfWidth(text.content(), bold, advancesFor(font));
        } else if (component instanceof TranslatableComponent translatable
                && Resources.Font.SPACE.equals(component.font())
                && translatable.key().startsWith("space.")) {
            width += spaceAdvance(translatable.key()) * 2;
        }
        for (Component child : component.children()) {
            width += componentHalfWidth(child, bold, font);
        }
        return width;
    }

    private static byte[] advancesFor(Key font) {
        return PACK_FONT_ADVANCES.getOrDefault(font, ADVANCES);
    }

    private static int textHalfWidth(String text, boolean bold, byte[] advances) {
        int width = 0;
        for (int i = 0; i < text.length(); ) {
            final int codePoint = text.codePointAt(i);
            i += Character.charCount(codePoint);
            if (codePoint > Character.MAX_VALUE) {
                width += (6 + (bold ? 1 : 0)) * 2; // missing-glyph box
                continue;
            }
            final int entry = advances[codePoint] & 0xFF;
            width += (entry & ~UNIFONT_FLAG) * 2;
            if (bold) {
                width += (entry & UNIFONT_FLAG) != 0 ? 1 : 2;
            }
        }
        return width;
    }

    private static int spaceAdvance(String key) {
        try {
            return Integer.parseInt(key.substring("space.".length()));
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private static byte[] loadAdvances(String file) {
        try (InputStream stream = UtilFont.class.getResourceAsStream("/font/" + file)) {
            if (stream == null) {
                throw new IllegalStateException("Missing font/" + file);
            }
            return stream.readAllBytes();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
