package me.mykindos.betterpvp.core.menu.dialog;

import net.kyori.adventure.key.Key;

import java.util.Set;

/**
 * Fonts that draw lower than their base font, generated by the pack's {@code tools/gui/offset_fonts.py} for the RPG
 * and ui fonts, and by {@code tools/gui/build_gui.py} for the screen art fonts {@code betterpvp:gui/<namespace>}. A canvas
 * places an element on the 9 px line that holds its top and shifts it down the remaining pixels with one of these.
 */
public final class VerticalOffsets {

    /** Largest shift generated. A line is 9 px, so 0 to 8 reach every row. */
    public static final int MAX = 8;

    private static final Set<Key> BASES = Set.of(Key.key("betterpvp", "rpg"), Key.key("betterpvp", "rpg_large"), Key.key("betterpvp", "ui"));

    private VerticalOffsets() {
    }

    /** The font that draws {@code base} {@code offset} pixels lower. */
    public static Key font(Key base, int offset) {
        if (offset < 0 || offset > MAX) {
            throw new IllegalArgumentException("No vertical offset font for " + offset + " px, the range is 0 to " + MAX);
        }
        if (offset == 0) {
            return base;
        }
        if (!BASES.contains(base) && !(base.namespace().equals("betterpvp") && base.value().startsWith("gui/"))) {
            throw new IllegalArgumentException("Font " + base.asString() + " has no vertical offset fonts");
        }
        return Key.key(base.namespace(), base.value() + "/down_" + offset);
    }
}
