name: CI - Unit Tests

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew --no-daemon test

      - name: SonarCloud analysis (Gradle)
        run: >
          ./gradlew --no-daemon sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.projectName=${{ github.repository }}
          -Dsonar.exclusions=**/build/**
          -Dsonar.junit.reportPaths=**/build/test-results/test
          -Dsonar.java.binaries=**/build/classes/java/main,**/build/classes/kotlin/main
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Publish test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.run_id }}
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/**
          if-no-files-found: ignore
          retention-days: 7
