/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables.records;


import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsDamagevalues;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChampionsDamagevaluesRecord extends UpdatableRecordImpl<ChampionsDamagevaluesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.champions_damagevalues.material</code>.
     */
    public ChampionsDamagevaluesRecord setMaterial(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_damagevalues.material</code>.
     */
    public String getMaterial() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.champions_damagevalues.damage</code>.
     */
    public ChampionsDamagevaluesRecord setDamage(Double value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_damagevalues.damage</code>.
     */
    public Double getDamage() {
        return (Double) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChampionsDamagevaluesRecord
     */
    public ChampionsDamagevaluesRecord() {
        super(ChampionsDamagevalues.CHAMPIONS_DAMAGEVALUES);
    }

    /**
     * Create a detached, initialised ChampionsDamagevaluesRecord
     */
    public ChampionsDamagevaluesRecord(String material, Double damage) {
        super(ChampionsDamagevalues.CHAMPIONS_DAMAGEVALUES);

        setMaterial(material);
        setDamage(damage);
        resetChangedOnNotNull();
    }
}
