/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables.records;


import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsCombatStats;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChampionsCombatStatsRecord extends TableRecordImpl<ChampionsCombatStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.champions_combat_stats.client</code>.
     */
    public ChampionsCombatStatsRecord setClient(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_combat_stats.client</code>.
     */
    public Long getClient() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.champions_combat_stats.realm</code>.
     */
    public ChampionsCombatStatsRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_combat_stats.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.champions_combat_stats.class</code>.
     */
    public ChampionsCombatStatsRecord setClass_(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_combat_stats.class</code>.
     */
    public String getClass_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.champions_combat_stats.rating</code>.
     */
    public ChampionsCombatStatsRecord setRating(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_combat_stats.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.champions_combat_stats.killstreak</code>.
     */
    public ChampionsCombatStatsRecord setKillstreak(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_combat_stats.killstreak</code>.
     */
    public Integer getKillstreak() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.champions_combat_stats.highest_killstreak</code>.
     */
    public ChampionsCombatStatsRecord setHighestKillstreak(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_combat_stats.highest_killstreak</code>.
     */
    public Integer getHighestKillstreak() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.champions_combat_stats.valid</code>.
     */
    public ChampionsCombatStatsRecord setValid(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.champions_combat_stats.valid</code>.
     */
    public Boolean getValid() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChampionsCombatStatsRecord
     */
    public ChampionsCombatStatsRecord() {
        super(ChampionsCombatStats.CHAMPIONS_COMBAT_STATS);
    }

    /**
     * Create a detached, initialised ChampionsCombatStatsRecord
     */
    public ChampionsCombatStatsRecord(Long client, Integer realm, String class_, Integer rating, Integer killstreak, Integer highestKillstreak, Boolean valid) {
        super(ChampionsCombatStats.CHAMPIONS_COMBAT_STATS);

        setClient(client);
        setRealm(realm);
        setClass_(class_);
        setRating(rating);
        setKillstreak(killstreak);
        setHighestKillstreak(highestKillstreak);
        setValid(valid);
        resetChangedOnNotNull();
    }
}
