/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables.records;


import me.mykindos.betterpvp.champions.database.jooq.tables.ChampionsKillContributions;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChampionsKillContributionsRecord extends UpdatableRecordImpl<ChampionsKillContributionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.champions_kill_contributions.contribution_id</code>.
     */
    public ChampionsKillContributionsRecord setContributionId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.champions_kill_contributions.contribution_id</code>.
     */
    public Long getContributionId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.champions_kill_contributions.contributor_class</code>.
     */
    public ChampionsKillContributionsRecord setContributorClass(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.champions_kill_contributions.contributor_class</code>.
     */
    public String getContributorClass() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChampionsKillContributionsRecord
     */
    public ChampionsKillContributionsRecord() {
        super(ChampionsKillContributions.CHAMPIONS_KILL_CONTRIBUTIONS);
    }

    /**
     * Create a detached, initialised ChampionsKillContributionsRecord
     */
    public ChampionsKillContributionsRecord(Long contributionId, String contributorClass) {
        super(ChampionsKillContributions.CHAMPIONS_KILL_CONTRIBUTIONS);

        setContributionId(contributionId);
        setContributorClass(contributorClass);
        resetChangedOnNotNull();
    }
}
