/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables.records;


import me.mykindos.betterpvp.champions.database.jooq.tables.GetChampionsData;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetChampionsDataRecord extends TableRecordImpl<GetChampionsDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_champions_data.class</code>.
     */
    public GetChampionsDataRecord setClass_(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_champions_data.class</code>.
     */
    public String getClass_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.get_champions_data.kills</code>.
     */
    public GetChampionsDataRecord setKills(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_champions_data.kills</code>.
     */
    public Long getKills() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.get_champions_data.deaths</code>.
     */
    public GetChampionsDataRecord setDeaths(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.get_champions_data.deaths</code>.
     */
    public Long getDeaths() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.get_champions_data.assists</code>.
     */
    public GetChampionsDataRecord setAssists(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.get_champions_data.assists</code>.
     */
    public Long getAssists() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.get_champions_data.rating</code>.
     */
    public GetChampionsDataRecord setRating(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.get_champions_data.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.get_champions_data.killstreak</code>.
     */
    public GetChampionsDataRecord setKillstreak(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.get_champions_data.killstreak</code>.
     */
    public Integer getKillstreak() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.get_champions_data.highest_killstreak</code>.
     */
    public GetChampionsDataRecord setHighestKillstreak(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.get_champions_data.highest_killstreak</code>.
     */
    public Integer getHighestKillstreak() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetChampionsDataRecord
     */
    public GetChampionsDataRecord() {
        super(GetChampionsData.GET_CHAMPIONS_DATA);
    }

    /**
     * Create a detached, initialised GetChampionsDataRecord
     */
    public GetChampionsDataRecord(String class_, Long kills, Long deaths, Long assists, Integer rating, Integer killstreak, Integer highestKillstreak) {
        super(GetChampionsData.GET_CHAMPIONS_DATA);

        setClass_(class_);
        setKills(kills);
        setDeaths(deaths);
        setAssists(assists);
        setRating(rating);
        setKillstreak(killstreak);
        setHighestKillstreak(highestKillstreak);
        resetChangedOnNotNull();
    }
}
