/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables.records;


import me.mykindos.betterpvp.champions.database.jooq.tables.GetTopHighestKillstreakByClass;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetTopHighestKillstreakByClassRecord extends TableRecordImpl<GetTopHighestKillstreakByClassRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.get_top_highest_killstreak_by_class.client</code>.
     */
    public GetTopHighestKillstreakByClassRecord setClient(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_top_highest_killstreak_by_class.client</code>.
     */
    public String getClient() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.get_top_highest_killstreak_by_class.highest_killstreak</code>.
     */
    public GetTopHighestKillstreakByClassRecord setHighestKillstreak(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.get_top_highest_killstreak_by_class.highest_killstreak</code>.
     */
    public Integer getHighestKillstreak() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetTopHighestKillstreakByClassRecord
     */
    public GetTopHighestKillstreakByClassRecord() {
        super(GetTopHighestKillstreakByClass.GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS);
    }

    /**
     * Create a detached, initialised GetTopHighestKillstreakByClassRecord
     */
    public GetTopHighestKillstreakByClassRecord(String client, Integer highestKillstreak) {
        super(GetTopHighestKillstreakByClass.GET_TOP_HIGHEST_KILLSTREAK_BY_CLASS);

        setClient(client);
        setHighestKillstreak(highestKillstreak);
        resetChangedOnNotNull();
    }
}
