/*
 * This file is generated by jOOQ.
 */
package me.mykindos.betterpvp.champions.database.jooq.tables.records;


import me.mykindos.betterpvp.champions.database.jooq.tables.GrafanaRoleMatchupSnapshot;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GrafanaRoleMatchupSnapshotRecord extends UpdatableRecordImpl<GrafanaRoleMatchupSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.id</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.realm</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setRealm(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.realm</code>.
     */
    public Integer getRealm() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.captured_at</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setCapturedAt(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.captured_at</code>.
     */
    public OffsetDateTime getCapturedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.role</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.vs_role</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setVsRole(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.vs_role</code>.
     */
    public String getVsRole() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.kills</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setKills(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.kills</code>.
     */
    public Long getKills() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.deaths</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setDeaths(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.deaths</code>.
     */
    public Long getDeaths() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.grafana_role_matchup_snapshot.kdr</code>.
     */
    public GrafanaRoleMatchupSnapshotRecord setKdr(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.grafana_role_matchup_snapshot.kdr</code>.
     */
    public BigDecimal getKdr() {
        return (BigDecimal) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrafanaRoleMatchupSnapshotRecord
     */
    public GrafanaRoleMatchupSnapshotRecord() {
        super(GrafanaRoleMatchupSnapshot.GRAFANA_ROLE_MATCHUP_SNAPSHOT);
    }

    /**
     * Create a detached, initialised GrafanaRoleMatchupSnapshotRecord
     */
    public GrafanaRoleMatchupSnapshotRecord(Long id, Integer realm, OffsetDateTime capturedAt, String role, String vsRole, Long kills, Long deaths, BigDecimal kdr) {
        super(GrafanaRoleMatchupSnapshot.GRAFANA_ROLE_MATCHUP_SNAPSHOT);

        setId(id);
        setRealm(realm);
        setCapturedAt(capturedAt);
        setRole(role);
        setVsRole(vsRole);
        setKills(kills);
        setDeaths(deaths);
        setKdr(kdr);
        resetChangedOnNotNull();
    }
}
